### ISSUE TITLE
com.hazelcast.jet.impl.connector.StreamEventJournalP_WmCoalescingTest.when_allPartitionsIdleAndThenRecover_then_wmOutput

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1003]
```
Error Message
processor output in mode "snapshots disabled, inboxLimit=1" doesn't match expected:<Watermark{IDLE_MESSAGE}
Watermark{ts=02:00:00.010}> but was:<Watermark{IDLE_MESSAGE}
Watermark{ts=02:00:00.010}
Watermark{IDLE_MESSAGE}>
```

https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet-jdk9/com.hazelcast.jet$hazelcast-jet-core/286/testReport/junit/com.hazelcast.jet.impl.connector/StreamEventJournalP_WmCoalescingTest/when_allPartitionsIdleAndThenRecover_then_wmOutput/

**Comment by gurbuzali** [comment]
fail again:

https://github.com/hazelcast/hazelcast-jet/issues/1003

```
Error Message

processor output in mode "snapshots disabled, inboxLimit=1" doesn't match expected:<Watermark{IDLE_MESSAGE}
Watermark{ts=02:00:00.012}> but was:<Watermark{IDLE_MESSAGE}
Watermark{ts=02:00:00.012}
Watermark{IDLE_MESSAGE}>

Stacktrace

java.lang.AssertionError: 
processor output in mode "snapshots disabled, inboxLimit=1" doesn't match expected:<Watermark{IDLE_MESSAGE}
Watermark{ts=02:00:00.012}> but was:<Watermark{IDLE_MESSAGE}
Watermark{ts=02:00:00.012}
Watermark{IDLE_MESSAGE}>
	at com.hazelcast.jet.core.test.JetAssert.throwNotEqual(JetAssert.java:63)
	at com.hazelcast.jet.core.test.JetAssert.assertEquals(JetAssert.java:46)
	at com.hazelcast.jet.core.test.TestSupport.runTest(TestSupport.java:580)
	at com.hazelcast.jet.core.test.TestSupport.expectOutputs(TestSupport.java:324)
	at com.hazelcast.jet.core.test.TestSupport.expectOutput(TestSupport.java:307)
	at com.hazelcast.jet.impl.connector.StreamEventJournalP_WmCoalescingTest.when_allPartitionsIdleAndThenRecover_then_wmOutput(StreamEventJournalP_WmCoalescingTest.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
