### ISSUE TITLE
 com.hazelcast.jet.core.JobRestartWithSnapshotTest.stressTest_suspendAndResume

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1009]
```
Error Message
java.lang.AssertionError: expected:<RUNNING> but was:<SUSPENDED>
Stacktrace
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<RUNNING> but was:<SUSPENDED>
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.stressTest(JobRestartWithSnapshotTest.java:452)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.stressTest_suspendAndResume(JobRestartWithSnapshotTest.java:426)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: expected:<RUNNING> but was:<SUSPENDED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$null$15(JobRestartWithSnapshotTest.java:430)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:168)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1246)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1263)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:133)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$stressTest_suspendAndResume$16(JobRestartWithSnapshotTest.java:430)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$stressTest$17(JobRestartWithSnapshotTest.java:448)
	... 2 more
```

https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/846/testReport/junit/com.hazelcast.jet.core/JobRestartWithSnapshotTest/stressTest_suspendAndResume/

**Comment by cangencer** [comment]
Might be related also:

https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/843/testReport/junit/com.hazelcast.jet.core/JobRestartWithSnapshotTest/stressTest_restart/

```
Error Message
java.lang.AssertionError: expected:<RUNNING> but was:<STARTING>
Stacktrace
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<RUNNING> but was:<STARTING>
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.stressTest(JobRestartWithSnapshotTest.java:452)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.stressTest_restart(JobRestartWithSnapshotTest.java:415)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: expected:<RUNNING> but was:<STARTING>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$null$12(JobRestartWithSnapshotTest.java:420)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:168)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1246)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1272)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:129)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$stressTest_restart$13(JobRestartWithSnapshotTest.java:420)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$stressTest$17(JobRestartWithSnapshotTest.java:448)
	... 2 more```
