### ISSUE TITLE
com.hazelcast.jet.impl.connector.StreamJmsPTest.when_queue

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1010]
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/843/testReport/junit/com.hazelcast.jet.impl.connector/StreamJmsPTest/when_queue/

```
Error Message
expected:<34960dc2-c254-4442-89f5-b6aaa98d70c3> but was:<null>
Stacktrace
java.lang.AssertionError: expected:<34960dc2-c254-4442-89f5-b6aaa98d70c3> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.jet.impl.connector.StreamJmsPTest.when_queue(StreamJmsPTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by viliam-durina** [comment]
Looks like a race. The test first asserts the queue size. After it confirms it's 2, it goes to call `processor.complete()`. But that method uses `receiveNoWait` and I guess it's possible that the second message wasn't received yet and since it doesn't block, it will be available later. I'll change it to `assertTrueEventually`.
