### ISSUE TITLE
NullPointerException after a batch job completed.

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-jet#1019]
After a batch job completed, below stack trace logs continuously.

```
52:08,256 [10.0.0.144]:5701 [jet] [0.7-SNAPSHOT] Execution of job '5f85-7712-ce6a-daba', execution 91e6-e2f6-1f3e-054e completed in 57,594 ms
Exception in thread "hz._hzInstance_1_jet.cached.thread-27" java.lang.NullPointerException
    at com.hazelcast.jet.impl.metrics.jmx.JmxPublisher.whenComplete(JmxPublisher.java:120)
    at com.hazelcast.jet.impl.metrics.JetMetricsService.lambda$init$0(JetMetricsService.java:98)
    at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:66)
    at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by viliam-durina** [comment]
The problem was related to the '*' used in vertex name, which wasn't properly escaped. It was then used as a pattern matcher when querying MBeans.
