### ISSUE TITLE
Test failure: ManualRestartTest.when_terminalSnapshotFails_then_previousSnapshotUsed

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#1029]
https://hazelcast-l337.ci.cloudbees.com/job/jet-pr-builder/com.hazelcast.jet$hazelcast-jet-core/3082/testReport/junit/com.hazelcast.jet.core/ManualRestartTest/when_terminalSnapshotFails_then_previousSnapshotUsed/

Simplified error message:

```
{0=2, ... 2337=2, 2338=1, .. 9999=1} expected:<1> but was:<2>

Stacktrace AssertionError: expected:<1> but was:<2>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at com.hazelcast.jet.core.ManualRestartTest.when_terminalSnapshotFails_then_previousSnapshotUsed(ManualRestartTest.java:188)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
    at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.lang.Thread.run(Thread.java:844)```

**Comment by viliam-durina** [comment]
Full test output from archive: [test_output.txt](https://github.com/hazelcast/hazelcast-jet/files/2339923/test_output.txt)

**Comment by cangencer** [comment]
This failed again..

https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/870/testReport/junit/com.hazelcast.jet.core/ManualRestartTest/when_terminalSnapshotFails_then_previousSnapshotUsed/

```first item != 1```

**Comment by cangencer** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/jet-sonar/com.hazelcast.jet$hazelcast-jet-core/1659/testReport/junit/com.hazelcast.jet.core/ManualRestartTest/when_terminalSnapshotFails_then_previousSnapshotUsed/

```
Stacktrace
java.lang.NullPointerException
	at com.hazelcast.jet.core.ManualRestartTest.lambda$when_terminalSnapshotFails_then_previousSnapshotUsed$3(ManualRestartTest.java:170)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:191)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1302)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:152)
	at com.hazelcast.jet.core.ManualRestartTest.when_terminalSnapshotFails_then_previousSnapshotUsed(ManualRestartTest.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
