### ISSUE TITLE
Rolling aggregation does not add timestamps

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#1057]
```java
public class TestCustomSource {

    public static final class MyAccu {
        private long lastTime;
    }

    @Test
    public void foo() {
        StreamSource<String> uuidSource = SourceBuilder.timestampedStream("my source", context -> "")
                .<String>fillBufferFn((a, b) -> b.add(UuidUtil.newUnsecureUuidString()))
                .build();

        AggregateOperation1<Object, MyAccu, Long> latencyBetweenElementsOp = AggregateOperation.withCreate(MyAccu::new)
                .andAccumulate0((acc, event) -> {})
                .andExportFinish(acc -> {
                    long now = System.nanoTime();
                    long delta = now - acc.lastTime;
                    acc.lastTime = now;
                    return delta;
                });

        Pipeline pipeline = Pipeline.create();
        pipeline.drawFrom(uuidSource)
                .map(String::toLowerCase)
                .rollingAggregate(latencyBetweenElementsOp)
                .window(WindowDefinition.sliding(10000, 1000))
                .aggregate(AggregateOperations.averagingLong(e -> e))
                .drainTo(logger());

        JetInstance instance = Jet.newJetInstance();
        instance.newJob(pipeline).join();
    }
}
```

is failing with:
```
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#4}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#0}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#7}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#1}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#6}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#5}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#2}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Exception in ProcessorTasklet{sliding-window-step1#3}
java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)

Sep 19, 2018 5:41:30 PM com.hazelcast.jet.impl.MasterContext
WARNING: [192.168.86.241]:5701 [jet] [0.7-SNAPSHOT] Execution of job 'e56d-6a2a-e68b-9af4', execution e2a7-e4ac-589c-a4d3 failed after 126 ms
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{sliding-window-step1#4}: java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:304)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)


java.util.concurrent.ExecutionException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{sliding-window-step1#4}: java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.hazelcast.jet.Job.lambda$join$0(Job.java:92)
	at com.hazelcast.jet.impl.util.Util.uncheckRun(Util.java:111)
	at com.hazelcast.jet.Job.join(Job.java:92)
	at TestCustomSource.foo(TestCustomSource.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{sliding-window-step1#4}: java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:304)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to com.hazelcast.jet.impl.JetEvent
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.core.processor.Processors.lambda$toFrameTimestampFn$cdcc75bb$1(Processors.java:571)
	at com.hazelcast.jet.function.DistributedToLongFunction.applyAsLong(DistributedToLongFunction.java:39)
	at com.hazelcast.jet.impl.processor.SlidingWindowP.tryProcess(SlidingWindowP.java:148)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:190)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:590)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:111)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:296)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cangencer** [comment]
Fixed by #1065
