### ISSUE TITLE
Kafka cancelled exception not suppressed

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1058]
Not sure if this is a recurrence of https://github.com/hazelcast/hazelcast-jet/issues/824

Stopping a job with `job.cancel()` throws an Interrupted Exception from Kafka 2.0.0,
using hazelcast-jet-kafka-0.7-20180919.141941-164 snapshot build

Job is doing
```
		StreamStage<Entry<Object, Object>> source = 
				pipeline.drawFrom(KafkaSources.kafka(properties, "neil"))

```

Gives this

```
23:21:54.290 [hz._hzInstance_1_oktobap.jet.blocking.ProcessorTasklet{kafkaSource#2}] WARN  com.hazelcast.jet.impl.execution.TaskletExecutionService - [127.0.0.1]:5701 [oktobap] [0.7-SNAPSHOT] Exception in ProcessorTasklet{kafkaSource#2}
 org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:492) ~[kafka-clients-1.0.2.jar!/:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:274) ~[kafka-clients-1.0.2.jar!/:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:230) ~[kafka-clients-1.0.2.jar!/:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:206) ~[kafka-clients-1.0.2.jar!/:?]
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:601) ~[kafka-clients-1.0.2.jar!/:?]
	at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:1211) ~[kafka-clients-1.0.2.jar!/:?]
	at com.hazelcast.jet.kafka.impl.StreamKafkaP.complete(StreamKafkaP.java:200) ~[hazelcast-jet-kafka-0.7-SNAPSHOT.jar!/:0.7-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:343) ~[hazelcast-jet-0.7-SNAPSHOT.jar!/:0.7-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212) ~[hazelcast-jet-0.7-SNAPSHOT.jar!/:0.7-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205) ~[hazelcast-jet-0.7-SNAPSHOT.jar!/:0.7-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:235) [hazelcast-jet-0.7-SNAPSHOT.jar!/:0.7-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.InterruptedException
	... 16 more
23:21:54.360 [hz._hzInstance_1_oktobap.async.thread-4] INFO  com.hazelcast.jet.impl.MasterContext - [127.0.0.1]:5701 [oktobap] [0.7-SNAPSHOT] Execution of job 'GPS Load', execution 4c4f-9dd3-6bb7-6fbe completed in 4,095 ms, reason=java.util.concurrent.CancellationException
```

**Comment by viliam-durina** [comment]
It's similar to #824, but technically it's the same problem in a different place.
