### ISSUE TITLE
 com.hazelcast.jet.kafka.impl.StreamKafkaPTest.when_noAssignedPartitions_thenEmitIdleMsgImmediately

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1124]
https://hazelcast-l337.ci.cloudbees.com/job/jet-jdk9/com.hazelcast.jet$hazelcast-jet-kafka/360/testReport/junit/com.hazelcast.jet.kafka.impl/StreamKafkaPTest/when_noAssignedPartitions_thenEmitIdleMsgImmediately/

```
Error Message
Socket server failed to bind to 127.0.0.1:46989: Address already in use.
Stacktrace
kafka.common.KafkaException: Socket server failed to bind to 127.0.0.1:46989: Address already in use.
	at kafka.network.Acceptor.openServerSocket(SocketServer.scala:331)
	at kafka.network.Acceptor.<init>(SocketServer.scala:256)
	at kafka.network.SocketServer$$anonfun$startup$1.apply(SocketServer.scala:97)
	at kafka.network.SocketServer$$anonfun$startup$1.apply(SocketServer.scala:89)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at kafka.network.SocketServer.startup(SocketServer.scala:89)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:229)
	at kafka.utils.TestUtils$.createServer(TestUtils.scala:133)
	at kafka.utils.TestUtils.createServer(TestUtils.scala)
	at com.hazelcast.jet.kafka.impl.KafkaTestSupport.createKafkaCluster(KafkaTestSupport.java:120)
	at com.hazelcast.jet.kafka.impl.StreamKafkaPTest.before(StreamKafkaPTest.java:93)
```

**Comment by viliam-durina** [comment]
This is an issue in Kafka's `TestUtils` caused by something else grabbing the port in the OS. These issues might be related: [this](https://issues.apache.org/jira/browse/KAFKA-1418) and [this](https://github.com/spring-projects/spring-kafka/issues/582), both are fixed but maybe just similar. We can't fix it in jet anyway.
