### ISSUE TITLE
com.hazelcast.jet.core.GracefulShutdownTest.when_shutdownGracefulWhileRestartGraceful_then_restartsFromTerminalSnapshot

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1156]
https://hazelcast-l337.ci.cloudbees.com/job/jet-jdk9/com.hazelcast.jet$hazelcast-jet-core/408/testReport/junit/com.hazelcast.jet.core/GracefulShutdownTest/when_shutdownGracefulWhileRestartGraceful_then_restartsFromTerminalSnapshot/

```
java.lang.NullPointerException
	at com.hazelcast.jet.core.GracefulShutdownTest.lambda$when_shutdownGracefulWhileRestartGraceful_then_restartsFromTerminalSnapshot$9(GracefulShutdownTest.java:254)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:188)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1294)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1320)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:149)
	at com.hazelcast.jet.core.GracefulShutdownTest.when_shutdownGracefulWhileRestartGraceful_then_restartsFromTerminalSnapshot(GracefulShutdownTest.java:253)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by cangencer** [comment]
http://jenkins.hazelcast.com/job/jet-oss-pr-builder/96/testReport/junit/com.hazelcast.jet.core/GracefulShutdownTest/when_shutdownGracefulWhileRestartGraceful_then_restartsFromTerminalSnapshot/

```
Error Message
test timed out after 300000 milliseconds
Stacktrace
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at com.hazelcast.jet.Job.join(Job.java:104)
	at com.hazelcast.jet.core.GracefulShutdownTest.when_shutdownGracefulWhileRestartGraceful_then_restartsFromTerminalSnapshot(GracefulShutdownTest.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by viliam-durina** [comment]
Locally it doesn't reproduce (100 executions), the logs from this run are lost. I reviewed the test code, didn't spot any problem. Maybe it's related to #918 (the issue reported on Jan 17 in it), but due to the lack of logs I can't confirm.
