### ISSUE TITLE
Improve exception handling for job.join()

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1167]
Currently when you cancel a job and do `join()` the exception looks like follows:

```
Exception in thread "main" java.util.concurrent.CancellationException
	at com.hazelcast.jet.impl.MasterContext.getResult(MasterContext.java:853)
	at com.hazelcast.jet.impl.MasterContext.onExecuteStepCompleted(MasterContext.java:807)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipants$19(MasterContext.java:1074)
	at com.hazelcast.jet.impl.util.Util$2.onFailure(Util.java:174)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

This lacks both a message and also doesn't point to user code but instead to MasterContext. It should instead say something like "Job was cancelled"

**Comment by viliam-durina** [comment]
IMO, message is not necessary, it's implied from the exception class. When you `cancel` a future, there's also no extra message.

Stack trace not pointing to code calling `join` is a flaw in CompletableFuture.join(): 
```
        CompletableFuture f = new CompletableFuture();
        f.cancel(true);
        f.join();
```
`join` will throw:
```
Exception in thread "main" java.util.concurrent.CancellationException
    at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
    at FutureTest.main(FutureTest.java:22)
```
[This OpenJDK issue](https://bugs.openjdk.java.net/browse/JDK-8179667) is similar. We also can't throw CancellationException with a cause, there's no such constructor. We could throw other kind of exception, but that will be even more mess.
