### ISSUE TITLE
Exception while exporting state when the job is in SUSPENDED state

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast-jet#1189]
```
16:02:41,549 ERROR || - [MasterContext] hz._hzInstance_1_jet.async.thread-3 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Exception during callback
java.lang.NullPointerException: Null value is not allowed!
	at com.hazelcast.util.Preconditions.checkNotNull(Preconditions.java:59)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:244)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:238)
	at com.hazelcast.jet.impl.JobRepository.cacheValidationRecord(JobRepository.java:472)
	at com.hazelcast.jet.impl.MasterContext.lambda$exportSnapshot$0(MasterContext.java:340)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalComplete(NonCompletableFuture.java:55)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.onResponse(AbstractJobProxy.java:275)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.onResponse(AbstractJobProxy.java:270)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by viliam-durina** [comment]
I was unable to reproduce the issue. [This is the actual code used](https://github.com/hazelcast/hazelcast-jet/blob/a0021c4d9dda3a397c85b6e402a333759df049c0/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/MasterContext.java#L334-L348).

The stack trace suggests there was a successful snapshot, but yet the validation record was missing. This suggests that the snapshot was deleted in the meantime, but it should not happen since the status is set to `EXPORTING_SNAPSHOT` in a synchronized block. Also, `JobExecutionRecord.snapshotId` is assigned after the validation record is stored.

Giving up for now.

**Comment by eminn** [comment]
I cannot reproduce this issue with the latest master either. Closing this for now.
