### ISSUE TITLE
StreamEventJournalPTest.smokeTest: snapshots not fully restored

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#1261]
## Error Message

processor output in mode "snapshots enabled, restoring every snapshot" doesn't match expected:<0
1
2
3> but was:<0
2
1>

java.lang.AssertionError
	at com.hazelcast.jet.core.test.JetAssert.throwNotEqual(JetAssert.java:67)
	at com.hazelcast.jet.core.test.JetAssert.assertEquals(JetAssert.java:50)
	at com.hazelcast.jet.core.test.TestSupport.runTest(TestSupport.java:582)
	at com.hazelcast.jet.core.test.TestSupport.expectOutputs(TestSupport.java:334)
	at com.hazelcast.jet.core.test.TestSupport.expectOutput(TestSupport.java:302)
	at com.hazelcast.jet.impl.connector.StreamEventJournalPTest.smokeTest(StreamEventJournalPTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

## Standard Output

Finished Running Test: when_lostItems_afterRestore in 15.151 seconds.
13:51:45,171  INFO || - [JobExecutionService] hz._hzInstance_6_jet.cached.thread-5 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Execution plan for jobId=1d75-6ebe-5e2d-19f1, jobName='1d75-6ebe-5e2d-19f1', executionId=1c1b-edaf-840f-df43 initialized
13:51:45,188 DEBUG || - [MasterContext] hz._hzInstance_6_jet.async.thread-3 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Init of job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 was successful
13:51:45,188 DEBUG || - [MasterContext] hz._hzInstance_6_jet.async.thread-3 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Executing job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43
13:51:45,191  INFO || - [JobExecutionService] hz._hzInstance_6_jet.async.thread-3 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Start execution of job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 from coordinator [127.0.0.1]:5701
13:51:45,222 DEBUG || - [Job] when_processorsWithNoPartitions_then_snapshotRestoreWorks - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Sending RESTART_GRACEFUL request for job 1d75-6ebe-5e2d-19f1 (name ??)
13:51:45,224  INFO || - [MasterContext] when_processorsWithNoPartitions_then_snapshotRestoreWorks - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Starting snapshot 0 for job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43, terminal
13:51:45,227 DEBUG || - [JobCoordinationService] hz._hzInstance_6_jet.async.thread-3 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 snapshot is scheduled in 200000ms
13:51:45,250  INFO || - [LifecycleService] Thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
13:51:45,251  INFO || - [MigrationManager] hz._hzInstance_4_jet.cached.thread-2 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Shutdown request of Member [127.0.0.1]:5701 - 25bd1fc9-6c32-40a6-b6ac-3627474b35ef this is handled
13:51:45,252  INFO || - [Node] Thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Shutting down connection manager...
13:51:45,252  INFO || - [Node] Thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Shutting down node engine...
13:51:45,444 DEBUG || - [AsyncSnapshotWriterImpl] hz._hzInstance_6_jet.jet.cooperative.thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Stats for src: keys=2, chunks=1, bytes=89
13:51:45,446 DEBUG || - [SnapshotOperation] hz._hzInstance_6_jet.jet.cooperative.thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Snapshot 0 for job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 finished successfully on member
13:51:45,509 DEBUG || - [JobExecutionService] hz._hzInstance_6_jet.jet.cooperative.thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Execution of job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalComplete(NonCompletableFuture.java:55)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:396)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:332)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:297)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException
	at com.hazelcast.jet.impl.execution.ExecutionContext.lambda$beginExecution$0(ExecutionContext.java:143)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 8 more
13:51:45,677  INFO || - [MasterContext] hz._hzInstance_6_jet.async.thread-5 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Snapshot 0 for job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 completed with status SUCCESS in 375ms, 89 bytes, 2 keys in 1 chunks, stored in '__jet.snapshot.1d75-6ebe-5e2d-19f1.0'
13:51:45,697 DEBUG || - [MasterContext] hz._hzInstance_6_jet.async.thread-7 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Execution of job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 has failures: [MemberInfo{address=[127.0.0.1]:5701, uuid=6fc97810-399e-41e8-94a1-5c43b21ec846, liteMember=false, memberListJoinVersion=1}=com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException]
13:51:45,823 DEBUG || - [MasterContext] hz._hzInstance_6_jet.async.thread-7 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Execution of job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 terminated after a terminal snapshot
13:51:45,835 DEBUG || - [MasterContext] hz._hzInstance_6_jet.async.thread-7 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Sending CompleteExecutionOperation for job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43
13:51:45,915 DEBUG || - [CompleteExecutionOperation] hz._hzInstance_6_jet.async.thread-7 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Completing execution 1c1b-edaf-840f-df43 from caller [127.0.0.1]:5701, error=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_GRACEFUL
13:51:45,960 DEBUG || - [JobRepository] hz._hzInstance_6_jet.async.thread-5 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Cleared snapshot data map __jet.snapshot.1d75-6ebe-5e2d-19f1.1
13:51:45,961 DEBUG || - [MasterContext] hz._hzInstance_6_jet.async.thread-5 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Not beginning snapshot since terminal snapshot is already completed job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43
13:51:46,128 DEBUG || - [JobExecutionService] hz._hzInstance_6_jet.async.thread-7 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Completed execution of job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43
13:51:46,168  INFO || - [MasterContext] ForkJoinPool.commonPool-worker-57 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Execution of job '1d75-6ebe-5e2d-19f1', execution 1c1b-edaf-840f-df43 completed in 4,237 ms, reason=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_GRACEFUL
13:51:46,219  INFO || - [NodeExtension] Thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Destroying node NodeExtension.
13:51:46,254  INFO || - [Node] Thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] Hazelcast Shutdown is completed in 1004 ms.
13:51:46,254  INFO || - [LifecycleService] Thread-0 - [127.0.0.1]:5701 [jet] [0.8-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after smokeTest(com.hazelcast.jet.impl.connector.StreamEventJournalPTest): BuildInfo{version='3.12-SNAPSHOT', build='20190212', buildNumber=20190212, revision=862df02, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='0.8-SNAPSHOT', build='20190213', revision='9c4082e'}}
Hiccups measured while running test 'smokeTest(com.hazelcast.jet.impl.connector.StreamEventJournalPTest):'
13:51:30, accumulated pauses: 2082 ms, max pause: 806 ms, pauses over 1000 ms: 0
13:51:35, accumulated pauses: 2503 ms, max pause: 876 ms, pauses over 1000 ms: 0
13:51:40, accumulated pauses: 2674 ms, max pause: 240 ms, pauses over 1000 ms: 0
13:51:45, accumulated pauses: 438 ms, max pause: 142 ms, pauses over 1000 ms: 0

**Comment by viliam-durina** [comment]
This is a parallel test and the logs are from some other test in the class. Issue is too short timeout (1000ms), but a longer makes the test slower.
