### ISSUE TITLE
Map sources do not provide enough compile-time safety

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1266]
It's possible to write code like this which compiles just fine, even if the Map is just of the type `IMap<Integer, Integer>` but it will fail in runtime.

```
StreamSourceStage<Map.Entry<Integer, Integer>> source = p1.drawFrom(
            Sources.remoteMapJournal(
                    "map", clientConfig, mapPutEvents(), mapEventNewValue(), START_FROM_OLDEST
            )
    );
```

If you want to provide type-hints, it gets overly verbose as you have to specify both the map key/value types and the result type. The sources also have a lot of parameters. We may consider a builder for map sources such as: 
```
Sources.<String, String>remoteMapBuilder(mapName, clientConfig).filter(e -> ).project(e ->).build()
```

**Comment by viliam-durina** [comment]
The failure for the above example is:
```
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{map#0}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Map$Entry
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:315)
	... 3 more
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Map$Entry
	at com.hazelcast.jet.function.FunctionEx.apply(FunctionEx.java:43)
	at com.hazelcast.jet.core.processor.Processors.lambda$null$92c42222$1(Processors.java:700)
	at com.hazelcast.jet.function.FunctionEx.apply(FunctionEx.java:43)
	at com.hazelcast.jet.core.AbstractProcessor$FlatMapper.tryProcess(AbstractProcessor.java:569)
	at com.hazelcast.jet.impl.processor.TransformP.tryProcess(TransformP.java:45)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:188)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:597)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:109)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:290)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:260)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:232)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:308)
```

The point of the issue is that it is hard to understand this. If you have `IMap<Integer, Integer>` and use `mapEventNewValue()`, then you should have `StreamSourceStage<Integer>` and not `StreamSourceStage<Map.Entry<Integer, Integer>>`.
