### ISSUE TITLE
com.hazelcast.jet.impl.util.ExceptionUtilTest.test_serializationFromNodeToClient

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#1330]
http://jenkins.hazelcast.com/job/jet-oss-master-zulu-jdk11/13/testReport/junit/com.hazelcast.jet.impl.util/ExceptionUtilTest/test_serializationFromNodeToClient/

```
Error Message
expected exception not found in causes chain expected:<java.lang.RuntimeException: myException> but was:<java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{source#0}: java.lang.RuntimeException: myException>
Stacktrace
java.lang.AssertionError: expected exception not found in causes chain expected:<java.lang.RuntimeException: myException> but was:<java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{source#0}: java.lang.RuntimeException: myException>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.jet.core.TestUtil.assertExceptionInCauses(TestUtil.java:64)
	at com.hazelcast.jet.impl.util.ExceptionUtilTest.test_serializationFromNodeToClient(ExceptionUtilTest.java:81)
```

**Comment by viliam-durina** [comment]
Two more test runs passed in this builder, looks like an intermittent failure. Looks like the causes were lost, only the top-level exception has passed through, but hard to confirm due to the intertwined logs from multiple tests in the class.

**Comment by cangencer** [comment]
Has this issue occured since? Is it safe to close it?
