### ISSUE TITLE
JobAlreadyExistsException from newJobIfAbsent

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1374]
On Jet 3.0, when my member starts it launches a job with
```
	Job job = this.jetInstance.getJob(jobConfig.getName());
    	if (job == null) {
            job = this.jetInstance.newJobIfAbsent(pipeline, jobConfig);
    	}
```

I start two members at the same time, and this sometimes throws
```
com.hazelcast.jet.JobAlreadyExistsException: Another active job with equal name (MovingAverage) exists: 11e6-482b-0b42-2bcb
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$2(JobCoordinationService.java:190) ~[hazelcast-jet-3.0.jar!/:3.0]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$29(JobCoordinationService.java:878) ~[hazelcast-jet-3.0.jar!/:3.0]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$30(JobCoordinationService.java:897) ~[hazelcast-jet-3.0.jar!/:3.0]
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67) ~[hazelcast-jet-3.0.jar!/:3.0]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227) ~[hazelcast-jet-3.0.jar!/:3.0]
```

**Comment by viliam-durina** [comment]
I tested it, the `newJobIfAbsent` method works as intended. The error is printed because it might be thrown behind the scenes, but it otherwise ignored. I'm removing the printout and also adding a test for parallel submission of equally-named jobs.
