### ISSUE TITLE
StreamSource without createSnapshotFn throws NPE during job restart

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1399]
_master_ (commit 2326ffae153c1fbf17bbddda1b021a6aae762917)

In case when `StreamSource` is created by `SourceBuilder` and `createSnapshotFn`/`restoreSnapshotFn` is not configured then NPE is thrown when job is restarted. It leads to failing that job.

This is regression - it works correctly with Hazelcast jet 3.0 - job is restarted and running there.

Thrown NPE:
```
INFO: [192.168.86.58]:5701 [jet] [3.1-SNAPSHOT] Starting snapshot 0 for job 'fb8a-cf67-785f-2084', execution 18f0-8b91-e41c-22b7, terminal
May 21, 2019 8:20:24 AM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [192.168.86.58]:5701 [jet] [3.1-SNAPSHOT] Exception in ProcessorTasklet{src#0}
java.lang.NullPointerException
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.saveToSnapshot(ConvenientSourceP.java:145)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:327)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:232)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Simplest way for reproduction this issue is remove `createSnapshotFn` and `restoreSnapshotFn` from this `test_faultTolerance()` test - https://github.com/hazelcast/hazelcast-jet/blob/2326ffa/hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourceBuilderTest.java#L332

**Comment by viliam-durina** [comment]
The issue is that createSnapshotFn remains `null` so if a non-ft source is used in a job with processing guarantee, it will fail.
