### ISSUE TITLE
MulticastDiscoveryTest.when_jetClientCreated_then_connectsToJetCluster

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1407]
_master_ (commit 14600ce24926ccc900bad0e7726a1daaf9e382c5)

Failed on Sonar: http://jenkins.hazelcast.com/view/Jet/job/jet-oss-master-sonar-nightly/125/testReport/com.hazelcast.jet/MulticastDiscoveryTest/when_jetClientCreated_then_connectsToJetCluster/

Stacktrace:
```
java.lang.IllegalStateException: Unable to connect to any cluster.
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectToClusterInternal(ClusterConnectorServiceImpl.java:214)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.access$000(ClusterConnectorServiceImpl.java:62)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:279)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:275)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

Problem here seems to be that cluster is started on nodes `5704` and `5706`. However clients try to connect to port `5701`, `5702` and `5703`. It seems that this test case is affected by previous test cases. IIUC it seems that cluster in this test must be started on at least on of expected `5701`, `5702` and `5703` ports otherwise it fails. 

Standard output:
```
...
06:30:22,904  INFO || - [ClusterService] hz._hzInstance_152_jet.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [jet] [3.1-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5704 - b61d0439-0970-4cd8-b902-e21103e714a1 this
	Member [127.0.0.1]:5706 - 2eadd2fb-5352-4860-961b-9415c1d33b6a
]
...
06:30:23,914  WARN || - [ClientConnection] hz.client_14.internal-2 - hz.client_14 [jet] [3.1-SNAPSHOT] [3.12.1-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:41435->/127.0.0.1:5701}, remoteEndpoint=null, lastReadTime=2019-05-23 06:30:23.913, lastWriteTime=2019-05-23 06:30:23.912, closedTime=2019-05-23 06:30:23.914, connected server version=null} closed. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials! Principal: null]
com.hazelcast.client.AuthenticationException: Invalid credentials! Principal: null
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:684)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:644)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
...
06:30:23,922  WARN || - [ClientConnection] hz.client_14.internal-2 - hz.client_14 [jet] [3.1-SNAPSHOT] [3.12.1-SNAPSHOT] ClientConnection{alive=false, connectionId=2, channel=NioChannel{/127.0.0.1:59393->/127.0.0.1:5702}, remoteEndpoint=null, lastReadTime=2019-05-23 06:30:23.921, lastWriteTime=2019-05-23 06:30:23.917, closedTime=2019-05-23 06:30:23.921, connected server version=null} closed. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials! Principal: null]
com.hazelcast.client.AuthenticationException: Invalid credentials! Principal: null
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:684)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:644)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
...
06:30:23,924  WARN || - [ClientConnection] hz.client_14.internal-2 - hz.client_14 [jet] [3.1-SNAPSHOT] [3.12.1-SNAPSHOT] ClientConnection{alive=false, connectionId=3, channel=NioChannel{/127.0.0.1:45919->/127.0.0.1:5703}, remoteEndpoint=null, lastReadTime=2019-05-23 06:30:23.924, lastWriteTime=2019-05-23 06:30:23.923, closedTime=2019-05-23 06:30:23.924, connected server version=null} closed. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials! Principal: null]
com.hazelcast.client.AuthenticationException: Invalid credentials! Principal: null
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:684)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$AuthCallback.onResponse(ClientConnectionManagerImpl.java:644)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:130)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture$InternalDelegatingExecutionCallback.onResponse(ClientInvocationFuture.java:118)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:256)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
...
06:30:26,930  WARN || - [ClusterConnectorService] hz.client_14.cluster- - hz.client_14 [jet] [3.1-SNAPSHOT] [3.12.1-SNAPSHOT] Unable to connect to any address for cluster: jet. The following addresses were tried: [[127.0.0.1]:5703, [127.0.0.1]:5702, [127.0.0.1]:5701]
...
Hiccups measured while running test 'when_jetClientCreated_then_connectsToJetCluster(com.hazelcast.jet.MulticastDiscoveryTest):'
06:30:15, accumulated pauses: 72 ms, max pause: 36 ms, pauses over 1000 ms: 0
06:30:20, accumulated pauses: 86 ms, max pause: 9 ms, pauses over 1000 ms: 0
06:30:25, accumulated pauses: 169 ms, max pause: 149 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
It failed again on PR builder for Jet 4.3-SNAPSHOT: http://jenkins.hazelcast.com/job/jet-oss-pr-builder-nightly-tests/10/testReport/com.hazelcast.jet/MulticastDiscoveryTest/when_jetClientCreated_then_connectsToJetCluster/

Stacktrace:
```
java.lang.IllegalStateException: Unable to connect to any cluster.
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.doConnectToCluster(ClientConnectionManagerImpl.java:397)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToCluster(ClientConnectionManagerImpl.java:346)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.start(ClientConnectionManagerImpl.java:296)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:363)
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
	at com.hazelcast.jet.Jet.newJetClient(Jet.java:195)
	at com.hazelcast.jet.MulticastDiscoveryTest.when_jetClientCreated_then_connectsToJetCluster(MulticastDiscoveryTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
2020-09-21 13:22:43,067 [ WARN] [when_jetClientCreated_then_connectsToJetCluster] [c.h.c.i.c.n.ClientConnection]: hz.client_6 [jet] [4.3-SNAPSHOT] [4.0.3-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:44212->/127.0.0.1:5702}, remoteEndpoint=null, lastReadTime=2020-09-21 13:22:43.067, lastWriteTime=2020-09-21 13:22:43.066, closedTime=2020-09-21 13:22:43.067, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.authenticateOnCluster(ClientConnectionManagerImpl.java:792) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:580) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connect(ClientConnectionManagerImpl.java:423) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.doConnectToCandidateCluster(ClientConnectionManagerImpl.java:451) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.doConnectToCluster(ClientConnectionManagerImpl.java:385) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToCluster(ClientConnectionManagerImpl.java:346) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.start(ClientConnectionManagerImpl.java:296) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:363) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136) [hazelcast-4.0.3-SNAPSHOT.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.jet.Jet.newJetClient(Jet.java:195) [classes/:?]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_jetClientCreated_then_connectsToJetCluster(MulticastDiscoveryTest.java:99) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.0.3-SNAPSHOT-tests.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.0.3-SNAPSHOT-tests.jar:4.0.3-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
...
Hiccups measured while running test 'when_jetClientCreated_then_connectsToJetCluster(com.hazelcast.jet.MulticastDiscoveryTest):'
13:22:35, accumulated pauses: 97 ms, max pause: 42 ms, pauses over 1000 ms: 0
13:22:40, accumulated pauses: 56 ms, max pause: 6 ms, pauses over 1000 ms: 0
13:22:45, accumulated pauses: 26 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:22:50, accumulated pauses: 45 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:22:55, accumulated pauses: 43 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:23:00, accumulated pauses: 147 ms, max pause: 114 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also on common nightly run: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/623/testReport/com.hazelcast.jet/MulticastDiscoveryTest/when_jetClientCreated_then_connectsToJetCluster/
