### ISSUE TITLE
Classloading issue when a job submitted via jet.sh

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast-jet#1420]
When I submitted a JAR file which shades log4j logger I do get the following exception.

```
picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.submit(com.hazelcast.jet.server.JetCommandLine$Verbosity,java.lang.String,java.lang.String,java.io.File,java.util.List) throws java.lang.Exception): java.lang.reflect.InvocationTargetException
    at picocli.CommandLine.execute(CommandLine.java:1207)
    at picocli.CommandLine.access$800(CommandLine.java:141)
    at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
    at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
    at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
    at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
    at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:153)
    at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:131)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:146)
    at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at picocli.CommandLine.execute(CommandLine.java:1189)
    ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
    at com.hazelcast.logging.Log4jFactory.createLogger(Log4jFactory.java:29)
    at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:32)
    at com.hazelcast.logging.LoggerFactorySupport$1.createNew(LoggerFactorySupport.java:30)
    at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:125)
    at com.hazelcast.logging.LoggerFactorySupport.getLogger(LoggerFactorySupport.java:38)
    at com.hazelcast.logging.Logger.getLogger(Logger.java:110)
    at com.hazelcast.logging.Logger.getLogger(Logger.java:64)
    at com.hazelcast.jet.Jet.<clinit>(Jet.java:61)
    at com.hazelcast.jet.server.JetBootstrap.lambda$static$0(JetBootstrap.java:105)
    at com.hazelcast.jet.impl.util.ConcurrentMemoizingSupplier.get(ConcurrentMemoizingSupplier.java:50)
    at com.hazelcast.jet.server.JetBootstrap.getInstance(JetBootstrap.java:170)
    at com.hazelcast.jet.benchmark.trademonitor.JetTradeMonitor.main(JetTradeMonitor.java:124)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 30 more
```

It appears that the classes inside the JAR file is not loaded by the job submitting JVM.

**Comment by eminn** [comment]
For a workaround, until this issue has been fixed, the JAR file can be added to the classpath of the `jet.sh` like below;

```
$ export CLASSPATH=$CLASSPATH:../jet-trade-monitor-3.0.jar
$ ./jet.sh submit ../jet-trade-monitor-3.0.jar
```

**Comment by jerrinot** [comment]
is there anything specific about log4j? or does it affect any library which is used from the code executed from inside the `main` method?

**Comment by viliam-durina** [comment]
@jerrinot The log4j classes are not referenced from the main class, but are loaded using reflection by a class that's not loaded with the custom class loader.

In general, when a class is using reflection to load a user-defined class, it should use the thread context class loader, but `LoggerFactorySupport` does not.

**Comment by cangencer** [comment]
@jerrinot it only affects optional dependencies of HZ. HZ creates the logger like this in Logger.java

```java
private static LoggerFactory tryToCreateLoggerFactory(String className) {
        try {
            return ClassLoaderUtil.newInstance(null, className);
        } catch (Exception e) {
            logError("Failed to create '" + className + "' logger factory:", e);
            return null;
        }
    }
```

This uses the CL that was used to load `Hazelcast` instead of the one used to load the user code.

**Comment by cangencer** [comment]
workaround: 
```
$  CLASSPATH=../jet-trade-monitor-3.0.jar ./jet.sh submit ../jet-trade-monitor-3.0.jar
```
