### ISSUE TITLE
Incorrect message when auto-scaling is off and coordinator is shut down

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1436]
When batch job is running on cluster with more nodes (and auto-scaling is set to `false`) and job coordinator is shutdowned then `TopologyChangedException` with incorrect message is thrown on other members. It shows incorrect time and also execution is set on weird value `0000-0000-0000-0000`:
```
SEVERE: [192.168.1.114]:5701 [jet] [3.1-SNAPSHOT] Execution of job 'e237-6ee0-9112-aa95', execution 0000-0000-0000-0000 failed after 28,037,450 ms
com.hazelcast.jet.core.TopologyChangedException
	at com.hazelcast.jet.impl.JobCoordinationService.completeMasterContextIfJobAlreadyCompleted(JobCoordinationService.java:793)
	at com.hazelcast.jet.impl.JobCoordinationService.startJobIfNotStartedOrCompleted(JobCoordinationService.java:765)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$joinSubmittedJob$7(JobCoordinationService.java:264)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$30(JobCoordinationService.java:897)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by olukas** [comment]
Another thing which can be confusing is that there is no information on `INFO` level about stopping original job. It leads to situation where the message like `Execution of job 'c2dd-d330-7d9a-f458', execution 0000-0000-0000-0000 failed after 16 ms` seems that it talked about original job.
