### ISSUE TITLE
Soak tests failures with Jet 3.2

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1606]
Following soak tests failed during 8-hours run:
* `async-transform-test`
* `job-management-test`
* `large-snapshot-chunk-test`
* `jms-test`
* `jdbc-test`
* `event-journal-test`

(these tests can be found here - https://github.com/hazelcast/hazelcast-jet-ansible-tests)

Log for this soak test can be found here - https://s3.console.aws.amazon.com/s3/object/jet-test-env/jobs/jet-soak-tests-ondrej/2/2019_09_05-23_36_41.zip?region=us-east-1&tab=overview

Thrown exception on client side for `async-transform-test`:
```
java.lang.AssertionError: expected: true, actual: false
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertTrue(AbstractSoakTest.java:176)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertTrue(AbstractSoakTest.java:171)
	at com.hazelcast.jet.tests.async.AsyncTransformTest.test(AsyncTransformTest.java:110)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:70)
	at com.hazelcast.jet.tests.async.AsyncTransformTest.main(AsyncTransformTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:142)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:132)
```

Thrown exception on client side for `job-management-test`:
```
java.lang.AssertionError: Values should be different. Actual: FAILED
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
	at com.hazelcast.jet.tests.common.Util.waitForJobStatus(Util.java:51)
	at com.hazelcast.jet.tests.management.JobManagementTest.test(JobManagementTest.java:86)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:70)
	at com.hazelcast.jet.tests.management.JobManagementTest.main(JobManagementTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:142)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:132)
```

Thrown exception on client side for `large-snapshot-chunk-test`:
```
java.lang.AssertionError: not expected: FAILED, actual: FAILED
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertNotEquals(AbstractSoakTest.java:166)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertNotEquals(AbstractSoakTest.java:161)
	at com.hazelcast.jet.tests.largesnapshotchunk.LargeSnapshotChunkTest.test(LargeSnapshotChunkTest.java:98)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:70)
	at com.hazelcast.jet.tests.largesnapshotchunk.LargeSnapshotChunkTest.main(LargeSnapshotChunkTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:142)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:132)
```

Thrown exception on client side for `jms-test`:
```
java.lang.AssertionError: expected: 554337, actual: 554331
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertEquals(AbstractSoakTest.java:146)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertEquals(AbstractSoakTest.java:141)
	at com.hazelcast.jet.tests.jms.JmsTest.assertCount(JmsTest.java:114)
	at com.hazelcast.jet.tests.jms.JmsTest.test(JmsTest.java:91)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:70)
	at com.hazelcast.jet.tests.jms.JmsTest.main(JmsTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:142)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:132)
```

Thrown exception on client side for `jdbc-test`:
```
java.lang.AssertionError: not expected: FAILED, actual: FAILED
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertNotEquals(AbstractSoakTest.java:166)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertNotEquals(AbstractSoakTest.java:161)
	at com.hazelcast.jet.tests.jdbc.JdbcTest.test(JdbcTest.java:108)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:70)
	at com.hazelcast.jet.tests.jdbc.JdbcTest.main(JdbcTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:142)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:132)
```

Thrown exception on client side for `event-journal-test`:
```
java.lang.AssertionError: not expected: FAILED, actual: FAILED
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertNotEquals(AbstractSoakTest.java:166)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.assertNotEquals(AbstractSoakTest.java:161)
	at com.hazelcast.jet.tests.eventjournal.EventJournalTest.test(EventJournalTest.java:121)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:70)
	at com.hazelcast.jet.tests.eventjournal.EventJournalTest.main(EventJournalTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:142)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:132)
```

**Comment by olukas** [comment]
Regarding `large-snapshot-chunk-test` (from file `/2019_09_05-23_36_41/isolated/54.91.242.153/hazelcast-jet-51.log`):
```
17:34:11,992 ERROR || - [MasterJobContext] hz._hzInstance_1_jet.cached.thread-11 - [10.0.0.11]:5701 [jet] [3.2-SNAPSHOT] Execution of job 'LargeSnapshotChunkTest', execution 0314-dd4b-1e13-0001 failed after 12,502 ms
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{LargeSnapshotChunkTest/VerificationSink#0}: java.lang.IllegalArgumentException: Expected 8 items, but got 7
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:334)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:308)
	at java.lang.Thread.run(Thread.java:748)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.IllegalArgumentException: Expected 8 items, but got 7
	at com.hazelcast.jet.tests.largesnapshotchunk.VerificationProcessor.tryProcess(VerificationProcessor.java:49)
	at com.hazelcast.jet.core.AbstractProcessor.tryProcess0(AbstractProcessor.java:188)
	at com.hazelcast.jet.core.AbstractProcessor.process0(AbstractProcessor.java:596)
	at com.hazelcast.jet.core.AbstractProcessor.process(AbstractProcessor.java:109)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:54)
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:193)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:300)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:270)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:242)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:327)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:308)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by olukas** [comment]
There was `com.hazelcast.spi.exception.TargetNotMemberException` failure in soak tests on `isolated` cluster. _(This 8-hours soak test run was executed without `CooperativeMapCacheSourceTest` which currently causes some troubles.)_

Following tests failed in the same time with that exception:
* `large-snapshot-chunk-test`
* `rolling-aggregate-test`

Stacktrace + output on client side:
```
2019-09-08 00:33:00.273] [INFO   ] com.hazelcast.client.connection.nio.ClientConnection - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] ClientConnection{alive=false, connectionId=77, channel=NioChannel{/10.0.0.114:53408->/10.0.0.81:5701}, remoteEndpoint=[10.0.0.81]:5701, lastReadTime=2019-09-08 00:33:00.272, lastWriteTime=2019-09-08 00:32:57.655, closedTime=2019-09-08 00:33:00.272, connected server version=3.12.2} closed. Reason: Connection closed by the other side 
[2019-09-08 00:33:00.274] [INFO   ] com.hazelcast.client.connection.ClientConnectionManager - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Removed connection to endpoint: [10.0.0.81]:5701, connection: ClientConnection{alive=false, connectionId=77, channel=NioChannel{/10.0.0.114:53408->/10.0.0.81:5701}, remoteEndpoint=[10.0.0.81]:5701, lastReadTime=2019-09-08 00:33:00.272, lastWriteTime=2019-09-08 00:32:57.655, closedTime=2019-09-08 00:33:00.272, connected server version=3.12.2} 
[2019-09-08 00:33:01.275] [INFO   ] com.hazelcast.client.connection.nio.ClientConnection - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] ClientConnection{alive=false, connectionId=78, channel=NioChannel{/10.0.0.114:60779->/10.0.0.74:5701}, remoteEndpoint=[10.0.0.74]:5701, lastReadTime=2019-09-08 00:33:01.275, lastWriteTime=2019-09-08 00:32:58.228, closedTime=2019-09-08 00:33:01.275, connected server version=3.12.2} closed. Reason: Connection closed by the other side 
[2019-09-08 00:33:01.275] [INFO   ] com.hazelcast.client.connection.ClientConnectionManager - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Removed connection to endpoint: [10.0.0.74]:5701, connection: ClientConnection{alive=false, connectionId=78, channel=NioChannel{/10.0.0.114:60779->/10.0.0.74:5701}, remoteEndpoint=[10.0.0.74]:5701, lastReadTime=2019-09-08 00:33:01.275, lastWriteTime=2019-09-08 00:32:58.228, closedTime=2019-09-08 00:33:01.275, connected server version=3.12.2} 
[2019-09-08 00:33:02.273] [INFO   ] com.hazelcast.client.connection.nio.ClientConnection - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] ClientConnection{alive=false, connectionId=79, channel=NioChannel{/10.0.0.114:55116->/10.0.0.48:5701}, remoteEndpoint=[10.0.0.48]:5701, lastReadTime=2019-09-08 00:33:02.273, lastWriteTime=2019-09-08 00:32:57.654, closedTime=2019-09-08 00:33:02.273, connected server version=3.12.2} closed. Reason: Connection closed by the other side 
[2019-09-08 00:33:02.275] [INFO   ] com.hazelcast.client.connection.ClientConnectionManager - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Removed connection to endpoint: [10.0.0.48]:5701, connection: ClientConnection{alive=false, connectionId=79, channel=NioChannel{/10.0.0.114:55116->/10.0.0.48:5701}, remoteEndpoint=[10.0.0.48]:5701, lastReadTime=2019-09-08 00:33:02.273, lastWriteTime=2019-09-08 00:32:57.654, closedTime=2019-09-08 00:33:02.273, connected server version=3.12.2} 
[2019-09-08 00:33:02.275] [INFO   ] com.hazelcast.core.LifecycleService - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] HazelcastClient 3.12.2 (20190802 - 46fbe3e, e34b163) is CLIENT_DISCONNECTED 
[2019-09-08 00:33:02.275] [INFO   ] com.hazelcast.client.connection.nio.ClusterConnectorService - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Trying to connect to cluster with name: jet 
[2019-09-08 00:33:02.275] [INFO   ] com.hazelcast.client.connection.nio.ClusterConnectorService - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Trying to connect to [10.0.0.81]:5701 as owner member 
[2019-09-08 00:33:02.277] [WARNING] com.hazelcast.client.connection.nio.ClusterConnectorService - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Exception during initial connection to [10.0.0.81]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /10.0.0.81:5701 
[2019-09-08 00:33:02.277] [INFO   ] com.hazelcast.client.connection.nio.ClusterConnectorService - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Trying to connect to [10.0.0.18]:5701 as owner member 
[2019-09-08 00:33:03.983] [INFO   ] com.hazelcast.client.connection.ClientConnectionManager - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Setting ClientConnection{alive=true, connectionId=80, channel=NioChannel{/10.0.0.114:38063->/10.0.0.18:5701}, remoteEndpoint=[10.0.0.18]:5701, lastReadTime=2019-09-08 00:33:03.982, lastWriteTime=2019-09-08 00:33:02.279, closedTime=never, connected server version=3.12.2} as owner with principal ClientPrincipal{uuid='5f016173-df0e-46d5-86fe-d13019048c23', ownerUuid='11c0e75f-595f-480d-8eda-558e422281ef'} 
[2019-09-08 00:33:03.983] [INFO   ] com.hazelcast.client.connection.ClientConnectionManager - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Authenticated with server [10.0.0.18]:5701, server version:3.12.2 Local address: /10.0.0.114:38063 
[2019-09-08 00:33:03.984] [INFO   ] com.hazelcast.client.spi.impl.ClientMembershipListener - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] 

Members [1] {
	Member [10.0.0.18]:5701 - 11c0e75f-595f-480d-8eda-558e422281ef
}
 
[2019-09-08 00:33:03.985] [INFO   ] com.hazelcast.core.LifecycleService - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] HazelcastClient 3.12.2 (20190802 - 46fbe3e, e34b163) is CLIENT_CONNECTED 
com.hazelcast.spi.exception.TargetNotMemberException: Target '[10.0.0.81]:5701' is not a member.
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:66)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:165)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.jet.impl.ClientJobProxy.getStatus(ClientJobProxy.java:72)
	at com.hazelcast.jet.tests.rolling.RollingAggregateTest.test(RollingAggregateTest.java:83)
	at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:70)
	at com.hazelcast.jet.tests.rolling.RollingAggregateTest.main(RollingAggregateTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.executeJar(JetBootstrap.java:142)
	at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at picocli.CommandLine.execute(CommandLine.java:1189)
	at picocli.CommandLine.access$800(CommandLine.java:141)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:155)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:132)
[2019-09-08 00:33:04.051] [SEVERE ] com.hazelcast.jet.tests.rolling.RollingAggregateTest - hz.client_0 [jet] [3.2-SNAPSHOT] [3.12.2] Target '[10.0.0.81]:5701' is not a member. 
[2019-09-08 00:33:04.056] [INFO   ] com.hazelcast.core.LifecycleService - hz.client_1 [jet] [3.2-SNAPSHOT] [3.12.2] HazelcastClient 3.12.2 (20190802 - 46fbe3e, e34b163) is SHUTTING_DOWN
```

Server log for `10.0.0.18` machine:
```
00:32:59,781 DEBUG || - [JobExecutionService] hz._hzInstance_1_jet.jet.cooperative.thread-0 - [10.0.0.18]:5701 [jet] [3.2-SNAPSHOT] Execution of job 'RollingAggregateTest', execution 0317-d064-3788-0006 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalComplete(NonCompletableFuture.java:55)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:415)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:351)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:329)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:308)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException
	at com.hazelcast.jet.impl.execution.ExecutionContext.lambda$beginExecution$0(ExecutionContext.java:148)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 10 more
...
00:33:07,276  INFO || - [LifecycleService] hz._hzInstance_1_jet.cached.thread-10 - [10.0.0.18]:5701 [jet] [3.2-SNAPSHOT] [10.0.0.18]:5701 is SHUTDOWN
```

Server log for `10.0.0.81` machine:
```
00:32:59,719 DEBUG || - [JobExecutionService] hz._hzInstance_1_jet.jet.cooperative.thread-6 - [10.0.0.81]:5701 [jet] [3.2-SNAPSHOT] Execution of job 'RollingAggregateTest', execution 0317-d064-3788-0006 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalComplete(NonCompletableFuture.java:55)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:415)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:351)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:329)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:308)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.jet.impl.exception.TerminatedWithSnapshotException
	at com.hazelcast.jet.impl.execution.ExecutionContext.lambda$beginExecution$0(ExecutionContext.java:148)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 10 more
...
00:33:00,275  INFO || - [LifecycleService] hz._hzInstance_1_jet..clusterShutdown - [10.0.0.81]:5701 [jet] [3.2-SNAPSHOT] [10.0.0.81]:5701 is SHUTDOWN
```

Also both other machines `10.0.0.74` and `10.0.0.48` went down in that time.

**Comment by viliam-durina** [comment]
Possibly resolved by https://github.com/hazelcast/hazelcast-jet-ansible/pull/13 (adding the `-XX:MaxMetaspaceSize=`) option.

**Comment by olukas** [comment]
Adding `-XX:MaxMetaspaceSize=` fixed most of the issues. Only issues from https://github.com/hazelcast/hazelcast-jet/issues/1606#issuecomment-529334169 occured in 8 hours soak tests.
