### ISSUE TITLE
com.hazelcast.jet.MulticastDiscoveryTest.when_jetClientCreated_then_connectsToJetCluster

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1615]
_3.1-maintenance_ (commit b79453edce91c6ab3bfbf57d7574f89fdb572f01)

Failed on Oracle JDK11: http://jenkins.hazelcast.com/job/jet-oss-maintenance-oracle-jdk11/63/testReport/junit/com.hazelcast.jet/MulticastDiscoveryTest/when_jetClientCreated_then_connectsToJetCluster/

Stacktrace:
```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.jet.MulticastDiscoveryTest.when_jetClientCreated_then_connectsToJetCluster(MulticastDiscoveryTest.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Hiccups measured while running test 'when_jetClientCreated_then_connectsToJetCluster(com.hazelcast.jet.MulticastDiscoveryTest):'
16:24:30, accumulated pauses: 75 ms, max pause: 10 ms, pauses over 1000 ms: 0
16:24:35, accumulated pauses: 287 ms, max pause: 167 ms, pauses over 1000 ms: 0
16:24:40, accumulated pauses: 6 ms, max pause: 1 ms, pauses over 1000 ms: 0
```

**Comment by viliam-durina** [comment]
Very similar to #1503

**Comment by cangencer** [comment]
we are not going to release a maintenance release for 3.1 so we can close this.
