### ISSUE TITLE
JetClassLoader in ContextFactory create function causes cluster lockdown

### ISSUE THREAD

**Issue by Alexichlol** [hazelcast/hazelcast-jet#1625]
We have library used in ContextFactory which uses class loader and has synchronized cache on it initialization, so from the looks of it generic operation thread picks up the lock and then JetClassLoader tries to access IMap, while all partition threads using that ContextFactory try to acquire that lock which causes cluster lockup. (The job startup context gets created on generic-operation thread, while operating functions happen on partition threads. (On job startup context gets created on generic-operation thread -> it uses classloader, tries to check keys from IMap -> partition threads are locked, waiting for this thread, while this thread is waiting for partition threads in my understanding) Attaching part of the thread dump.

```
"hz._hzInstance_1_BG-AWS-PERF-smartstream-6.generic-operation.thread-2" - Thread t@49
   java.lang.Thread.State: WAITING
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:323)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:161)
	at com.hazelcast.map.impl.proxy.MapProxySupport.containsKeyInternal(MapProxySupport.java:662)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.containsKey(MapProxyImpl.java:299)
	at com.hazelcast.jet.impl.deployment.JetClassLoader.findResource(JetClassLoader.java:79)
	at com.hazelcast.jet.impl.deployment.JetClassLoader.findResources(JetClassLoader.java:95)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1459)
	at com.oracle.truffle.polyglot.LanguageCache.collectLanguages(LanguageCache.java:273)
	at com.oracle.truffle.polyglot.LanguageCache.createLanguages(LanguageCache.java:249)
	at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:236)
	- locked <50ced0f4> (a java.lang.Class)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.languages(PolyglotEngineImpl.java:551)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:499)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:193)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:175)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:216)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:505)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1389)
	at com.g.s.s.context.JetStreamExecutionContext.createExecutionContext(JetStreamExecutionContext.java:68)
	at com.g.s.s.context.JetStreamExecutionContext.lambda$createFactory$245c86b4$1(JetStreamExecutionContext.java:55)
	at com.g.s.s.context.JetStreamExecutionContext$$Lambda$996/1997258459.applyEx(Unknown Source)
	at com.hazelcast.jet.function.FunctionEx.apply(FunctionEx.java:43)
	at com.hazelcast.jet.impl.processor.TransformUsingContextP.init(TransformUsingContextP.java:77)
	at com.hazelcast.jet.core.AbstractProcessor.init(AbstractProcessor.java:83)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.init(ProcessorTasklet.java:221)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$$Lambda$1110/974801219.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.lambda$submitCooperativeTasklets$4(TaskletExecutionService.java:167)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$$Lambda$1109/536815502.run(Unknown Source)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:626)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets(TaskletExecutionService.java:166)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.beginExecute(TaskletExecutionService.java:131)
	at com.hazelcast.jet.impl.execution.ExecutionContext.beginExecution(ExecutionContext.java:136)
	- locked <4bfe2bf1> (a java.lang.Object)
	at com.hazelcast.jet.impl.JobExecutionService.beginExecution(JobExecutionService.java:333)
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:44)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:50)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:416)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:153)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:123)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)

   Locked ownable synchronizers:
	- None`

`"hz._hzInstance_1_BG-AWS-PERF-smartstream-6.partition-operation.thread-0" - Thread t@26
   java.lang.Thread.State: BLOCKED
	at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:233)
	- waiting to lock <50ced0f4> (a java.lang.Class) owned by "hz._hzInstance_1_BG-AWS-PERF-smartstream-6.generic-operation.thread-2" t@49
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.languages(PolyglotEngineImpl.java:551)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:499)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:193)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:175)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:216)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:505)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1389)
	at com.g.s.s.context.JetStreamExecutionContext.createExecutionContext(JetStreamExecutionContext.java:68)
	at com.g.s.s.context.JetStreamExecutionContext.lambda$createFactory$245c86b4$1(JetStreamExecutionContext.java:55)
	at com.g.s.s.context.JetStreamExecutionContext$$Lambda$996/1997258459.applyEx(Unknown Source)
	at com.hazelcast.jet.function.FunctionEx.apply(FunctionEx.java:43)
	at com.g.s.s.function.JetStreamReduction.applyInternal(JetStreamReduction.java:32)
	at com.g.s.s.function.JetStreamReduction.applyInternal(JetStreamReduction.java:12)
	at com.g.s.s.function.MonitoredBiFunction.lambda$applyEx$ac9c3e4d$1(MonitoredBiFunction.java:10)
	at com.g.s.s.function.MonitoredBiFunction$$Lambda$1312/1525946475.getEx(Unknown Source)
	at com.hazelcast.jet.function.SupplierEx.get(SupplierEx.java:41)
	at com.g.s.s.context.JetStreamMonitor.time(JetStreamMonitor.java:23)
	at com.g.s.s.function.MonitoredLambda.monitor(MonitoredLambda.java:21)
	at com.g.s.s.function.MonitoredBiFunction.applyEx(MonitoredBiFunction.java:10)
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:563)
	at com.g.s.s.StreamingHelper$AggregatedReduction.applyEx(StreamingHelper.java:105)
	at com.g.s.s.StreamingHelper$AggregatedReduction.applyEx(StreamingHelper.java:92)
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)

   Locked ownable synchronizers:
	- None

"hz._hzInstance_1_BG-AWS-PERF-smartstream-6.partition-operation.thread-1" - Thread t@27
   java.lang.Thread.State: BLOCKED
	at com.oracle.truffle.polyglot.LanguageCache.languages(LanguageCache.java:233)
	- waiting to lock <50ced0f4> (a java.lang.Class) owned by "hz._hzInstance_1_BG-AWS-PERF-smartstream-6.generic-operation.thread-2" t@49
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.languages(PolyglotEngineImpl.java:551)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.initializeLanguages(PolyglotEngineImpl.java:499)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:193)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:175)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:216)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:505)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1389)
	at com.g.s.s.context.JetStreamExecutionContext.createExecutionContext(JetStreamExecutionContext.java:68)
	at com.g.s.s.context.JetStreamExecutionContext.lambda$createFactory$245c86b4$1(JetStreamExecutionContext.java:55)
	at com.g.s.s.context.JetStreamExecutionContext$$Lambda$996/1997258459.applyEx(Unknown Source)
	at com.hazelcast.jet.function.FunctionEx.apply(FunctionEx.java:43)
	at com.g.s.s.function.JetStreamReduction.applyInternal(JetStreamReduction.java:32)
	at com.g.s.s.function.JetStreamReduction.applyInternal(JetStreamReduction.java:12)
	at com.g.s.s.function.MonitoredBiFunction.lambda$applyEx$ac9c3e4d$1(MonitoredBiFunction.java:10)
	at com.g.s.s.function.MonitoredBiFunction$$Lambda$1312/1525946475.getEx(Unknown Source)
	at com.hazelcast.jet.function.SupplierEx.get(SupplierEx.java:41)
	at com.g.s.s.context.JetStreamMonitor.time(JetStreamMonitor.java:23)
	at com.g.s.s.function.MonitoredLambda.monitor(MonitoredLambda.java:21)
	at com.g.s.s.function.MonitoredBiFunction.applyEx(MonitoredBiFunction.java:10)
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)

   Locked ownable synchronizers:
	- None
```

**Comment by viliam-durina** [comment]
Could you share the full thread dump? I suspect it's an issue of Jet.
