### ISSUE TITLE
com.hazelcast.jet.pipeline.StatefulMappingStressTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1651]
_master_ (commit 02e14e910ac8c231c623c8193f3c025faa14b836)

Failed on Sonar nightly build: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/254/testReport/junit/com.hazelcast.jet.pipeline/StatefulMappingStressTest/mapStateful_stressTest/

Stacktrace:
```
java.lang.AssertionError: expected:<2000000> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.jet.pipeline.StatefulMappingStressTest.lambda$stressTest$2(StatefulMappingStressTest.java:104)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:203)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1412)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:160)
	at com.hazelcast.jet.pipeline.StatefulMappingStressTest.stressTest(StatefulMappingStressTest.java:103)
	at com.hazelcast.jet.pipeline.StatefulMappingStressTest.mapStateful_stressTest(StatefulMappingStressTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

It works correctly if `static` variables are used for counters.

**Comment by olukas** [comment]
Fixed by https://github.com/hazelcast/hazelcast-jet/pull/1652
