### ISSUE TITLE
com.hazelcast.jet.core.JobTest.when_joinFromClientTimesOut_then_futureShouldNotBeCompletedEarly

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1660]
_master_ (commit f8fd5970adfbfcf47944e306bbe569924ace8c27)

Failed on OracleJDK 11: http://jenkins.hazelcast.com/job/jet-oss-master-oracle-jdk11/111/testReport/junit/com.hazelcast.jet.core/JobTest/when_joinFromClientTimesOut_then_futureShouldNotBeCompletedEarly/

Stacktrace:
```
com.hazelcast.spi.exception.TargetNotMemberException: Target '[127.0.0.1]:5701' is not a member.
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:66)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:165)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:194)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:179)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:163)
	at com.hazelcast.jet.impl.ClientJobProxy$CancellableFuture.get(ClientJobProxy.java:214)
	at com.hazelcast.jet.impl.ClientJobProxy$CancellableFuture.get(ClientJobProxy.java:189)
	at com.hazelcast.jet.impl.AbstractJobProxy.terminate(AbstractJobProxy.java:158)
	at com.hazelcast.jet.impl.AbstractJobProxy.cancel(AbstractJobProxy.java:141)
	at com.hazelcast.jet.core.JobTest.when_joinFromClientTimesOut_then_futureShouldNotBeCompletedEarly(JobTest.java:779)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Hiccups measured while running test 'when_joinFromClientTimesOut_then_futureShouldNotBeCompletedEarly(com.hazelcast.jet.core.JobTest):'
19:40:50, accumulated pauses: 320 ms, max pause: 6 ms, pauses over 1000 ms: 0
19:40:55, accumulated pauses: 299 ms, max pause: 226 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also in `3.2` branch - http://jenkins.hazelcast.com/view/Jet%20-%20Release/job/release-jet-oss-master-ibm-jdk8/2/testReport/com.hazelcast.jet.core/JobTest/when_joinFromClientTimesOut_then_futureShouldNotBeCompletedEarly/
