### ISSUE TITLE
SAX error from Jet Management Center with "custom" XML

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#1724]
Jet Managament Center 3.2 gives a SAX parse exception with a customised client config file, changed in the minimum way.

Steps to recreate,
```
sed 's/<name>jet</<name>fitba</' < hazelcast-client.xml  > hazelcast-client-fitba.xml
```
(Take the provided `hazelcast-client.xml` and amend the group name)

Proof only group name changed
```
$ diff hazelcast-client.xml hazelcast-client-fitba.xml
22c22
<         <name>jet</name>
---
>         <name>fitba</name>
$ 
```

Then start Management Center
```
./jet-management-center.sh --client-config=hazelcast-client-fitba.xml
```

Gives
```
2019-11-06 10:53:27.914  INFO 1560 --- [ient_0.cluster-] com.hazelcast.core.LifecycleService      : hz.client_0 [fitba] [3.2] [3.12.3] HazelcastClient 3.12.3 (20191003 - fea8197, 3b1d495) is CLIENT_CONNECTED
2019-11-06 10:53:27.995  INFO 1560 --- [           main] com.hazelcast.config.InMemoryXmlConfig   : Configuring Hazelcast from 'in-memory xml'.
2019-11-06 10:53:28.175  WARN 1560 --- [           main] org.eclipse.jetty.webapp.WebAppContext   : Failed startup of context o.s.b.w.e.j.JettyEmbeddedWebAppContext@2f4919b0{application,/,[file:///private/var/folders/v6/qlr8vw9j4q73w41g_s0n9m4w0000gn/T/jetty-docbase.7037561524257878509.8081/],UNAVAILABLE}

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'filterConfiguration': Unsatisfied dependency expressed through field 'connectedFilter'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'connectedFilter' defined in URL [jar:file:/Applications/hazelcast-jet-management-center-3.2/hazelcast-jet-management-center-3.2.jar!/BOOT-INF/classes!/com/hazelcast/jet/management/filter/ConnectedFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientService' defined in URL [jar:file:/Applications/hazelcast-jet-management-center-3.2/hazelcast-jet-management-center-3.2.jar!/BOOT-INF/classes!/com/hazelcast/jet/management/service/ClientService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.jet.management.service.ClientService$$EnhancerBySpringCGLIB$$9e9e8505]: Constructor threw exception; nested exception is com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.hazelcast.com/schema/config":factory-class-name}'. One of '{"http://www.hazelcast.com/schema/config":write-delay-seconds, "http://www.hazelcast.com/schema/config":write-batch-size, "http://www.hazelcast.com/schema/config":write-coalescing, "http://www.hazelcast.com/schema/config":properties}' is expected.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:235) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:226) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:101) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:88) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:261) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:234) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.callInitializers(ServletContextInitializerConfiguration.java:66) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.configure(ServletContextInitializerConfiguration.java:55) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517) ~[jetty-webapp-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1454) ~[jetty-webapp-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852) ~[jetty-server-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278) ~[jetty-servlet-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545) ~[jetty-webapp-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138) ~[jetty-util-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.server.Server.start(Server.java:415) ~[jetty-server-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108) ~[jetty-util-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113) ~[jetty-server-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.server.Server.doStart(Server.java:382) ~[jetty-server-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.4.14.v20181114.jar!/:9.4.14.v20181114]
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:108) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.<init>(JettyWebServer.java:86) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getJettyWebServer(JettyServletWebServerFactory.java:410) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:153) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at com.hazelcast.jet.management.Application.main(Application.java:49) ~[classes!/:3.2]
	at com.hazelcast.jet.management.JetManagementCenterCommandLine.call(JetManagementCenterCommandLine.java:145) ~[classes!/:3.2]
	at com.hazelcast.jet.management.JetManagementCenterCommandLine.call(JetManagementCenterCommandLine.java:38) ~[classes!/:3.2]
	at picocli.CommandLine.execute(CommandLine.java:1173) ~[hazelcast-jet-enterprise-3.2.jar!/:na]
	at picocli.CommandLine.access$800(CommandLine.java:141) ~[hazelcast-jet-enterprise-3.2.jar!/:na]
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1413) ~[hazelcast-jet-enterprise-3.2.jar!/:na]
	at picocli.CommandLine$RunAll.handle(CommandLine.java:1376) ~[hazelcast-jet-enterprise-3.2.jar!/:na]
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243) ~[hazelcast-jet-enterprise-3.2.jar!/:na]
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526) ~[hazelcast-jet-enterprise-3.2.jar!/:na]
	at com.hazelcast.jet.management.JetManagementCenterCommandLine.runCommandLine(JetManagementCenterCommandLine.java:131) ~[classes!/:3.2]
	at com.hazelcast.jet.management.JetManagementCenterCommandLine.main(JetManagementCenterCommandLine.java:114) ~[classes!/:3.2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[hazelcast-jet-management-center-3.2.jar:3.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[hazelcast-jet-management-center-3.2.jar:3.2]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[hazelcast-jet-management-center-3.2.jar:3.2]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[hazelcast-jet-management-center-3.2.jar:3.2]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'connectedFilter' defined in URL [jar:file:/Applications/hazelcast-jet-management-center-3.2/hazelcast-jet-management-center-3.2.jar!/BOOT-INF/classes!/com/hazelcast/jet/management/filter/ConnectedFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientService' defined in URL [jar:file:/Applications/hazelcast-jet-management-center-3.2/hazelcast-jet-management-center-3.2.jar!/BOOT-INF/classes!/com/hazelcast/jet/management/service/ClientService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.jet.management.service.ClientService$$EnhancerBySpringCGLIB$$9e9e8505]: Constructor threw exception; nested exception is com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.hazelcast.com/schema/config":factory-class-name}'. One of '{"http://www.hazelcast.com/schema/config":write-delay-seconds, "http://www.hazelcast.com/schema/config":write-batch-size, "http://www.hazelcast.com/schema/config":write-coalescing, "http://www.hazelcast.com/schema/config":properties}' is expected.
```

It gets as far as `CLIENT_CONNECTED` so I don't really think the XML can be wrong

**Comment by neilstevenson** [comment]
This error is actually "user error" (by me) , the server side was 3.1 and the Jet MC was 3.2.

So, this issue is really that Jet Management Center connects (Jet 3.1 and 3.2 both embed IMDG 3.12) but don't give a helpful error message

**Comment by cangencer** [comment]
@neilstevenson I'm closing this issue, we have another issue open for what you mentioned already: https://github.com/hazelcast/hazelcast-jet/issues/1468
