### ISSUE TITLE
com.hazelcast.jet.core.JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot_singleStage

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1757]
_3.2-maintenance_ (commit 166503c66113d5fe3d7e3158f4aba87cc683a7b9)

Failed on Oracle JDK 11: http://jenkins.hazelcast.com/job/jet-oss-maintenance-oracle-jdk11/74/testReport/junit/com.hazelcast.jet.core/JobRestartWithSnapshotTest/when_nodeDown_then_jobRestartsFromSnapshot_singleStage/

Stacktrace:
```
java.lang.AssertionError: No snapshot produced
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.jet.core.JetTestSupport.lambda$waitForFirstSnapshot$5(JetTestSupport.java:235)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:203)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1327)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:164)
	at com.hazelcast.jet.core.JetTestSupport.waitForFirstSnapshot(JetTestSupport.java:232)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot(JobRestartWithSnapshotTest.java:204)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot_singleStage(JobRestartWithSnapshotTest.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Hiccups measured while running test 'when_nodeDown_then_jobRestartsFromSnapshot_singleStage(com.hazelcast.jet.core.JobRestartWithSnapshotTest):'
16:20:35, accumulated pauses: 567 ms, max pause: 31 ms, pauses over 1000 ms: 0
16:20:40, accumulated pauses: 1379 ms, max pause: 114 ms, pauses over 1000 ms: 0
16:20:45, accumulated pauses: 1415 ms, max pause: 174 ms, pauses over 1000 ms: 0
16:20:50, accumulated pauses: 868 ms, max pause: 237 ms, pauses over 1000 ms: 0
```

**Comment by gurbuzali** [comment]
The test looks very time sensitive, we check the snapshot for 3 seconds after submitting the job and the snapshot interval is 1200ms. So if get more than 2 seconds pause on the system the test fails. I suggest to increase the timeout a bit, since I couldn't reproduce it on my local.
