### ISSUE TITLE
CustomByteArrayOutputStream's "java.lang.IllegalStateException: buffer full" while creating Snapshot

### ISSUE THREAD

**Issue by mtishchuk** [hazelcast/hazelcast-jet#1770]
``` hazelcast-jet 3.0, java-11.0.1  ```

3 node cluster

Options: ```--illegal-access=warn -Xms15g -Xmx15g -XX:+AlwaysPreTouch -XX:+ScavengeBeforeFullGC -XX:+UseG1GC -XX:+ParallelRefProcEnabled --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dhazelcast.jmx=true ```

Failed on creating Snapshot of Job, probably Job Snapshot was huge, but I can't reproduce issue locally, I get only OOM's.
Stacktrace:
```
Caused by: java.lang.IllegalStateException: buffer full
	at com.hazelcast.jet.impl.util.AsyncSnapshotWriterImpl$CustomByteArrayOutputStream.ensureCapacity(AsyncSnapshotWriterImpl.java:464)
	at com.hazelcast.jet.impl.util.AsyncSnapshotWriterImpl$CustomByteArrayOutputStream.write(AsyncSnapshotWriterImpl.java:452)
	at com.hazelcast.jet.impl.util.AsyncSnapshotWriterImpl.getBufferContentsAndClear(AsyncSnapshotWriterImpl.java:206)
	at com.hazelcast.jet.impl.util.AsyncSnapshotWriterImpl.lambda$flushPartition$1(AsyncSnapshotWriterImpl.java:198)
	at com.hazelcast.jet.impl.util.AsyncSnapshotWriterImpl.putAsyncToMap(AsyncSnapshotWriterImpl.java:231)
	at com.hazelcast.jet.impl.util.AsyncSnapshotWriterImpl.flushPartition(AsyncSnapshotWriterImpl.java:198)
	at com.hazelcast.jet.impl.util.AsyncSnapshotWriterImpl.offer(AsyncSnapshotWriterImpl.java:170)
	at com.hazelcast.jet.impl.execution.StoreSnapshotTasklet.addToInbox(StoreSnapshotTasklet.java:145)
	at com.hazelcast.jet.impl.execution.ConcurrentInboundEdgeStream$ItemDetector.test(ConcurrentInboundEdgeStream.java:233)
	at com.hazelcast.internal.util.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:92)
	at com.hazelcast.jet.impl.execution.ConcurrentInboundEdgeStream.drainQueue(ConcurrentInboundEdgeStream.java:190)
	at com.hazelcast.jet.impl.execution.ConcurrentInboundEdgeStream.drainTo(ConcurrentInboundEdgeStream.java:108)
	at com.hazelcast.jet.impl.execution.StoreSnapshotTasklet.stateMachineStep(StoreSnapshotTasklet.java:89)
	at com.hazelcast.jet.impl.execution.StoreSnapshotTasklet.call(StoreSnapshotTasklet.java:74)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:302)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.lambda$run$0(TaskletExecutionService.java:278)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:803)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:283)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Pipeline:
```
Pipeline.create()
        .drawFrom(Sources.mapJournal(mjName, START_FROM_OLDEST))
        .withTimestamps(t -> t.getValue().getTimestamp(), lag)
        .window(WindowDefinition.tumbling(windowSize)
        .groupingKey(t -> t.getKey())
        .aggregate(customAggregateToMap) 
        .drainTo(CustomVsinks.toClickhouse(...))
        .getPipeline(); 
```

**Comment by mtishchuk** [comment]
Duplicate of #1769

**Comment by viliam-durina** [comment]
You didn't share the `customAggregateToMap`, but it probably accumulates many items to a map and when that map was serialized to somewhere between 131048 and 131059 bytes, the error occurred.

**Comment by mtishchuk** [comment]
> You didn't share the `customAggregateToMap`, but it probably accumulates many items to a map and when that map was serialized to somewhere between 131048 and 131059 bytes, the error occurred.

Yeap, I calculate some per user statistic, so usually it's a wide map (much more then hundreds of byte). But restart was at night (when only a few users use service), maybe because of that this error occurred.
You warning me about possible GC pause issues with huge snapshots, I think it's ok for me to have some pauses.
