### ISSUE TITLE
com.hazelcast.jet.core.Job_StaleInstanceTest.when_join and com.hazelcast.jet.core.Job_StaleInstanceTest.when_getFuture

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1792]
_master_ (commit ced4b2f51f88b91f2b37e14d924570ee54a64e79)

Failed on Sonar: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/332/testReport/

Stacktrace for `com.hazelcast.jet.core.Job_StaleInstanceTest.when_join`:
```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.jet.core.JobNotFoundException> but was<java.lang.IllegalStateException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No members found in cluster
	at com.hazelcast.jet.impl.ClientJobProxy.lambda$masterAddress$7(ClientJobProxy.java:168)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.hazelcast.jet.impl.ClientJobProxy.masterAddress(ClientJobProxy.java:168)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.rejoinJob(AbstractJobProxy.java:296)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.accept(AbstractJobProxy.java:284)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.accept(AbstractJobProxy.java:270)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Stacktrace for `com.hazelcast.jet.core.Job_StaleInstanceTest.when_getFuture`:
```
java.lang.Exception: Unexpected exception, expected<com.hazelcast.jet.core.JobNotFoundException> but was<java.lang.IllegalStateException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No members found in cluster
	at com.hazelcast.jet.impl.ClientJobProxy.lambda$masterAddress$7(ClientJobProxy.java:168)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.hazelcast.jet.impl.ClientJobProxy.masterAddress(ClientJobProxy.java:168)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.rejoinJob(AbstractJobProxy.java:296)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.accept(AbstractJobProxy.java:284)
	at com.hazelcast.jet.impl.AbstractJobProxy$JoinJobCallback.accept(AbstractJobProxy.java:270)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Standard output for `com.hazelcast.jet.core.Job_StaleInstanceTest.when_join`:
```
Hiccups measured while running test 'when_join(com.hazelcast.jet.core.Job_StaleInstanceTest):'
13:08:25, accumulated pauses: 214 ms, max pause: 33 ms, pauses over 1000 ms: 0
```

Standard output for `com.hazelcast.jet.core.Job_StaleInstanceTest.when_getFuture`:
```
Hiccups measured while running test 'when_getFuture(com.hazelcast.jet.core.Job_StaleInstanceTest):'
13:08:25, accumulated pauses: 834 ms, max pause: 423 ms, pauses over 1000 ms: 0
```

**Comment by gurbuzali** [comment]
I've tried to reproduce the failure by retrying it a few times(500) via maven. From the stack-trace it looks like the failures are caused by the client code. There has been a some changes on imdg side around this `masterAddress` logic afaik, I suggest we close this issue and see if it reoccurs later.

**Comment by olukas** [comment]
Thanks Ali for investigation. Let's close it. I'll reopen it if it reoccurs.
