### ISSUE TITLE
A moderately complex job startup takes > 30 seconds

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast-jet#1805]
Hi Jet team,
I have recently observed performance regression on job initialization. While other jobs initialize and start within 1 second, some specific job (260 vertices, 504 edges) takes over 30 second to initialize. 

Strack trace during initialization:
````
"hz._hzInstance_1_integration-test.cached.thread-20@11036" prio=5 tid=0x53 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks hz._hzInstance_1_integration-test.cached.thread-18@10909
	 blocks hz._hzInstance_1_integration-test.cached.thread-10@10898
	 blocks hz._hzInstance_1_integration-test.cached.thread-9@10902
	  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	  at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	  at com.hazelcast.jet.impl.execution.init.VertexDef.isHigherPrioritySource(VertexDef.java:111)
	  at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:166)
	  at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:116)
	  at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$9(JobExecutionService.java:214)
	  at com.hazelcast.jet.impl.JobExecutionService$$Lambda$1094.1335892278.run(Unknown Source:-1)
	  at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:440)
	  at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:214)
	  - locked <0x4322> (a com.hazelcast.jet.impl.JobExecutionService)
	  at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:72)
	  at com.hazelcast.spi.Operation.call(Operation.java:170)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	  at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	  at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	  at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	  at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:262)
	  at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:246)
	  at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$3(MasterJobContext.java:223)
	  at com.hazelcast.jet.impl.MasterJobContext$$Lambda$1064.409133827.run(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$44(JobCoordinationService.java:971)
	  at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$680.751311561.call(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:980)
	  at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:970)
	  at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:182)
	  at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:892)
	  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:218)
	  at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$1042.1102484811.run(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$44(JobCoordinationService.java:971)
	  at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$680.751311561.call(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$45(JobCoordinationService.java:990)
	  at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$681.1972562950.call(Unknown Source:-1)
	  at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	  at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:748)
	  at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	  at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

````
Any suggestion how to proceed with root cause analysis?

Regards
LH

**Comment by cangencer** [comment]
@lukasherman could you give some details? which version? and for example, how many inbound / outbound edges on each vertex? Does this happen when job is first starting, or after a restart?

**Comment by lukasherman** [comment]
Jet 3.2
average 1-2 inbound, 1-2 outbound edges per vertex, but several have 9-12 inbound edges. It happens both on first start, and after cancel / start too. Restart I am not sure, we do not restart much, may test it,.
I may share digraph but only privately since it is a company IP.

**Comment by lukasherman** [comment]
Restart behavior is the same. Stack trace:
````
"hz._hzInstance_1_integration-test.cached.thread-8@10894" prio=5 tid=0x43 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	  at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	  at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	  at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	  at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	  at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	  at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	  at com.hazelcast.jet.impl.execution.init.VertexDef.isHigherPrioritySource(VertexDef.java:111)
	  at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:166)
	  at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:116)
	  at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$9(JobExecutionService.java:214)
	  at com.hazelcast.jet.impl.JobExecutionService$$Lambda$1105.1343642435.run(Unknown Source:-1)
	  at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:440)
	  at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:214)
	  - locked <0x50a0> (a com.hazelcast.jet.impl.JobExecutionService)
	  at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:72)
	  at com.hazelcast.spi.Operation.call(Operation.java:170)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	  at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	  at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:407)
	  at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:434)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:648)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:633)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:592)
	  at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:256)
	  at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61)
	  at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:262)
	  at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:246)
	  at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$3(MasterJobContext.java:223)
	  at com.hazelcast.jet.impl.MasterJobContext$$Lambda$1069.2136346075.run(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$44(JobCoordinationService.java:971)
	  at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$679.16624800.call(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:980)
	  at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:970)
	  at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:182)
	  at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:892)
	  at com.hazelcast.jet.impl.JobCoordinationService.restartJob(JobCoordinationService.java:736)
	  at com.hazelcast.jet.impl.MasterJobContext.lambda$null$18(MasterJobContext.java:641)
	  at com.hazelcast.jet.impl.MasterJobContext$$Lambda$3240.417172591.run(Unknown Source:-1)
	  at com.hazelcast.jet.impl.MasterJobContext.lambda$finalizeJob$21(MasterJobContext.java:678)
	  at com.hazelcast.jet.impl.MasterJobContext$$Lambda$3007.512029194.run(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$44(JobCoordinationService.java:971)
	  at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$679.16624800.call(Unknown Source:-1)
	  at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$45(JobCoordinationService.java:990)
	  at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$680.1535960084.call(Unknown Source:-1)
	  at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	  at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:748)
	  at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	  at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

````

**Comment by viliam-durina** [comment]
@lukasherman Can you check the PR #1806 if that fixes the issue for you?

**Comment by lukasherman** [comment]
Sure, will do.

**Comment by lukasherman** [comment]
@viliam-durina Verified, looks OK. 

timing after change:
````
19:44:57.177 [hz.charming_minsky.cached.thread-3] INFO  c.h.jet.impl.MasterJobContext - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Start executing job 
19:44:58.515 [hz.charming_minsky.cached.thread-3] INFO  c.h.jet.impl.JobExecutionService - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Execution plan initialized
````

compared to two other jobs: 
````
19:44:55.256 [hz.charming_minsky.cached.thread-13] INFO  c.h.jet.impl.MasterJobContext - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Start executing job 
19:44:57.119 [hz.charming_minsky.cached.thread-13] INFO  c.h.jet.impl.JobExecutionService - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Execution plan initialized

19:44:58.774 [hz.charming_minsky.cached.thread-3] INFO  c.h.jet.impl.MasterJobContext - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Start executing job 
19:44:59.468 [hz.charming_minsky.cached.thread-3] INFO  c.h.jet.impl.JobExecutionService - [127.0.0.1]:5701 [dev] [4.0-SNAPSHOT] Execution plan initialized
````
Great work!

**Comment by viliam-durina** [comment]
3.2.1 version with a fix was just released.
