### ISSUE TITLE
SourceBuilder_TopologyChangeTest.test_restartJob_nodeShutDown failure

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#1814]
http://jenkins.hazelcast.com/job/jet-oss-pr-builder/1621/testReport/junit/com.hazelcast.jet.pipeline/SourceBuilder_TopologyChangeTest/test_restartJob_nodeShutDown/

Stacktrace:
```
java.lang.AssertionError: No snapshot produced
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.jet.core.JetTestSupport.lambda$waitForFirstSnapshot$5(JetTestSupport.java:222)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1351)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1368)
	at com.hazelcast.jet.core.JetTestSupport.waitForFirstSnapshot(JetTestSupport.java:219)
	at com.hazelcast.jet.pipeline.SourceBuilder_TopologyChangeTest.testTopologyChange(SourceBuilder_TopologyChangeTest.java:114)
	at com.hazelcast.jet.pipeline.SourceBuilder_TopologyChangeTest.test_restartJob_nodeShutDown(SourceBuilder_TopologyChangeTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
13:12:02,459 DEBUG || - [MasterSnapshotContext] hz.musing_lalande.cached.thread-14 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Starting snapshot 0 for job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001, flags: terminal=no,export=no, writing to: null
Will save 749 to snapshot
13:12:02,543 DEBUG || - [AsyncSnapshotWriterImpl] hz.musing_lalande.jet.cooperative.thread-0 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Stats for src: keys=1, chunks=1, bytes=170
13:12:02,740 DEBUG || - [AsyncSnapshotWriterImpl] hz.musing_lalande.jet.cooperative.thread-1 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Stats for sliding-window-prepare: keys=0, chunks=0, bytes=0
```

We see in the output that snapshot started only on one of the members. The job contains a non-distributed source so it creates a real processor on 1 member and a processor that completes immediately on the other. Also the `sliding-window-prepare` on that member completes immediately. The phase 1 of the snapshot got stuck at `sliding-window` because it was waiting for the barrier from the other member.

**Comment by viliam-durina** [comment]
I've run the test 400 times locally on current master (39c5e636145d2f7a02676a521f4638d18b5a8c09), without a single failure. I've analyzed the code in many places and can't find a possible cause. I've also inserted sleeps at various places. Also it probably didn't happen again in the PR builder. Even though the explanation in the original report that it's related to the source completing on one member and not on the other seems plausible. From the logs it looks like the snapshot phase-1 wasn't started on one of the members.

Here's the full log:
```
13:12:00,596  INFO || - [LifecycleService] test_restartJob_nodeShutDown - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
13:12:00,597 DEBUG || - [Planner] test_restartJob_nodeShutDown - Watermarks in the pipeline will be throttled to 100
13:12:00,622  INFO || - [PartitionStateManager] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Initializing cluster partition table arrangement...
13:12:00,626  INFO || - [HealthMonitor] hz.xenodochial_lalande.HealthMonitor - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=136.9G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=251.5M, heap.memory.free=749.5M, heap.memory.total=1001.0M, heap.memory.max=1001.0M, heap.memory.used/total=25.12%, heap.memory.used/max=25.12%, minor.gc.count=10, minor.gc.time=624ms, major.gc.count=2, major.gc.time=711ms, load.process=0.00%, load.system=85.71%, load.systemAverage=182.25, thread.count=486, thread.peakCount=796, cluster.timeDiff=-3, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=1, executor.q.priorityOperation.size=0, operations.completed.count=13, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=7, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
13:12:00,656  INFO || - [JobCoordinationService] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Starting job 0399-3e03-d580-0001 based on submit request
13:12:00,714  INFO || - [MasterJobContext] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Didn't find any snapshot to restore for job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001
13:12:00,714  INFO || - [MasterJobContext] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Start executing job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001, execution graph in DOT format:
digraph DAG {
	"src" [localParallelism=1];
	"sliding-window-prepare" [localParallelism=72];
	"sliding-window" [localParallelism=1];
	"listSink(result-fb3b5e3c-0f27-4656-9e4b-8632dc9fde75)" [localParallelism=1];
	"src" -> "sliding-window-prepare" [queueSize=1024];
	subgraph cluster_0 {
		"sliding-window-prepare" -> "sliding-window" [label="distributed-partitioned", queueSize=1024];
	}
	"sliding-window" -> "listSink(result-fb3b5e3c-0f27-4656-9e4b-8632dc9fde75)" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
13:12:00,714 DEBUG || - [MasterJobContext] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Building execution plan for job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001
13:12:00,716 DEBUG || - [MasterJobContext] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Built execution plans for job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001
13:12:00,717 DEBUG || - [InitExecutionOperation] hz.xenodochial_lalande.generic-operation.thread-11 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Initializing execution plan for job 0399-3e03-d580-0001, execution 0399-3e03-d581-0001 from [127.0.0.1]:5701
13:12:00,718 DEBUG || - [InitExecutionOperation] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Initializing execution plan for job 0399-3e03-d580-0001, execution 0399-3e03-d581-0001 from [127.0.0.1]:5701
13:12:00,887  INFO || - [JobExecutionService] hz.xenodochial_lalande.generic-operation.thread-11 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Execution plan for jobId=0399-3e03-d580-0001, jobName='0399-3e03-d580-0001', executionId=0399-3e03-d581-0001 initialized
13:12:01,117 DEBUG || - [MasterJobContext] hz.musing_lalande.cached.thread-9 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Not scaling up job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001: not running or already running on all members
13:12:01,130  INFO || - [JobExecutionService] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Execution plan for jobId=0399-3e03-d580-0001, jobName='0399-3e03-d580-0001', executionId=0399-3e03-d581-0001 initialized
13:12:01,143 DEBUG || - [MasterJobContext] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Init of job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001 was successful
13:12:01,143 DEBUG || - [MasterJobContext] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Executing job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001
13:12:01,143  INFO || - [JobExecutionService] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Start execution of job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001 from coordinator [127.0.0.1]:5701
13:12:01,144  INFO || - [JobExecutionService] hz.xenodochial_lalande.generic-operation.thread-12 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Start execution of job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001 from coordinator [127.0.0.1]:5701
13:12:01,576 DEBUG || - [JobCoordinationService] hz.musing_lalande.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001 snapshot is scheduled in 500ms
13:12:02,459 DEBUG || - [MasterSnapshotContext] hz.musing_lalande.cached.thread-14 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Starting snapshot 0 for job '0399-3e03-d580-0001', execution 0399-3e03-d581-0001, flags: terminal=no,export=no, writing to: null
Will save 749 to snapshot
13:12:02,543 DEBUG || - [AsyncSnapshotWriterImpl] hz.musing_lalande.jet.cooperative.thread-0 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Stats for src: keys=1, chunks=1, bytes=170
13:12:02,740 DEBUG || - [AsyncSnapshotWriterImpl] hz.musing_lalande.jet.cooperative.thread-1 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Stats for sliding-window-prepare: keys=0, chunks=0, bytes=0
13:12:03,487  INFO || - [sliding-window#0] hz.xenodochial_lalande.jet.cooperative.thread-5 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Output to ordinal 0: Watermark{ts=00:00:00.700}
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: WindowResult{start=00:00:00.000, end=00:00:00.100, value='100', isEarly=false} (eventTime=00:00:00.099)
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: WindowResult{start=00:00:00.100, end=00:00:00.200, value='100', isEarly=false} (eventTime=00:00:00.199)
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: WindowResult{start=00:00:00.200, end=00:00:00.300, value='100', isEarly=false} (eventTime=00:00:00.299)
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: WindowResult{start=00:00:00.300, end=00:00:00.400, value='100', isEarly=false} (eventTime=00:00:00.399)
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: WindowResult{start=00:00:00.400, end=00:00:00.500, value='100', isEarly=false} (eventTime=00:00:00.499)
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: WindowResult{start=00:00:00.500, end=00:00:00.600, value='100', isEarly=false} (eventTime=00:00:00.599)
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: WindowResult{start=00:00:00.600, end=00:00:00.700, value='100', isEarly=false} (eventTime=00:00:00.699)
13:12:03,554  INFO || - [sliding-window#1] hz.musing_lalande.jet.cooperative.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Output to ordinal 0: Watermark{ts=00:00:00.700}
13:12:04,992 DEBUG || - [JobRepository] hz.musing_lalande.cached.thread-8 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Job cleanup took 5ms
13:12:09,978 DEBUG || - [JobRepository] hz.musing_lalande.cached.thread-5 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Job cleanup took 1ms
```

Closing the issue for now, should be reopened if it occurs again.
