### ISSUE TITLE
IOUtilTest.test_zipAndUnzipNestedFolder_then_contentsShouldBeSame

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-jet#1851]
failed on _master_ PR builder

Failed on http://jenkins.hazelcast.com/job/jet-oss-pr-builder/1846/testReport/junit/com.hazelcast.jet.impl.util/IOUtilTest/test_zipAndUnzipNestedFolder_then_contentsShouldBeSame/

Stacktrace:
```
java.lang.AssertionError: expected:<7> but was:<6>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.test.HazelcastTestSupport.assertCollection(HazelcastTestSupport.java:180)
	at com.hazelcast.jet.impl.util.IOUtilTest.test(IOUtilTest.java:71)
	at com.hazelcast.jet.impl.util.IOUtilTest.test_zipAndUnzipNestedFolder_then_contentsShouldBeSame(IOUtilTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Finished Running Test: test_zipAndUnzipNestedFoldersWithAnEmptySubFolder_then_contentsShouldBeSame in 0.411 seconds.
BuildInfo right after test_zipAndUnzipNestedFolder_then_contentsShouldBeSame(com.hazelcast.jet.impl.util.IOUtilTest): BuildInfo{version='4.0-SNAPSHOT', build='20200110', buildNumber=20200110, revision=bbf6a5b, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='4.0-SNAPSHOT', build='20200110', revision='ee03c4f'}}
Hiccups measured while running test 'test_zipAndUnzipNestedFolder_then_contentsShouldBeSame(com.hazelcast.jet.impl.util.IOUtilTest):'
13:00:25, accumulated pauses: 807 ms, max pause: 383 ms, pauses over 1000 ms: 0

```

**Comment by eminn** [comment]
I couldn't be able to reproduce this on my local

**Comment by gurbuzali** [comment]
failed again in a PR builder
http://jenkins.hazelcast.com/job/jet-oss-pr-builder/1884/testReport/junit/com.hazelcast.jet.impl.util/IOUtilTest/test_zipAndUnzipNestedFolder_then_contentsShouldBeSame/
unfortunately it was before we merge the PR which add more logging in case of a failure
