### ISSUE TITLE
com.hazelcast.jet.core.metrics.JobLifecycleMetricsTest.jobRestarted

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1854]
_master_ (commit 0a648ff623e09346d966d3fac6cc44edfbc3711d)

Failed on Sonar nightly: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/366/testReport/com.hazelcast.jet.core.metrics/JobLifecycleMetricsTest/jobRestarted/

Stacktrace:
```
com.hazelcast.core.HazelcastException: javax.management.AttributeNotFoundException: jobs.submitted
	at com.hazelcast.internal.util.ExceptionUtil.lambda$static$0(ExceptionUtil.java:39)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:122)
	at com.hazelcast.internal.util.ExceptionUtil.peel(ExceptionUtil.java:67)
	at com.hazelcast.internal.util.ExceptionUtil.rethrow(ExceptionUtil.java:127)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1358)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.jet.core.metrics.JobLifecycleMetricsTest.jobRestarted(JobLifecycleMetricsTest.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.management.AttributeNotFoundException: jobs.submitted
	at com.hazelcast.internal.metrics.jmx.MetricsMBean.getAttribute(MetricsMBean.java:64)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at com.hazelcast.jet.core.metrics.JobLifecycleMetricsTest.assertMBeans(JobLifecycleMetricsTest.java:231)
	at com.hazelcast.jet.core.metrics.JobLifecycleMetricsTest.assertJobStats(JobLifecycleMetricsTest.java:208)
	at com.hazelcast.jet.core.metrics.JobLifecycleMetricsTest.lambda$jobRestarted$9(JobLifecycleMetricsTest.java:154)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	... 28 more
```

Standard output:
```
Hiccups measured while running test 'jobRestarted(com.hazelcast.jet.core.metrics.JobLifecycleMetricsTest):'
13:06:00, accumulated pauses: 96 ms, max pause: 45 ms, pauses over 1000 ms: 0
13:06:05, accumulated pauses: 226 ms, max pause: 18 ms, pauses over 1000 ms: 0
```

**Comment by jbartok** [comment]
I have investigated and fixed this issue. It's a problem with the tests `JobLifecycleMetricsTest`. The fix is currently only in [this PR's branch](https://github.com/hazelcast/hazelcast-jet/pull/1729). It will hopefully be merged in today, if not, I can port the fix to `master` too.

**Comment by jbartok** [comment]
Fixed by merging the above mentioned branch into `master`.
