### ISSUE TITLE
Python service fails to delete the runtime directory

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-jet#1894]
stack-trace:
```
com.hazelcast.core.HazelcastException: Failed to delete /var/folders/y7/kljm0_sd5j1bbfmc2p5gxmp80000gn/T/jet-objective_bohr-03d1-a89b-61c0-0001-_java_workspace_test_python1378860225143924489
	at com.hazelcast.internal.nio.IOUtil.delete(IOUtil.java:460)
	at com.hazelcast.jet.python.PythonServiceContext.destroy(PythonServiceContext.java:118)
	at com.hazelcast.function.ConsumerEx.accept(ConsumerEx.java:46)
	at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.close(ProcessorSupplierWithService.java:71)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:196)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$f4fa789d$1(JobExecutionService.java:346)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:408)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:345)
	at com.hazelcast.jet.impl.operation.CompleteExecutionOperation.run(CompleteExecutionOperation.java:89)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:590)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:575)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeCompleteExecution$12(MasterJobContext.java:576)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$42(JobCoordinationService.java:978)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$43(JobCoordinationService.java:997)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.nio.file.AccessDeniedException: /var/folders/y7/kljm0_sd5j1bbfmc2p5gxmp80000gn/T/jet-objective_bohr-03d1-a89b-61c0-0001-_java_workspace_test_python1378860225143924489/jet_to_python_grpc_server.py
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.hazelcast.internal.nio.IOUtil$3.visitFile(IOUtil.java:449)
	at com.hazelcast.internal.nio.IOUtil$3.visitFile(IOUtil.java:446)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.hazelcast.internal.nio.IOUtil.delete(IOUtil.java:446)
```

**Comment by gurbuzali** [comment]
`cleanup.sh` also cannot remove the files created in `init.sh` due to the same reason I guess
