### ISSUE TITLE
Files sink with exactly-once is not able to work with more nodes on one machine

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1935]
When exactly-once is configured for job which runs pipeline with `files` sink and is running on 2 or more members on the same machine then following Excaption is thrown after first snapshot:
```
WARNING: [192.168.0.102]:5701 [jet] [4.0-SNAPSHOT] Exception in ProcessorTasklet{filesSink(/tmp/filesink)#0}
java.nio.file.NoSuchFileException: /tmp/filesink/0-0.tmp -> /tmp/filesink/0-0
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:396)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at com.hazelcast.jet.impl.connector.WriteFileP$FileWithTransaction.commit(WriteFileP.java:365)
	at com.hazelcast.jet.impl.processor.TwoPhaseSnapshotCommitUtility$LoggingNonThrowingResource.commit(TwoPhaseSnapshotCommitUtility.java:406)
	at com.hazelcast.jet.impl.processor.UnboundedTransactionsProcessorUtility.commitPendingTransactions(UnboundedTransactionsProcessorUtility.java:173)
	at com.hazelcast.jet.impl.processor.UnboundedTransactionsProcessorUtility.snapshotCommitFinish(UnboundedTransactionsProcessorUtility.java:166)
	at com.hazelcast.jet.impl.connector.WriteFileP.snapshotCommitFinish(WriteFileP.java:182)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.snapshotCommitFinish(ProcessorWrapper.java:128)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:335)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	at java.lang.Thread.run(Thread.java:748)
```
Only file `1-0` is created in `/tmp/filesink` and this file includes items emitted only by one of sink processors. Also before snapshot should be created only file `1-0.tmp` occurs in `/tmp/filesink`

This does not happen in exactly once is disabled.

**How to reproduce:**
Run job with pipeline like this on cluster with 2 members on the same machine (e.g. locally):
```
Pipeline p = Pipeline.create();
StreamSource<Long> source = SourceBuilder
        .stream("srcForFileSink", procCtx -> new long[1])
        .<Long>fillBufferFn((ctx, buf) -> {
            buf.add(ctx[0]++);
            Thread.sleep(100);
        })
        .createSnapshotFn(ctx -> ctx[0])
        .restoreSnapshotFn((ctx, state) -> ctx[0] = state.get(0))
        .build();
Sink<Object> sink = Sinks.files("/tmp/filesink");
p.readFrom(source)
        .withoutTimestamps()
        .groupingKey(identity())
        .filterUsingService(sharedService(ctx -> null), (s, k, v) -> true)
        .writeTo(sink);
```

**Comment by viliam-durina** [comment]
All processors try to delete all .tmp files in the directory. However when P1 got to do it, P2 might already started creating files which caused that P1 deleted working files of P2. On Windows, the delete failed, on Linux the processor failed later when it was trying to commit (rename) the file, with the exception above.
