### ISSUE TITLE
com.hazelcast.jet.impl.connector.StreamJmsPTest.com.hazelcast.jet.impl.connector.StreamJmsPTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1954]
_master_ (commit a9c37e8e8697fe5478f5d516f899c06a9b9135d0)

Failed on Sonar build: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/394/testReport/junit/com.hazelcast.jet.impl.connector/StreamJmsPTest/com_hazelcast_jet_impl_connector_StreamJmsPTest/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at java.lang.Object.wait(Native Method)
	at org.apache.activemq.transport.failover.FailoverTransport.oneway(FailoverTransport.java:623)
	at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:68)
	at org.apache.activemq.transport.ResponseCorrelator.asyncRequest(ResponseCorrelator.java:81)
	at org.apache.activemq.transport.ResponseCorrelator.request(ResponseCorrelator.java:86)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1392)
	at org.apache.activemq.ActiveMQConnection.ensureConnectionInfoSent(ActiveMQConnection.java:1486)
	at org.apache.activemq.ActiveMQConnection.createSession(ActiveMQConnection.java:329)
	at org.apache.activemq.junit.EmbeddedActiveMQBroker$InternalClient.start(EmbeddedActiveMQBroker.java:711)
	at org.apache.activemq.junit.EmbeddedActiveMQBroker.start(EmbeddedActiveMQBroker.java:131)
	at org.apache.activemq.junit.EmbeddedActiveMQBroker.before(EmbeddedActiveMQBroker.java:170)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
13:14:32,045  WARN || - [BrokerService] Time-limited test - Memory Usage for the Broker (1024mb) is more than the maximum available for the JVM: 985 mb - resetting to 70% of maximum available: 689 mb
13:14:32,047  INFO || - [BrokerService] Time-limited test - Using Persistence Adapter: MemoryPersistenceAdapter
13:14:32,051  INFO || - [BrokerService] Time-limited test - Apache ActiveMQ 5.15.11 (embedded-broker, ID:7c02e16ec446-41813-1581340430454-0:2) is starting
13:14:32,052  INFO || - [BrokerService] Time-limited test - Apache ActiveMQ 5.15.11 (embedded-broker, ID:7c02e16ec446-41813-1581340430454-0:2) started
13:14:32,052  INFO || - [BrokerService] Time-limited test - For help or more information please see: http://activemq.apache.org
13:14:37,171  WARN || - [FailoverTransport] ActiveMQ Task-1 - Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
13:14:42,248  WARN || - [FailoverTransport] ActiveMQ Task-3 - Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
13:14:42,251  WARN || - [FailoverTransport] ActiveMQ Task-3 - Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
13:14:42,255  WARN || - [FailoverTransport] ActiveMQ Task-2 - Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
13:14:42,255  WARN || - [FailoverTransport] ActiveMQ Task-2 - Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
13:14:42,255  WARN || - [FailoverTransport] ActiveMQ Task-2 - Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
...
```

**Comment by olukas** [comment]
Closing. This happened only once and we are not able to reproduce it. In case it will fail again I will reopen it.

**Comment by olukas** [comment]
Reopen. Failed again - http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/404/testReport/junit/com.hazelcast.jet.impl.connector/StreamJmsPTest/com_hazelcast_jet_impl_connector_StreamJmsPTest/
