### ISSUE TITLE
Exception using Map.Entry.class in Job

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2106]
On Jet 4.0, this code 

```
Pipeline pipeline = Pipeline.create();
            
pipeline.readFrom(Sources.map("neil"))
.map(Map.Entry::getValue)
.writeTo(Sinks.logger());
            
JobConfig jobConfig=new JobConfig();
            
Job job = this.jetInstance.newJobIfAbsent(pipeline, jobConfig);
```
triggers this error
```
com.hazelcast.jet.JetException: Class containing the lambda probably missing from class path, did you add it using JobConfig.addClass()?: com.hazelcast.nio.serialization.HazelcastSerializationException: Error deserializing vertex 'map': com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.core.ProcessorMetaSupplier$1.val$addressToSupplier of type com.hazelcast.function.FunctionEx in instance of com.hazelcast.jet.core.ProcessorMetaSupplier$1
```

Adding these lines
```
jobConfig.addClass(java.util.Map.class);
jobConfig.addClass(java.util.Map.Entry.class);
```
triggers this error
```
 java.lang.NullPointerException: null
	at com.hazelcast.jet.config.ResourceConfig.<init>(ResourceConfig.java:66) ~[hazelcast-jet-4.0.jar!/:4.0]
	at com.hazelcast.jet.config.JobConfig.addClass(JobConfig.java:243) ~[hazelcast-jet-4.0.jar!/:4.0]
```

**Comment by neilstevenson** [comment]
You need to add the parent class, but this is not exactly obvious from the exception!

**Comment by mtopolnik** [comment]
You didn't show all the code so I ran this:

```java
public class JetTest {
    public static void main(String[] args) {
        Pipeline pipeline = Pipeline.create();

        pipeline.readFrom(Sources.map("neil"))
                .map(Map.Entry::getValue)
                .writeTo(Sinks.logger());

        JetInstance jetInstance = Jet.bootstrappedInstance();
        JobConfig jobConfig = new JobConfig();
        jetInstance.newJobIfAbsent(pipeline, jobConfig);
    }
}```

It doesn't reproduce your error which leads me to conclude that the problem is not in using `Map.Entry`. I wouldn't expect it to be a problem, either, since it's a JDK class.

**Comment by mtopolnik** [comment]
It is always an error to add a JDK class to the job classpath, but the exception you get in that case doesn't point that out. We should fix that aspect.

**Comment by neilstevenson** [comment]
Here's a reproducer

```
package neil.demo;

import java.util.Map.Entry;

import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.config.YamlClientConfigBuilder;
import com.hazelcast.jet.Jet;
import com.hazelcast.jet.JetInstance;
import com.hazelcast.jet.config.JobConfig;
import com.hazelcast.jet.pipeline.Pipeline;
import com.hazelcast.jet.pipeline.Sinks;
import com.hazelcast.jet.pipeline.Sources;

public class Main {
    
    public static void main(String[] args) throws Exception {
        ClientConfig clientConfig
            = new YamlClientConfigBuilder().build();

        JetInstance jetInstance = Jet.newJetClient(clientConfig);

        Pipeline pipeline = Pipeline.create();
        
        pipeline.readFrom(Sources.map("neil"))
        .map(Entry::getValue)
        .writeTo(Sinks.logger());
                    
        JobConfig jobConfig=new JobConfig();
        //jobConfig.addClass(Main.class);
        //jobConfig.addClass(Entry.class);
                    
        jetInstance.newJobIfAbsent(pipeline, jobConfig);
        
        jetInstance.shutdown();
    }
}
```

As is, it gives the error
```
Exception in thread "main" com.hazelcast.jet.JetException: Class containing the lambda probably missing from class path, did you add it using JobConfig.addClass()?: com.hazelcast.nio.serialization.HazelcastSerializationException: Error deserializing vertex 'map': com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.core.ProcessorMetaSupplier$1.val$addressToSupplier of type com.hazelcast.function.FunctionEx in instance of com.hazelcast.jet.core.ProcessorMetaSupplier$1
```

If you uncomment `jobConfig.addClass(Main.class)` it works. 
How this differs from @mtopolnik 's version is it's not using `Jet.bootstrappedInstance();`, it's using a directly created Jet instance.

If you uncomment `jobConfig.addClass(Entry.class);` you get the NPE listed on https://github.com/hazelcast/hazelcast-jet/issues/2107

**Comment by mtopolnik** [comment]
Here's a narrower reproducer:

```java
import com.hazelcast.jet.Jet;
import com.hazelcast.jet.pipeline.Pipeline;
import com.hazelcast.jet.pipeline.Sinks;
import com.hazelcast.jet.pipeline.test.TestSources;

public class JetTest {
    public static void main(String[] args) {
        var p = Pipeline.create();
        p.readFrom(TestSources.items(1))
                .map(Integer::longValue)
                .writeTo(Sinks.logger());
        try {
            Jet.newJetClient().newJob(p);
        } finally {
            Jet.shutdownAll();
        }
    }
}
```
If we use `Jet.boostrappedInstance()` instead, there is no failure.

**Comment by mtopolnik** [comment]
This is actually expected behavior, the error message says it: "Class containing the lambda probably missing from classpath". The class in question is `Main` and not `Map.Entry`.

This problem is avoided when you follow the recommendation to use `Jet. bootstrappedInstance()`.
