### ISSUE TITLE
Exception with HazelcastJsonValue

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2109]
This code, on Jet 4.0:

```
package neil.demo;

import java.util.Map.Entry;

import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.config.YamlClientConfigBuilder;
import com.hazelcast.core.HazelcastJsonValue;
import com.hazelcast.jet.Jet;
import com.hazelcast.jet.JetInstance;
import com.hazelcast.jet.config.JobConfig;
import com.hazelcast.jet.datamodel.Tuple2;
import com.hazelcast.jet.pipeline.Pipeline;
import com.hazelcast.jet.pipeline.Sinks;
import com.hazelcast.jet.pipeline.Sources;

public class Main {
    
    public static void main(String[] args) throws Exception {
        ClientConfig clientConfig
            = new YamlClientConfigBuilder().build();

        JetInstance jetInstance = Jet.newJetClient(clientConfig);

        Pipeline pipeline = Pipeline.create();
        
        pipeline.readFrom(Sources.<String, HazelcastJsonValue>map("neil"))
        .map(Entry::getValue)
        .map(value -> {
            String[] tokens = value.toString().split(",");
            return Tuple2.tuple2("fields", String.valueOf(tokens.length));
        })
        .writeTo(Sinks.logger());  
        
        JobConfig jobConfig=new JobConfig();
        jobConfig.addClass(Main.class);
                    
        jetInstance.newJobIfAbsent(pipeline, jobConfig);
        
        jetInstance.shutdown();
    }
}
```
produces this exception
```
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Error deserializing vertex 'fused(map, map-2)': com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.IOException: unexpected exception type
	at com.hazelcast.jet.core.Vertex.readData(Vertex.java:219)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:268)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:567)
	at com.hazelcast.jet.core.DAG.readData(DAG.java:486)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.readIdentifiedDataSerializable(EnterpriseDataSerializableSerializer.java:161)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.doRead(EnterpriseDataSerializableSerializer.java:130)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:124)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.read(EnterpriseDataSerializableSerializer.java:52)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:65)
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeDag(JobCoordinationService.java:815)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:203)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$42(JobCoordinationService.java:978)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$43(JobCoordinationService.java:997)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.IOException: unexpected exception type
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:103)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:274)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:567)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.read(CustomClassLoadedObject.java:56)
	at com.hazelcast.jet.core.Vertex.readData(Vertex.java:217)
	... 26 more
Caused by: java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1626)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1256)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2151)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.util.ArrayList.readObject(ArrayList.java:928)
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2271)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2048)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2048)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2048)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2048)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1634)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2410)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2304)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2142)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:110)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:91)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:268)
	... 29 more
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.reflect.InvocationTargetException, Message: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:237)
	at jdk.internal.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1250)
	... 75 more
```

Possibly related to https://github.com/hazelcast/hazelcast-jet/issues/2106

Note if you remove the generics, so that the map read line becomes `pipeline.readFrom(Sources.map("neil"))` it works fine.

**Comment by mtopolnik** [comment]
If you use `Jet.bootstrappedInstance()` and submit via `jet submit`, does it happen then?

**Comment by mtopolnik** [comment]
I can't reproduce this problem.

**Comment by neilstevenson** [comment]
I need to set config from Java, so if I change to `Jet.bootstrappedInstance()` as below I get the same error
```
ClientConfig clientConfig = new YamlClientConfigBuilder().build();
Jet.newJetClient(clientConfig);
JetInstance jetInstance = Jet.bootstrappedInstance();
```

**Comment by neilstevenson** [comment]
My dependency
```
	<dependencies>
		<dependency>
			<groupId>com.hazelcast.jet</groupId>
			<artifactId>hazelcast-jet</artifactId>
			<version>4.0</version>
		</dependency>
	</dependencies>
```

Try
```
    public static void main(String[] args) throws Exception {
        JetInstance server = Jet.newJetInstance();
        JetInstance client = Jet.newJetClient();

        Pipeline pipeline = Pipeline.create();
        
        // HazelcastJsonValue breaks it
        pipeline.readFrom(Sources.<String, HazelcastJsonValue>map("neil"))
        .map(Entry::getValue)
        .map(value -> {
            String[] tokens = value.toString().split(",");
            return Tuple2.tuple2("fields", String.valueOf(tokens.length));
        })
        .writeTo(Sinks.logger());  
        
        JobConfig jobConfig=new JobConfig();
        jobConfig.addClass(Main.class);
                    
        client.newJobIfAbsent(pipeline, jobConfig);

        client.shutdown();
        server.shutdown();
    }
```
which gives me
```
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Error deserializing vertex 'fused(map, map-2)': com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.IOException: unexpected exception type
	at com.hazelcast.jet.core.Vertex.readData(Vertex.java:219)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
```

**Comment by neilstevenson** [comment]
Simpler reproducer
```
    public static void main(String[] args) throws Exception {
        JetInstance server = Jet.bootstrappedInstance();

        Pipeline pipeline = Pipeline.create();
        
        // HazelcastJsonValue breaks it
        pipeline.readFrom(Sources.<String, HazelcastJsonValue>map("neil"))
        .map(Entry::getValue)
        .map(value -> {
            String[] tokens = value.toString().split(",");
            return Tuple2.tuple2("fields", String.valueOf(tokens.length));
        })
        .writeTo(Sinks.logger());  
        
        server.newJob(pipeline);

        server.shutdown();
    }
```

Just a server.

**Comment by mtopolnik** [comment]
All the examples work for me.

**Comment by neilstevenson** [comment]
@mtopolnik  Seems to be an IDE issue...with Eclipse. Works from the command line. So, user error
