### ISSUE TITLE
com.hazelcast.jet.impl.connector.JmsIntegration_NonSharedClusterTest.com.hazelcast.jet.impl.connector.JmsIntegration_NonSharedClusterTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2110]
_master_  (commit b5a714f5e76ed142a313959dacfee786e75249a8)

Failed on Zulu JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-zulu-jdk8/187/testReport/junit/com.hazelcast.jet.impl.connector/JmsIntegration_NonSharedClusterTest/com_hazelcast_jet_impl_connector_JmsIntegration_NonSharedClusterTest/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at java.lang.Object.wait(Native Method)
	at org.apache.activemq.transport.failover.FailoverTransport.oneway(FailoverTransport.java:623)
	at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:68)
	at org.apache.activemq.transport.ResponseCorrelator.asyncRequest(ResponseCorrelator.java:81)
	at org.apache.activemq.transport.ResponseCorrelator.request(ResponseCorrelator.java:86)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1392)
	at org.apache.activemq.ActiveMQConnection.ensureConnectionInfoSent(ActiveMQConnection.java:1486)
	at org.apache.activemq.ActiveMQConnection.createSession(ActiveMQConnection.java:329)
	at org.apache.activemq.junit.EmbeddedActiveMQBroker$InternalClient.start(EmbeddedActiveMQBroker.java:711)
	at org.apache.activemq.junit.EmbeddedActiveMQBroker.start(EmbeddedActiveMQBroker.java:131)
	at org.apache.activemq.junit.EmbeddedActiveMQBroker.before(EmbeddedActiveMQBroker.java:170)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
 INFO | Starting embedded ActiveMQ broker: embedded-broker
 WARN | Memory Usage for the Broker (1024mb) is more than the maximum available for the JVM: 1011 mb - resetting to 70% of maximum available: 708 mb
 INFO | Using Persistence Adapter: MemoryPersistenceAdapter
 INFO | Apache ActiveMQ 5.15.11 (embedded-broker, ID:64e2684f4972-38725-1585360487282-0:2) is starting
 INFO | Apache ActiveMQ 5.15.11 (embedded-broker, ID:64e2684f4972-38725-1585360487282-0:2) started
 INFO | For help or more information please see: http://activemq.apache.org
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 10 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 20 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 20 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 20 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 20 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 20 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 20 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 20 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 30 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 30 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 30 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 30 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 30 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 30 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 30 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 40 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 40 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 40 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 40 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 40 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 40 attempt(s) continuing to retry.
 WARN | Failed to connect to [vm://embedded-broker?create=false] after: 40 attempt(s) continuing to retry.
```

**Comment by viliam-durina** [comment]
Same root cause as in #1954
