### ISSUE TITLE
AuthenticationException with default ClientConfig against default `jet-start`

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#2111]
I started a Jet instance with `jet-start` and tried to use this code on it:

```java
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.config.YamlClientConfigBuilder;
import com.hazelcast.jet.Jet;
import com.hazelcast.jet.config.JobConfig;
import com.hazelcast.jet.pipeline.Pipeline;
import com.hazelcast.jet.pipeline.Sinks;
import com.hazelcast.jet.pipeline.test.TestSources;

public class JetTest {
    public static void main(String[] args) {
        Pipeline p = Pipeline.create();
        p.readFrom(TestSources.items(1))
         .writeTo(Sinks.logger());
        JobConfig jobConfig = new JobConfig();
        jobConfig.addClass(JetTest.class);
        ClientConfig clientConfig = new YamlClientConfigBuilder().build();
        try {
            Jet.newJetClient(clientConfig).newJobIfAbsent(p, jobConfig).join();
        } finally {
            Jet.shutdownAll();
        }
    }
}
```

It fails with

```
08:21:13.717 [ WARN] [c.h.c.i.c.n.ClientConnection] [4.0] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:62643->/127.0.0.1:5701}, remoteEndpoint=null, lastReadTime=2020-03-30 08:21:13.690, lastWriteTime=2020-03-30 08:21:13.689, closedTime=2020-03-30 08:21:13.692, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Invalid credentials!
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.authenticateOnCluster(ClientConnectionManagerImpl.java:793)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.getOrConnect(ClientConnectionManagerImpl.java:581)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connect(ClientConnectionManagerImpl.java:423)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.doConnectToCandidateCluster(ClientConnectionManagerImpl.java:451)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.doConnectToCluster(ClientConnectionManagerImpl.java:385)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.connectToCluster(ClientConnectionManagerImpl.java:346)
	at com.hazelcast.client.impl.connection.nio.ClientConnectionManagerImpl.start(ClientConnectionManagerImpl.java:296)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:365)
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
	at com.hazelcast.jet.Jet.newJetClient(Jet.java:193)
	at org.mtopol.JetTest.main(JetTest.java:27)

```

**Comment by cangencer** [comment]
Default group name for Jet node is `jet`, you should set the group name. The exception message is improved in https://github.com/hazelcast/hazelcast/pull/16765
