### ISSUE TITLE
com.hazelcast.jet.impl.JobSummaryTest.when_job_failed

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2193]
http://jenkins.hazelcast.com/job/jet-oss-pr-builder/2682/testReport/junit/com.hazelcast.jet.impl/JobSummaryTest/when_job_failed/

Stacktrace:
```
Error Message
expected:<...t.jet.JetException: [2 of 5 tasklets failed to initialize. One of the failures is attached as the cause and its summary is java.lang.UnsupportedOperationException: Cannot subscribe to event journal because it is either not configured or disabled for map 'invalid']> but was:<...t.jet.JetException: [ 2 of 5 tasklets failed to initialize. One of the failures is attached as the cause and its summary is java.lang.UnsupportedOperationException: Cannot subscribe to event journal because it is either not configured or disabled for map 'invalid'
 at com.hazelcast.jet.impl.execution.TaskletExecutionService.awaitAll(TaskletExecutionService.java:221)
 at com.hazelcast.jet.impl.execution.TaskletExecutionService.submitCooperativeTasklets(TaskletExecutionService.java:189)
 at com.hazelcast.jet.impl.execution.TaskletExecutionService.beginExecute(TaskletExecutionService.java:148)
 at com.hazelcast.jet.impl.execution.ExecutionContext.beginExecution(ExecutionContext.java:167)
 at com.hazelcast.jet.impl.JobExecutionService.beginExecution(JobExecutionService.java:377)
 at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:46)
 at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:53)
 at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
 at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
 at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
 at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:433)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136)
 at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)```

**Comment by cangencer** [comment]
I'm not 100% sure if this is related to #2183 @frant-hartm

**Comment by cangencer** [comment]
closing this since it's related to #2183
