### ISSUE TITLE
UnsupportedOperationException: Missing implementation in class com.hazelcast.jet.impl.connector.WriteJmsP

### ISSUE THREAD

**Issue by tplasko** [hazelcast/hazelcast-jet#2292]
Hi,

Running a simple pipeline with a JMS sink, inspired from 

https://github.com/hazelcast/hazelcast-jet/blob/master/examples/jms/src/main/java/com/hazelcast/jet/examples/jms/JmsTopicSample.java

throws the following exception:

java.lang.UnsupportedOperationException: Missing implementation in class com.hazelcast.jet.impl.connector.WriteJmsP
	at com.hazelcast.jet.core.Processor.tryProcessWatermark(Processor.java:211) ~[hazelcast-jet-4.1.jar:4.1]
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.tryProcessWatermark(ProcessorWrapper.java:98) ~[hazelcast-jet-4.1.jar:4.1]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:273) ~[hazelcast-jet-4.1.jar:4.1]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240) ~[hazelcast-jet-4.1.jar:4.1]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293) [hazelcast-jet-4.1.jar:4.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

Running Jet 4.1 using the hazelcast/hazelcast-jet:4.1 docker image.

Found a very similar issue: #1678

**Comment by cangencer** [comment]
Thanks @tplasko for the report. This will be fixed in Jet 4.1.1 release.

**Comment by viliam-durina** [comment]
Currently only pipelines without timestamp work with the JMS or JDBC sink. If you don't do window aggregation, use `withoutTimestamp()` in the pipeline. If you do, you can use the version from `maintenance-4.1` branch where it's already fixed.

**Comment by cangencer** [comment]
@tplasko Jet 4.1.1 is now released, you're welcome to try again.
