### ISSUE TITLE
MySQL JDBC sink soak test failure: Lock wait timeout exceeded

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#2384]
The `Dynamic-JdbcSinkTest` failed with: 
```
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{Dynamic-JdbcSinkTest/jdbcSink#0}: com.hazelcast.jet.JetException: java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:304)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.jet.JetException: java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction
	at com.hazelcast.jet.impl.util.ExceptionUtil.peeledAndUnchecked(ExceptionUtil.java:144)
	at com.hazelcast.jet.impl.util.ExceptionUtil.rethrow(ExceptionUtil.java:155)
	at com.hazelcast.jet.impl.connector.WriteJdbcP.process(WriteJdbcP.java:153)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:93)
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:226)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.processInbox(ProcessorTasklet.java:414)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:289)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293)
	... 5 more
Caused by: java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:210)
	at com.mysql.cj.util.Util.getInstance(Util.java:185)
	at com.mysql.cj.util.Util.getInstance(Util.java:192)
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:875)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:457)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:813)
	at com.mysql.cj.jdbc.StatementWrapper.executeBatch(StatementWrapper.java:545)
	at com.hazelcast.jet.impl.connector.WriteJdbcP.executeBatch(WriteJdbcP.java:225)
	at com.hazelcast.jet.impl.connector.WriteJdbcP.process(WriteJdbcP.java:143)
	... 11 more
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:975)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1114)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:854)
	... 16 more
```

That is the sink processor failed to inset a batch of rows because it failed to obtain a lock. 

At 00:20:53,024, the master member initiated the terminal snapshot 5116. Milliseconds later, all four members initiated the phase 1. Three members logged this:
```
00:20:53,024 DEBUG || - [ExecutionContext] hz.wonderful_archimedes.cached.thread-2 - Starting snapshot 5116 phase 1 for job 'Dynamic-JdbcSinkTest', execution 0496-2dce-5d9f-0006 on member
00:20:53,190 DEBUG || - [Dynamic-JdbcSinkTest/jdbcSink#3] hz.wonderful_archimedes.jet.blocking.thread-24 - flush XaTransactionId{jobId=0496-02f5-1b00-0003, jobNameHash=5057648937613316999, vertexIdHash=-3801245025844213929, processorIndex=3, transactionIndex=0}
00:20:53,190 DEBUG || - [Dynamic-JdbcSinkTest/jdbcSink#3] hz.wonderful_archimedes.jet.blocking.thread-24 - endAndPrepare XaTransactionId{jobId=0496-02f5-1b00-0003, jobNameHash=5057648937613316999, vertexIdHash=-3801245025844213929, processorIndex=3, transactionIndex=0}
00:20:53,247 DEBUG || - [SnapshotPhase1Operation] hz.wonderful_archimedes.jet.cooperative.thread-0 - Snapshot 5116 phase 1 for job 'Dynamic-JdbcSinkTest', execution 0496-2dce-5d9f-0006 finished successfully on member
```
That is the shapshot started on member, did flush, endAndPrepare and ended on member. But on one of the members, the snapshot was started, but after 50.083 seconds the above exception was logged. That is, before the sink received the barrier it needed to write the rows that preceded the barrier, but failed to do se because it failed to obtain some lock.

In the test there is one table with two columns:
```sql
CREATE TABLE t (id int PRIMARY KEY AUTO_INCREMENT, value int)
```

The sink inserts to it using this statement:
```
INSERT INTO t(value) VALUES(?)
```
That is, it doesn't insert into the `id` column. This way the uniqueness of the `id` is guaranteed. The sink uses exactly-once guarantee, so it uses XA transactions that are prepared in the 1st phase of the snapshot and committed in the 2nd.

In parallel, `JdbcSinkVerifier` regularly does these two statements:
```
SELECT * FROM t ORDER BY id LIMIT 1000;

DELETE FROM t WHERE id IN (<ids from the previous query>)"
```
The verifier runs concurrently to the job. It runs these statements using a connection in auto-commit mode. We've considered it as a possible culprit, but couldn't reproduce it. To my understanding, these two statements hold some locks, but release them as they complete. However, the lock timeout suggests that there was a deadlock: the sink processor was waiting for a lock which was held by some other process, but that other process was also blocked by something.

Unfortunately, we don't know for sure what type of lock was the sink processor trying to get and who held it. There are [many types of locks](https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html) in mysql.

Due to #1126, if the query fails, the job is marked as failed and the previous successful snapshot is deleted. We don't know if the deadlock was caused by the test design or if it would happen also without the verifier process running.

Here are logs from the member that caused the failure: [hazelcast-jet-78.log](https://github.com/hazelcast/hazelcast-jet/files/4857963/hazelcast-jet-78.log)
Here are logs from the master member: [hazelcast-jet-76.log](https://github.com/hazelcast/hazelcast-jet/files/4858005/hazelcast-jet-76.log)

Unfortunately we don't have logs from the mysql server.

Here's the test in which we tried to reproduce the deadlock: 
```java
import com.mysql.cj.jdbc.MysqlXADataSource;
import com.mysql.cj.jdbc.MysqlXid;
import org.junit.Rule;
import org.junit.Test;
import org.testcontainers.containers.MySQLContainer;

import javax.sql.XAConnection;
import javax.transaction.xa.Xid;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import static javax.transaction.xa.XAResource.TMNOFLAGS;
import static javax.transaction.xa.XAResource.TMSUCCESS;

public class Testt {

    public static final String USERNAME = "mysqluser";
    public static final String PASSWORD = "mysqlpw";

    @Rule
    public MySQLContainer<?> mysql = new MySQLContainer<>("mysql:8.0.20")
            .withUsername(USERNAME)
            .withPassword(PASSWORD);

    @Test
    public void test() throws Exception {
        MysqlXADataSource ds = new MysqlXADataSource();
        ds.setURL(mysql.getJdbcUrl());
        ds.setUser(USERNAME);
        ds.setPassword(PASSWORD);

        try (
                Connection conn = ds.getConnection();
                Statement stmt = conn.createStatement()
        ) {
            stmt.execute("CREATE TABLE t (id int PRIMARY KEY AUTO_INCREMENT, value int)");
            stmt.execute("INSERT INTO t(value) VALUES(1)");
        }

        Xid xid1 = new MysqlXid(new byte[]{1}, new byte[]{1}, 1);
        Xid xid2 = new MysqlXid(new byte[]{2}, new byte[]{1}, 1);

        // two XA connections for two members
        XAConnection xaConn1 = ds.getXAConnection();
        XAConnection xaConn2 = ds.getXAConnection();

        // the verifier connection and two statements that are never closed
        Connection connVerifier = ds.getXAConnection().getConnection();
        System.out.println("connVerifier.getAutoCommit=" + connVerifier.getAutoCommit());
        Statement stmtSelect = connVerifier.createStatement();
        Statement stmtDelete = connVerifier.createStatement();

        // member 1 starts an XA transaction, inserts some data and prepares
        xaConn1.getXAResource().start(xid1, TMNOFLAGS);
        Connection conn1 = xaConn1.getConnection();
        Statement stmt1 = conn1.createStatement();
        stmt1.execute("INSERT INTO t(value) VALUES(2)");
        xaConn1.getXAResource().end(xid1, TMSUCCESS);
        xaConn1.getXAResource().prepare(xid1);

        // member 2 starts another XA transaction, inserts some data, but doesn't prepare yet
        xaConn2.getXAResource().start(xid2, TMNOFLAGS);
        Connection conn2 = xaConn2.getConnection();
        PreparedStatement stmt2 = conn2.prepareStatement("INSERT INTO t(value) VALUES(?)");
        stmt2.setInt(1, 3);
        stmt2.addBatch();
        stmt2.executeBatch();

        // the verifier queries some IDs and deletes them. Its connection is auto-commit.
        ResultSet resultSet = stmtSelect.executeQuery("SELECT * FROM t ORDER BY id LIMIT 100");
        StringBuilder deleteQuery = new StringBuilder("DELETE FROM t WHERE id IN (");
        while (resultSet.next()) {
            deleteQuery.append(resultSet.getInt(1)).append(',');
        }
        deleteQuery.setCharAt(deleteQuery.length() - 1, ')');

        System.out.println(deleteQuery);
        int count = stmtDelete.executeUpdate(deleteQuery.toString());
        System.out.println("deleted " + count + " rows");

        // member 2 now tries to insert some more rows and do the 1st phase of the snapshot: to end and prepare its txn
        stmt2.setInt(1, 4);
        stmt2.addBatch();
        // this is where the soak test got stuck
        stmt2.executeBatch();

        xaConn2.getXAResource().end(xid2, TMSUCCESS);
        xaConn2.getXAResource().prepare(xid2);

        resultSet = stmtSelect.executeQuery("SELECT * FROM t ORDER BY id LIMIT 3");
        System.out.println("final rows:");
        while (resultSet.next()) {
            System.out.println(resultSet.getInt(1));
        }
    }
}
```

**Comment by olukas** [comment]
Moving to 4.3. We will monitor it and try to obtain more information from mysql log if we see this test failure again.

**Comment by gierlachg** [comment]
Here's the reproducer:
```java
import com.mysql.cj.jdbc.MysqlXADataSource;
import com.mysql.cj.jdbc.MysqlXid;
import org.junit.Rule;
import org.junit.Test;
import org.testcontainers.containers.MySQLContainer;

import javax.sql.XAConnection;
import javax.transaction.xa.Xid;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static javax.transaction.xa.XAResource.TMNOFLAGS;
import static javax.transaction.xa.XAResource.TMSUCCESS;

public class Testtt {

    public static final String USERNAME = "mysqluser";
    public static final String PASSWORD = "mysqlpw";

    @Rule
    public MySQLContainer<?> mysql = new MySQLContainer<>("mysql:8.0.20")
            .withUsername(USERNAME)
            .withPassword(PASSWORD);

    @Test
    public void test() throws Exception {
        MysqlXADataSource ds = new MysqlXADataSource();
        ds.setURL(mysql.getJdbcUrl() + "?useSSL=false");
        ds.setUser(USERNAME);
        ds.setPassword(PASSWORD);

        // insert some data
        try (
                Connection conn = ds.getConnection();
                Statement stmt = conn.createStatement()
        ) {
            stmt.execute("CREATE TABLE t (id int PRIMARY KEY, value int)");
            for (int i = 1; i < 8; i++) { // at least 7 records is required (did not try to dig into that)
                stmt.execute("INSERT INTO t(id, value) VALUES(" + i + ", " + i + ")");
            }
        }

        // member 1 starts an XA transaction, inserts some data and prepares
        Xid xid1 = new MysqlXid(new byte[]{1}, new byte[]{1}, 1);
        XAConnection xaConn1 = ds.getXAConnection();
        xaConn1.getXAResource().start(xid1, TMNOFLAGS);
        Connection conn1 = xaConn1.getConnection();
        Statement stmt1 = conn1.createStatement();
        stmt1.execute("INSERT INTO t(id, value) VALUES(9, 9)"); // gap is required
        xaConn1.getXAResource().end(xid1, TMSUCCESS);
        xaConn1.getXAResource().prepare(xid1);

        // verifier kicks in
        new Thread(() -> {
            try (
                    Connection conn = ds.getXAConnection().getConnection();
                    Statement stmt = conn.createStatement()
            ) {
                ResultSet resultSet = stmt.executeQuery("SELECT id FROM t ORDER BY id LIMIT 1000");
                StringBuilder deleteStatement = new StringBuilder("DELETE FROM t WHERE id IN (");
                while (resultSet.next()) {
                    deleteStatement.append(resultSet.getInt(1)).append(',');
                }
                deleteStatement.setCharAt(deleteStatement.length() - 1, ')');
                // blocks and eventually ends up with 'Lock wait timeout exceeded; try restarting transaction'
                stmt.executeUpdate(deleteStatement.toString());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

        // 'ensure' above DELETE had a chance to execute
        Thread.sleep(1_000);

        // member 2 starts an XA transaction, inserts some data and prepares
        Xid xid2 = new MysqlXid(new byte[]{2}, new byte[]{1}, 1);
        XAConnection xaConn2 = ds.getXAConnection();
        xaConn2.getXAResource().start(xid2, TMNOFLAGS);
        Connection conn2 = xaConn2.getConnection();
        Statement stmt2 = conn2.createStatement();
        stmt2.execute("INSERT INTO t(id, value) VALUES(8, 8)"); // 'filling' the gap blocks
        xaConn2.getXAResource().end(xid2, TMSUCCESS);
        xaConn2.getXAResource().prepare(xid2);

        // commit XA tx
        xaConn1.getXAResource().commit(xid1, false);
        xaConn2.getXAResource().commit(xid2, false);
    }
}
```

And an excerpt from `SHOW ENGINE INNODB STATUS` showing the deadlock:
```
------------
TRANSACTIONS
------------
Trx id counter 2090
Purge done for trx's n:o < 2089 undo n:o < 0 state: running but idle
History list length 6
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 421635902134120, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 421635902130728, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 421635902129880, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 2089, ACTIVE 2 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 2 lock struct(s), heap size 1136, 1 row lock(s)
MySQL thread id 12, OS thread handle 140160891336448, query id 54 172.17.0.1 root update
INSERT INTO t(id, value) VALUES(8, 8)
------- TRX HAS BEEN WAITING 2 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 2 page no 4 n bits 80 index PRIMARY of table `test`.`t` trx id 2089 lock_mode X locks gap before rec insert intention waiting
Record lock, heap no 9 PHYSICAL RECORD: n_fields 4; compact format; info bits 0
 0: len 4; hex 80000009; asc     ;;
 1: len 6; hex 000000000821; asc      !;;
 2: len 7; hex 820000010b0110; asc        ;;
 3: len 4; hex 80000009; asc     ;;

------------------
---TRANSACTION 2084, ACTIVE 3 sec fetching rows
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 8 row lock(s), undo log entries 7
MySQL thread id 11, OS thread handle 140160891631360, query id 46 172.17.0.1 root updating
DELETE FROM t WHERE id IN (1,2,3,4,5,6,7)
------- TRX HAS BEEN WAITING 3 SEC FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 2 page no 4 n bits 80 index PRIMARY of table `test`.`t` trx id 2084 lock_mode X waiting
Record lock, heap no 9 PHYSICAL RECORD: n_fields 4; compact format; info bits 0
 0: len 4; hex 80000009; asc     ;;
 1: len 6; hex 000000000821; asc      !;;
 2: len 7; hex 820000010b0110; asc        ;;
 3: len 4; hex 80000009; asc     ;;

------------------
---TRANSACTION 2081, ACTIVE (PREPARED) 3 sec
2 lock struct(s), heap size 1136, 1 row lock(s), undo log entries 1
MySQL thread id 10, OS thread handle 140160891926272, query id 40 172.17.0.1 root
```

I didn't use `AUTO_INCREMENT` primary key to have the control over what values are inserted when but it does not rule out the reproducer as the default value for `innodb_autoinc_lock_mode` is equal to [interleaved](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_autoinc_lock_mode).

The deadlock is possible with the `DELETE ... WHERE id IN(...)` but not with a batch of `DELETE .. WHERE id = ?` statements. The latter was actually implemented [shortly after the test failure was reported](https://github.com/hazelcast/hazelcast-jet-ansible-tests/commit/e7f74c8579af565f0e941fed4ae379077d36c5b1).
