### ISSUE TITLE
A Jet client connected to remote cluster throws HazelcastSerializationException

### ISSUE THREAD

**Issue by wubumihuo** [hazelcast/hazelcast-jet#2397]
I created a Jet client with the given Hazelcast client configuration, the remote Jet cluster is already set up. The code is:
```java
        clientConfig.setClusterName("jet");
        ClientNetworkConfig networkConfig = clientConfig.getNetworkConfig();
        networkConfig.addAddress("ip:port")
                .setSmartRouting(true)
                .addOutboundPortDefinition("34700-34730")
                .setRedoOperation(true)
                .setConnectionTimeout(2000);
        jet = Jet.newJetClient(clientConfig);
```

when I `join` the job,

```java
Pipeline p = buildPipeline(connectionUrl());
 jet.newJob(p).join();
```

it throws this exception：

```
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Error deserializing vertex 'mapSink(userMap)': com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.StreamCorruptedException: invalid stream header: 01ACED00
	at com.hazelcast.jet.core.Vertex.readData(Vertex.java:219)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:284)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:567)
	at com.hazelcast.jet.core.DAG.readData(DAG.java:486)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:203)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:65)
	at com.hazelcast.jet.impl.JobCoordinationService.deserializeDag(JobCoordinationService.java:815)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:203)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$42(JobCoordinationService.java:978)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$43(JobCoordinationService.java:997)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.StreamCorruptedException: invalid stream header: 01ACED00
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:103)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:290)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:567)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.read(CustomClassLoadedObject.java:56)
	at com.hazelcast.jet.core.Vertex.readData(Vertex.java:217)
	... 24 more
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.io.StreamCorruptedException, Message: invalid stream header: 01ACED00
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at com.hazelcast.internal.nio.IOUtil$ClassLoaderAwareObjectInputStream.<init>(IOUtil.java:750)
	at com.hazelcast.internal.nio.IOUtil$ClassLoaderAwareObjectInputStream.<init>(IOUtil.java:743)
	at com.hazelcast.internal.nio.IOUtil.newObjectInputStream(IOUtil.java:201)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:108)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:91)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:284)
	... 27 more
```

**Comment by viliam-durina** [comment]
Please check that the client and the cluster are of the same version. For Jet, the client is compatible only for patch versions, the first two numbers of the client and cluster have to match.

**Comment by cangencer** [comment]
@wubumihuo can we close this issue? were you able to resolve it?
