### ISSUE TITLE
com.hazelcast.jet.server.JetCommandLineTest.testTargetsInvalidValue

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2409]
_master_ (commit fcb6d77aab7e5a91ba59112d6d73460ce54882be)

Failed on Sonar nightly build: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/555/testReport/com.hazelcast.jet.server/JetCommandLineTest/testTargetsInvalidValue/

Stacktrace:
```
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:404)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output (I'm not sure whether it is related to the issue but job id `ffff-ffff-ffff-ffff` seems suspicious):
```
2020-07-17 13:39:19,996 [ WARN] [hz.goofy_greider.cached.thread-46] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [363c2bd0-e632-4672-993a-2caadcb4d68b] [4.3-SNAPSHOT] null
com.hazelcast.jet.core.JobNotFoundException: Job with id ffff-ffff-ffff-ffff not found
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$callWithJob$34(JobCoordinationService.java:633) ~[hazelcast-jet-core-4.3-SNAPSHOT.jar:4.3-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$43(JobCoordinationService.java:997) ~[hazelcast-jet-core-4.3-SNAPSHOT.jar:4.3-SNAPSHOT]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-4.0.1.jar:4.0.1]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-4.0.1.jar:4.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [hazelcast-4.0.1.jar:4.0.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [hazelcast-4.0.1.jar:4.0.1]
```

**Comment by olukas** [comment]
Failed again on Sonar build: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/584/testReport/junit/com.hazelcast.jet.server/JetCommandLineTest/testTargetsInvalidValue/

**Comment by mtopolnik** [comment]
This test failed due to a timeout. The test class is parallelized and each test method creates its own Jet instance. We might limit the level of parallelism, which looks pretty high (35 Jet instances were started in parallel).

**Comment by olukas** [comment]
Test `com.hazelcast.jet.server.JetCommandLineTest.test_cancelJob_invalidNameOrId` also failed due to timeout on sonar build: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/601/testReport/com.hazelcast.jet.server/JetCommandLineTest/test_cancelJob_invalidNameOrId/

However it can be caused by different exception, see stacktrace:
```
java.lang.AssertionError: 

Expected: exception with message a string containing "No job with name or id 'invalid' was found"
     but: message was "There were 2 errors:
  org.junit.runners.model.TestTimedOutException(test timed out after 600000 milliseconds)
  java.util.concurrent.TimeoutException(null)"
Stacktrace was: org.junit.internal.runners.model.MultipleFailureException: There were 2 errors:
  org.junit.runners.model.TestTimedOutException(test timed out after 600000 milliseconds)
  java.util.concurrent.TimeoutException(null)
	at org.junit.runners.model.MultipleFailureException.assertEmpty(MultipleFailureException.java:67)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:410)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:834)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:252)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:106)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:241)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:49)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by olukas** [comment]
Some more `JetCommandLineTest` tests failed with timeout: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/599/testReport/

**Comment by viliam-durina** [comment]
Also here: http://jenkins.hazelcast.com/job/jet-oss-pr-builder/3214/testReport/junit/com.hazelcast.jet.server/JetCommandLineTest/testTargetsInvalidValue/

**Comment by gurbuzali** [comment]
I've converted the test to run in serial mode [here](https://github.com/hazelcast/hazelcast-jet/pull/2529) 
let's see if it helps with the rest of the `JetCommandLineTest` issues

**Comment by gurbuzali** [comment]
we haven't seen any failures after converting the test to serial (2 months now).  I'll close the issue.
