### ISSUE TITLE
Failures in com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceP_IntegrationTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2452]
_master_ (commit 55958e30a94d419f740be754876f94fc8dc58f1f)

12 from 14 tests failed in `AsyncTransformUsingServiceP_IntegrationTest` with similar cause.

Failed on IBM JDK8: http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/249/testReport/com.hazelcast.jet.impl.processor/AsyncTransformUsingServiceP_IntegrationTest/

Stacktrace:
```
com.hazelcast.core.HazelcastInstanceNotActiveException: HazelcastInstance[[127.0.0.1]:5701] is not active!
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getService(ProxyRegistry.java:73)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.<init>(ProxyRegistry.java:55)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.lambda$new$0(ProxyServiceImpl.java:83)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$$Lambda$510.00000000942A7350.createNew(Unknown Source)
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:140)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getOrCreateRegistry(ProxyServiceImpl.java:143)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:151)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:353)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:172)
	at com.hazelcast.jet.impl.AbstractJetInstance.getMap(AbstractJetInstance.java:130)
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceP_IntegrationTest.before(AsyncTransformUsingServiceP_IntegrationTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:388)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
```

Standard output:
```
Hiccups measured while running test 'test_pipelineApi_mapNotPartitioned[ordered=true](com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceP_IntegrationTest):'
01:57:55, accumulated pauses: 389 ms, max pause: 93 ms, pauses over 1000 ms: 0
```

**Comment by mtopolnik** [comment]
This is a summary of all the errors in this test class:

```
03:58:01 [ERROR] test_pipelineApi_mapNotPartitioned[ordered=true] HazelcastInstance[[127.0.0.1]:5701] is not active!
03:58:01 [ERROR] test_pipelineApi_mapNotPartitioned[ordered=true] java.lang.NullPointerException: Target cannot be null!

03:58:01 [ERROR] test_pipelineApi_mapPartitioned[ordered=true] HazelcastInstance[[127.0.0.1]:5701] is not active!
03:58:01 [ERROR] test_pipelineApi_mapPartitioned[ordered=true] java.lang.NullPointerException: Target cannot be null!

03:58:01 [ERROR] test_pipelineApi_mapPartitioned[ordered=false] HazelcastInstance[[127.0.0.1]:5701] is not active!
03:58:01 [ERROR] test_pipelineApi_mapPartitioned[ordered=false] java.lang.NullPointerException: Target cannot be null!

03:58:01 [ERROR] stressTest_withRestart_graceful[ordered=false] HazelcastInstance[[127.0.0.1]:5701] is not active!
03:58:01 [ERROR] stressTest_withRestart_graceful[ordered=false] java.lang.NullPointerException: Target cannot be null!

03:58:01 [ERROR] stressTest_noRestart[ordered=false] HazelcastInstance[[127.0.0.1]:5701] is not active!
03:58:01 [ERROR] stressTest_noRestart[ordered=false] java.lang.NullPointerException: Target cannot be null!

03:58:01 [ERROR] test_pipelineApi_mapNotPartitioned[ordered=false] HazelcastInstance[[127.0.0.1]:5701] is not active!
03:58:01 [ERROR] test_pipelineApi_mapNotPartitioned[ordered=false] java.lang.NullPointerException: Target cannot be null!
```

So, two test methods passed (stress tests), taking 17 and 15 seconds to complete. Then the cluster dissolved and everything else failed due to that. This test class uses the serial runner and class-global cluster initialization.
