### ISSUE TITLE
4.3-SNAPSHOT, warning over master node not being ready

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2467]
I am testing using Spring, and the instance is returned by Spring suggesting it is ready to go.

However, job submission on 4.3-SNAPSHOT on a single-node cluster gives the error below

This seems to occur for high partition counts, I am using 25057. Didn't see this with 1999.

```
16:45:15.469 [hz.hungry_dijkstra.cached.thread-4] WARN  com.hazelcast.jet.impl.EnterpriseJobCoordinationService - null
 com.hazelcast.spi.exception.RetryableHazelcastException: Cannot submit job with name 'GrafanaGlobalMetricsJob' before the master node initializes job coordination service's state
	at com.hazelcast.jet.impl.JobCoordinationService.hasActiveJobWithName(JobCoordinationService.java:268) ~[hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:213) ~[hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$42(JobCoordinationService.java:978) ~[hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$43(JobCoordinationService.java:999) ~[hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [hazelcast-jet-enterprise-4.3-SNAPSHOT.jar!/:?]
```

**Comment by neilstevenson** [comment]
I can make this recreate on demand, but it's part of a large example, so a lot of work to do so. The error message seems pretty obvious, so this shouldn't be needed.

So the questions are:
(1) is it expected that the instance can be returned to the user before ready for job submission ?
(2) if so, is this a desirable user experience ?

**Comment by mtopolnik** [comment]
As far as I can see, this is just an internal signal that you have to retry a bit later. Nothing actually fails.

**Comment by neilstevenson** [comment]
@mtopolnik Yes, it seems to retry a few times then succeeds. However, it's not a message I'd seen before, and as this is a single node cluster, the node submitting the test job must be the master node. So it's waiting for itself, suggesting the JetInstance is available for job submission while the 1-node cluster is initializing.

**Comment by mtopolnik** [comment]
I think it's waiting for a concurrent process to complete, it's a lazy operation that happens on the first use of a partitioned operation. It's not about clustering.
