### ISSUE TITLE
[Jet + Python] Windows support

### ISSUE THREAD

**Issue by mario45211** [hazelcast/hazelcast-jet#2500]
Hi,

I'm using Hazelcast Jet with stage using Python `mapUsingPython` on the Windows workstation. Each time I starts application, I've got below error:

```
com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.UnsupportedOperationException
        at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:112)
        at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:87)
        at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47)
        at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55)
        at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:314)
        at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:150)
        at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138)
        at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240)
        at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30)
        at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446)
        at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240)
        at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73)
        at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:590)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:575)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
        at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261)
        at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245)
        at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:228)
        at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$42(JobCoordinationService.java:978)
        at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:987)
        at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:977)
        at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:187)
        at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:887)
        at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:246)
        at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$42(JobCoordinationService.java:978)
        at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$43(JobCoordinationService.java:997)
        at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.UnsupportedOperationException: null
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.nio.file.Files.getPosixFilePermissions(Files.java:2037)
        at com.hazelcast.jet.python.PythonServiceContext.editPermissions(PythonServiceContext.java:235)
        at com.hazelcast.jet.python.PythonServiceContext.makeExecutable(PythonServiceContext.java:216)
        at com.hazelcast.jet.python.PythonServiceContext.setupBaseDir(PythonServiceContext.java:168)
        at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:87)
        ... 39 common frames omitted
```
which indicates that Jet is unable to start Python process, because cannot modify POSIX file permissions (because Windows OS does not support it).

So the question is - are you going to provide support for Python functionality (starting Python process) under Windows OS or there is some well-known workaround for Windows users ?

Best regards!

**Comment by mtopolnik** [comment]
Currently we don't support Windows with Python, not just due to permission changing but also because our initialization scripts are `bash`. We haven't yet considered a timeframe for introducing this support.

**Comment by mario45211** [comment]
That's clear for me - thanks for the answer!
