### ISSUE TITLE
com.hazelcast.jet.core.OperationLossTest.when_connectionDroppedWithoutMemberLeaving_then_jobRestarts

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2542]
_master_

Failed on PR builder for nightly tests: http://jenkins.hazelcast.com/job/jet-oss-pr-builder-nightly-tests/10/testReport/com.hazelcast.jet.core/OperationLossTest/when_connectionDroppedWithoutMemberLeaving_then_jobRestarts/

Stacktrace:
```
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
	at com.hazelcast.jet.Job.join(Job.java:155)
	at com.hazelcast.jet.core.OperationLossTest.when_connectionDroppedWithoutMemberLeaving_then_jobRestarts(OperationLossTest.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:373)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	... 1 more
Caused by: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at com.hazelcast.jet.impl.execution.ReceiverTasklet.call(ReceiverTasklet.java:148)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366)
	... 3 more
```

Standard output:
```
2020-09-21 13:28:13,945 [ INFO] [when_connectionDroppedWithoutMemberLeaving_then_jobRestarts] [c.h.t.m.MockNetworkingService]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
connection closed
2020-09-21 13:28:13,969 [ WARN] [hz.infallible_austin.jet.cooperative.thread-28] [c.h.j.i.e.TaskletExecutionService]: [127.0.0.1]:5702 [jet] [4.3-SNAPSHOT] Exception in ReceiverTasklet
java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at com.hazelcast.jet.impl.execution.ReceiverTasklet.call(ReceiverTasklet.java:148) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) [?:1.8.0_251]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
2020-09-21 13:28:13,973 [DEBUG] [hz.infallible_austin.jet.blocking.thread-0] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5702 [jet] [4.3-SNAPSHOT] Execution of job '0500-7539-2509-0001', execution 0500-7539-250a-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) [?:1.8.0_251]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:59) [classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:461) [classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:309) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:373) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_251]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346) ~[classes/:?]
	... 1 more
Caused by: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at com.hazelcast.jet.impl.execution.ReceiverTasklet.call(ReceiverTasklet.java:148) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_251]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346) ~[classes/:?]
	... 1 more
2020-09-21 13:28:13,975 [ INFO] [hz.infallible_austin.jet.blocking.thread-0] [c.h.t.m.MockNetworkingService]: [127.0.0.1]:5702 [jet] [4.3-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}
2020-09-21 13:28:14,028 [ WARN] [hz.romantic_austin.jet.cooperative.thread-34] [c.h.j.i.e.TaskletExecutionService]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Exception in ReceiverTasklet
java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5702
	at com.hazelcast.jet.impl.execution.ReceiverTasklet.call(ReceiverTasklet.java:148) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) [?:1.8.0_251]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
2020-09-21 13:28:14,029 [DEBUG] [hz.romantic_austin.jet.cooperative.thread-32] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Execution of job '0500-7539-2509-0001', execution 0500-7539-250a-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5702
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_251]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_251]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:461) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:392) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:378) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) [?:1.8.0_251]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5702
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:373) ~[classes/:?]
	... 3 more
Caused by: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5702
	at com.hazelcast.jet.impl.execution.ReceiverTasklet.call(ReceiverTasklet.java:148) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366) ~[classes/:?]
	... 3 more
2020-09-21 13:28:14,032 [ INFO] [hz.romantic_austin.async.thread-4] [c.h.t.m.MockNetworkingService]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}
2020-09-21 13:28:14,076 [DEBUG] [ForkJoinPool.commonPool-worker-66] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Execution of job '0500-7539-2509-0001', execution 0500-7539-250a-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701, [127.0.0.1]:5701=com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5702]
2020-09-21 13:28:14,076 [DEBUG] [hz.romantic_austin.cached.thread-9] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Sending CompleteExecutionOperation for job '0500-7539-2509-0001', execution 0500-7539-250a-0001
2020-09-21 13:28:14,078 [DEBUG] [hz.romantic_austin.cached.thread-9] [c.h.j.i.o.CompleteExecutionOperation]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Completing execution 0500-7539-250a-0001 from caller [127.0.0.1]:5701, error=com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
2020-09-21 13:28:14,078 [DEBUG] [hz.romantic_austin.cached.thread-9] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Completed execution of job '0500-7539-2509-0001', execution 0500-7539-250a-0001
2020-09-21 13:28:14,078 [DEBUG] [hz.infallible_austin.generic-operation.thread-20] [c.h.j.i.o.CompleteExecutionOperation]: [127.0.0.1]:5702 [jet] [4.3-SNAPSHOT] Completing execution 0500-7539-250a-0001 from caller [127.0.0.1]:5701, error=com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
2020-09-21 13:28:14,078 [DEBUG] [hz.infallible_austin.generic-operation.thread-20] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5702 [jet] [4.3-SNAPSHOT] Completed execution of job '0500-7539-2509-0001', execution 0500-7539-250a-0001
2020-09-21 13:28:14,078 [ERROR] [hz.romantic_austin.cached.thread-9] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] Execution of job '0500-7539-2509-0001', execution 0500-7539-250a-0001 failed
	Start time: 2020-09-21T13:28:13.743
	Duration: 335 ms
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
com.hazelcast.jet.JetException: Exception in ReceiverTasklet: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:373) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_251]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_251]
Caused by: java.lang.RuntimeException: The member was reconnected: [127.0.0.1]:5701
	at com.hazelcast.jet.impl.execution.ReceiverTasklet.call(ReceiverTasklet.java:148) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366) ~[classes/:?]
	... 3 more
2020-09-21 13:28:14,079 [DEBUG] [hz.romantic_austin.cached.thread-9] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.3-SNAPSHOT] job '0500-7539-2509-0001', execution 0500-7539-250a-0001 is completed
BuildInfo right after when_connectionDroppedWithoutMemberLeaving_then_jobRestarts(com.hazelcast.jet.core.OperationLossTest): BuildInfo{version='4.0.3-SNAPSHOT', build='20200914', buildNumber=20200914, revision=d717127, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='4.3-SNAPSHOT', build='20200921', revision='58e4a39'}}
Hiccups measured while running test 'when_connectionDroppedWithoutMemberLeaving_then_jobRestarts(com.hazelcast.jet.core.OperationLossTest):'
13:28:10, accumulated pauses: 245 ms, max pause: 200 ms, pauses over 1000 ms: 0
13:28:15, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
Failed also on common nightly run: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/623/testReport/com.hazelcast.jet.core/OperationLossTest/when_connectionDroppedWithoutMemberLeaving_then_jobRestarts/
