### ISSUE TITLE
Python Soak-Test Failure

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-jet#2585]
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 1
    at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
    at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
    at com.hazelcast.jet.Job.join(Job.java:155)
    at com.hazelcast.jet.tests.python.PythonTest.test(PythonTest.java:98)
    at com.hazelcast.jet.tests.common.AbstractSoakTest.testInternal(AbstractSoakTest.java:144)
    at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:83)
    at com.hazelcast.jet.tests.python.PythonTest.main(PythonTest.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:126)
    at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:218)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.hazelcast.jet.picocli.CommandLine.execute(CommandLine.java:1189)
    at com.hazelcast.jet.picocli.CommandLine.access$800(CommandLine.java:141)
    at com.hazelcast.jet.picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
    at com.hazelcast.jet.picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
    at com.hazelcast.jet.picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
    at com.hazelcast.jet.picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
    at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:162)
    at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:139)
Caused by: com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 1
    at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:114)
    at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:87)
    at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47)
    at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55)
    at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:327)
    at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:158)
    at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138)
    at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240)
    at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30)
    at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446)
    at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240)
    at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73)
    at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:596)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:581)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:237)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
    at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261)
    at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245)
    at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:227)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1023)
    at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1032)
    at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1022)
    at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:189)
    at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:932)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:257)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1023)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1044)
    at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.Exception, Message: Initialization script finished with non-zero exit code: 1
    at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:105)
    ... 39 more
19:13:48.922 [ERROR] [c.h.j.t.p.PythonTest] hz.client_1 [jet] [4.3] [4.0.3] com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 1
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 1
    at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
    at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
    at com.hazelcast.jet.Job.join(Job.java:155)
    at com.hazelcast.jet.tests.python.PythonTest.test(PythonTest.java:98)
    at com.hazelcast.jet.tests.common.AbstractSoakTest.testInternal(AbstractSoakTest.java:144)
    at com.hazelcast.jet.tests.common.AbstractSoakTest.run(AbstractSoakTest.java:83)
    at com.hazelcast.jet.tests.python.PythonTest.main(PythonTest.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.hazelcast.jet.impl.JetBootstrap.executeJar(JetBootstrap.java:126)
    at com.hazelcast.jet.server.JetCommandLine.submit(JetCommandLine.java:218)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.hazelcast.jet.picocli.CommandLine.execute(CommandLine.java:1189)
    at com.hazelcast.jet.picocli.CommandLine.access$800(CommandLine.java:141)
    at com.hazelcast.jet.picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
    at com.hazelcast.jet.picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
    at com.hazelcast.jet.picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
    at com.hazelcast.jet.picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
    at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:162)
    at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:139)
Caused by: com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 1
    at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:114)
    at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:87)
    at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47)
    at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55)
    at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:327)
    at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:158)
    at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138)
    at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240)
    at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30)
    at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446)
    at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240)
    at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73)
    at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:596)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:581)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:237)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
    at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261)
    at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245)
    at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:227)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1023)
    at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1032)
    at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1022)
    at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:189)
    at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:932)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:257)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1023)
    at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1044)
    at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
    at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
    at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name: java.lang.Exception, Message: Initialization script finished with non-zero exit code: 1
    at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:105)
    ... 39 more
19:13:48.924 [ INFO] [c.h.j.t.p.PythonTest] hz.client_1 [jet] [4.3] [4.0.3] Finished with failure at test

**Comment by jbartok** [comment]
Seems like the issue is caused by an intermittent, known issue with the python service init script. Apparently there is not much we can, or should do about it at this point.
