### ISSUE TITLE
Container startup failed for *CdcNetworkIntegrationTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2601]
_master_ (commit 0fbe205b49c75a4f1df05b2f0d4ad29f81c43f04)

`*CdcNetworkIntegrationTest`s intermittently fail with `Container startup failed`. I see following tests to fail with that:
- `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail]`
- `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_networkDisconnectDuringSnapshotting_then_jetSourceIsStuckUntilReconnect[reconnect]`
- `com.hazelcast.jet.cdc.postgres.PostgresCdcNetworkIntegrationTest.when_databaseShutdownOrLongDisconnectDuringBinlogReading[fail]`
- `com.hazelcast.jet.cdc.postgres.PostgresCdcNetworkIntegrationTest.when_shortNetworkDisconnectDuringSnapshotting_then_connectorDoesNotNoticeAnything[reconnect]`
- `com.hazelcast.jet.cdc.postgres.PostgresCdcNetworkIntegrationTest.when_shortNetworkDisconnectDuringSnapshotting_then_connectorDoesNotNoticeAnything[reconnect w/ state reset]`

Failed on nightly run, for example: http://jenkins.hazelcast.com/job/jet-oss-master-nightly/274/testReport/junit/com.hazelcast.jet.cdc.mysql/MySqlCdcNetworkIntegrationTest/when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally_fail_/

Stacktrace (for `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail]`):
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initToxiproxy(MySqlCdcNetworkIntegrationTest.java:369)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally(MySqlCdcNetworkIntegrationTest.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.NullPointerException
		at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
		at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
		at java.util.Collections$SetFromMap.remove(Collections.java:5514)
		at org.testcontainers.utility.ResourceReaper.removeNetwork(ResourceReaper.java:359)
		at org.testcontainers.utility.ResourceReaper.removeNetworkById(ResourceReaper.java:322)
		at org.testcontainers.containers.Network$NetworkImpl.close(Network.java:102)
		at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally(MySqlCdcNetworkIntegrationTest.java:268)
		... 12 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 15 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:498)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 16 more
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:129)
	at com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:27)
	at com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:12)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102)
	at com.sun.proxy.$Proxy53.exec(Unknown Source)
	at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:91)
	at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:62)
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:811)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:359)
	... 18 more
```

Standard output (for `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail]`):
```
Finished Running Test: when_noDatabaseToConnectTo[fail] in 12.814 seconds.
Started Running Test: when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail]
2020-10-08 23:53:36,324 [ INFO] [when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally] [d.1.0]]: Creating container for image: shopify/toxiproxy:2.1.0
2020-10-08 23:53:36,326 [ERROR] [when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally] [d.1.0]]: Could not start container
com.github.dockerjava.api.exception.NotFoundException: {"message":"could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:129) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:27) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:12) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.14.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102) ~[testcontainers-1.14.3.jar:?]
	at com.sun.proxy.$Proxy53.exec(Unknown Source) ~[?:?]
	at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:91) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:62) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:811) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:359) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.14.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.14.3.jar:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initToxiproxy(MySqlCdcNetworkIntegrationTest.java:369) [test-classes/:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally(MySqlCdcNetworkIntegrationTest.java:237) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_251]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.0.3-tests.jar:4.0.3]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.0.3-tests.jar:4.0.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
BuildInfo right after when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest): BuildInfo{version='4.0.3', build='20200921', buildNumber=20200921, revision=59ae831, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='4.4-SNAPSHOT', build='20201008', revision='0fbe205'}}
Hiccups measured while running test 'when_networkDisconnectDuringBinlogRead_then_connectorReconnectsInternally[fail](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest):'
23:53:35, accumulated pauses: 61 ms, max pause: 13 ms, pauses over 1000 ms: 0
23:53:40, accumulated pauses: 39 ms, max pause: 2 ms, pauses over 1000 ms: 0
23:53:45, accumulated pauses: 96 ms, max pause: 73 ms, pauses over 1000 ms: 0
```

**Comment by jbartok** [comment]
This failure has occurred before I reverted the *CdcNetworkIntegrationTest to making use of the Testcontainers resource reaper. It's a container that is started by the tests, but is longer lived than the process that started it and takes care of all required docker cleanup. Hopefully this change will solve this particular problem, since it seems to be related to Docker networks not being cleaned up... 

I'm also submitting a [PR with a further improvement](https://github.com/hazelcast/hazelcast-jet/pull/2667) to how the tests interact with the resource reaper.

Not much else I can think of... Maybe close this issue and open another one if problems still happen on the latest code? @olukas ?

**Comment by olukas** [comment]
@jbartok sure, feel free to close it. I can reopen it (or create another issue) in case if it will fail again with the latest code.
