### ISSUE TITLE
4.4-SNAPSHOT error with master node not available on integration tests

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2614]
Using 4.4-SNAPSHOT, build 20201020,
and the code in this module https://github.com/hazelcast/hazelcast-platform-demos/tree/maintenance/ml/ml-ri/python-job

Running tests using `mvn install -Prelease` gives intermittent errors 

```
[INFO] Running com.hazelcast.platform.demos.ml.ri.Pi2IT
12:59:30.050 [ INFO] [c.h.i.AddressPicker] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [127.0.0.1]
12:59:30.050 [ INFO] [c.h.i.AddressPicker] Picked [127.0.0.1]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
12:59:30.051 [ INFO] [c.h.system] Hazelcast Jet 4.4-SNAPSHOT (20201020 - a8b10ab) starting at [127.0.0.1]:5701
12:59:30.051 [ INFO] [c.h.system] Cluster name: dev
12:59:30.051 [ INFO] [c.h.system] 
	o   o   o   o---o o---o o     o---o   o   o---o o-o-o        o o---o o-o-o
	|   |  / \     /  |     |     |      / \  |       |          | |       |
	o---o o---o   o   o-o   |     o     o---o o---o   |          | o-o     |
	|   | |   |  /    |     |     |     |   |     |   |      \   | |       |
	o   o o   o o---o o---o o---o o---o o   o o---o   o       o--o o---o   o
12:59:30.051 [ INFO] [c.h.system] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
12:59:30.053 [ INFO] [c.h.s.i.o.i.BackpressureRegulator] Backpressure is disabled
12:59:30.059 [ INFO] [c.h.i.i.Node] Creating TcpIpJoiner
12:59:30.060 [ WARN] [c.h.c.CPSubsystem] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
12:59:30.066 [ INFO] [c.h.j.i.e.TaskletExecutionService] Creating idler with jet.idle.cooperative.min.microseconds=25µs,jet.idle.cooperative.max.microseconds=500µs
12:59:30.066 [ INFO] [c.h.j.i.e.TaskletExecutionService] Creating idler with jet.idle.noncooperative.min.microseconds=25µs,jet.idle.noncooperative.max.microseconds=5000µs
12:59:30.069 [ INFO] [c.h.j.i.JetService] Setting number of cooperative threads and default parallelism to 12
12:59:30.069 [ INFO] [c.h.s.i.o.i.OperationExecutorImpl] Starting 12 partition threads and 7 generic threads (1 dedicated for priority tasks)
12:59:30.071 [ INFO] [c.h.i.d.Diagnostics] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
12:59:30.071 [ INFO] [c.h.c.LifecycleService] [127.0.0.1]:5701 is STARTING
12:59:30.074 [ INFO] [c.h.i.n.t.TcpIpConnector] Connecting to /127.0.0.1:5703, timeout: 10000, bind-any: true
12:59:30.074 [ INFO] [c.h.i.n.t.TcpIpConnector] Connecting to /127.0.0.1:5702, timeout: 10000, bind-any: true
12:59:30.074 [ INFO] [c.h.i.n.t.TcpIpConnector] Could not connect to: /127.0.0.1:5703. Reason: SocketException[Connection refused to address /127.0.0.1:5703]
12:59:30.074 [ INFO] [c.h.i.n.t.TcpIpConnector] Could not connect to: /127.0.0.1:5702. Reason: SocketException[Connection refused to address /127.0.0.1:5702]
12:59:30.075 [ INFO] [c.h.i.c.i.TcpIpJoiner] [127.0.0.1]:5703 is added to the blacklist.
12:59:30.075 [ INFO] [c.h.i.c.i.TcpIpJoiner] [127.0.0.1]:5702 is added to the blacklist.
12:59:31.077 [ INFO] [c.h.i.c.ClusterService] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - ab936539-5997-49c3-8156-0e4af091dd74 this
]

12:59:31.078 [ INFO] [c.h.c.LifecycleService] [127.0.0.1]:5701 is STARTED
12:59:31.085 [ INFO] [c.h.i.p.i.PartitionStateManager] Initializing cluster partition table arrangement...
12:59:31.093 [ WARN] [c.h.j.i.JobCoordinationService] null
com.hazelcast.spi.exception.RetryableHazelcastException: Cannot submit job with name 'originInsideCircle' before the master node initializes job coordination service's state
	at com.hazelcast.jet.impl.JobCoordinationService.hasActiveJobWithName(JobCoordinationService.java:280)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:225)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
12:59:31.096 [ WARN] [c.h.j.i.JobCoordinationService] null
com.hazelcast.spi.exception.RetryableHazelcastException: Cannot submit job with name 'originInsideCircle' before the master node initializes job coordination service's state
	at com.hazelcast.jet.impl.JobCoordinationService.hasActiveJobWithName(JobCoordinationService.java:280)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:225)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
12:59:31.099 [ WARN] [c.h.j.i.JobCoordinationService] null
com.hazelcast.spi.exception.RetryableHazelcastException: Cannot submit job with name 'originInsideCircle' before the master node initializes job coordination service's state
	at com.hazelcast.jet.impl.JobCoordinationService.hasActiveJobWithName(JobCoordinationService.java:280)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:225)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

**Comment by mtopolnik** [comment]
These are three `WARN` messages... is there any failure?

**Comment by mtopolnik** [comment]
This probably duplicates #2467.
