### ISSUE TITLE
NPE when inserting Portable

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#2618]
I'm on `ebe7391443`
When I modify [this test](https://github.com/hazelcast/hazelcast-jet/blob/fc92089fc49b9bf40749e0a3ad44dee94ecbc4a4/hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPortableTest.java#L122) to skip the [`put()`](https://github.com/hazelcast/hazelcast-jet/blob/fc92089fc49b9bf40749e0a3ad44dee94ecbc4a4/hazelcast-jet-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/map/SqlPortableTest.java#L125-L140) then I'm getting NPE.

```
com.hazelcast.sql.HazelcastSqlException
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:78)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:215)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:188)
	at com.hazelcast.jet.impl.JetSqlServiceImpl.execute(JetSqlServiceImpl.java:36)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:144)
	at com.hazelcast.jet.sql.impl.connector.map.SqlPortableTest.test_insertsIntoDiscoveredMap(SqlPortableTest.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: com.hazelcast.sql.impl.QueryException
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:59)
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:77)
	at com.hazelcast.sql.impl.calcite.OptimizerContext.parse(OptimizerContext.java:134)
	at com.hazelcast.sql.impl.calcite.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:126)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:260)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:241)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:205)
	... 16 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.jet.sql.impl.parse.SqlExtendedInsert.validate(SqlExtendedInsert.java:88)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1059)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:766)
	at com.hazelcast.jet.sql.impl.validate.JetSqlValidator.validate(JetSqlValidator.java:61)
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:88)
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:71)
	... 21 more
```
I get that this scenario is not supported as there is no way to derive table schema. However I would expect a nice error instead of this.

**Comment by viliam-durina** [comment]
Fixed, now it will report 
```Object 'o_99520d84_346a_4cba_89cc_888535565625' not found within 'hazelcast.partitioned'```
