### ISSUE TITLE
com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading[reconnect]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2634]
_master_ (commit af2d287e280777ea02c8385b609492c783c0c694)

Failed on Sonar nightly build: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/665/testReport/junit/com.hazelcast.jet.cdc.mysql/MySqlCdcNetworkIntegrationTest/when_databaseShutdownDuringBinlogReading_reconnect_/

Stacktrace:
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:358)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 15 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:498)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 16 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading_reconnect____2418c50b-cd1d-42ae-ba3a-ae455ae1d684 (8845cec02ea5c5322dde14dc5613df6da576c232f82fe110482901a1693551e9): Error starting userland proxy: listen tcp 0.0.0.0:37224: bind: address already in use"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102)
	at com.sun.proxy.$Proxy45.exec(Unknown Source)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419)
	... 18 more
```

Standard output:
```
Started Running Test: when_databaseShutdownDuringBinlogReading[reconnect]
2020-10-30 13:46:33,668 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Creating container for image: debezium/example-mysql:1.2
2020-10-30 13:46:35,962 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Starting container with ID: 7dc7f480ed0a0a34a092dd5ac5e788f2342defa2ea74bbd6b1e7471ce679dcd1
2020-10-30 13:46:36,925 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading_reconnect____7d00868b-0c40-4416-91f0-bee91f4f49fc (22a99fa5678a8847975e17c8cb2f26a2ba96c88b177a1cca53c634db645bf215): Error starting userland proxy: listen tcp 0.0.0.0:37224: bind: address already in use"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.14.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102) ~[testcontainers-1.14.3.jar:?]
	at com.sun.proxy.$Proxy45.exec(Unknown Source) ~[?:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.14.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.14.3.jar:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:358) [test-classes/:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:271) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.0.3-tests.jar:4.0.3]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.0.3-tests.jar:4.0.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-30 13:46:36,935 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: There are no stdout/stderr logs available for the failed container
2020-10-30 13:46:36,935 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Creating container for image: debezium/example-mysql:1.2
2020-10-30 13:46:38,423 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Starting container with ID: 84cd2e40bbd31806cb716d8cd8e3489413544c68593a324ddddda9a5beae1af3
2020-10-30 13:46:38,726 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading_reconnect____0b4aebea-d300-401d-a185-1a4b67750285 (51ee42d95b6242640c5b82616f704f5873ab69f733f9e8a022aeb4335cdefbc8): Error starting userland proxy: listen tcp 0.0.0.0:37224: bind: address already in use"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.14.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102) ~[testcontainers-1.14.3.jar:?]
	at com.sun.proxy.$Proxy45.exec(Unknown Source) ~[?:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.14.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.14.3.jar:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:358) [test-classes/:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:271) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.0.3-tests.jar:4.0.3]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.0.3-tests.jar:4.0.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-30 13:46:38,729 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: There are no stdout/stderr logs available for the failed container
2020-10-30 13:46:38,729 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Creating container for image: debezium/example-mysql:1.2
2020-10-30 13:46:40,102 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Starting container with ID: 697711a5a7d95fc33ef677eb695c52caab46d15952edcd92bf016ef2ad7cacee
2020-10-30 13:46:40,373 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading_reconnect____2418c50b-cd1d-42ae-ba3a-ae455ae1d684 (8845cec02ea5c5322dde14dc5613df6da576c232f82fe110482901a1693551e9): Error starting userland proxy: listen tcp 0.0.0.0:37224: bind: address already in use"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.14.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102) ~[testcontainers-1.14.3.jar:?]
	at com.sun.proxy.$Proxy45.exec(Unknown Source) ~[?:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.14.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.14.3.jar:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:358) [test-classes/:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:271) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.0.3-tests.jar:4.0.3]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.0.3-tests.jar:4.0.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-30 13:46:40,376 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: There are no stdout/stderr logs available for the failed container
BuildInfo right after when_databaseShutdownDuringBinlogReading[reconnect](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest): BuildInfo{version='4.0.3', build='20200921', buildNumber=20200921, revision=59ae831, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='4.4-SNAPSHOT', build='20201030', revision='af2d287'}}
Hiccups measured while running test 'when_databaseShutdownDuringBinlogReading[reconnect](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest):'
13:46:30, accumulated pauses: 121 ms, max pause: 53 ms, pauses over 1000 ms: 0
13:46:35, accumulated pauses: 40 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:46:40, accumulated pauses: 33 ms, max pause: 31 ms, pauses over 1000 ms: 0
```

**Comment by olukas** [comment]
The same type of issue occurred for `com.hazelcast.jet.cdc.postgres.PostgresCdcNetworkIntegrationTest.when_databaseShutdownOrLongDisconnectDuringSnapshotting[reconnect]` on Oracle JDK 8 build: http://jenkins.hazelcast.com/job/jet-oss-master-nightly-oracle-jdk8/299/testReport/junit/com.hazelcast.jet.cdc.postgres/PostgresCdcNetworkIntegrationTest/when_databaseShutdownOrLongDisconnectDuringSnapshotting_reconnect_/

**Comment by jbartok** [comment]
This failure is the reason why I've turned the resource reaper off for these tests initially... Obviously that didn't help... Now the reaper is back and I've made [this further change](https://github.com/hazelcast/hazelcast-jet/pull/2667) to it. I'll try to monitor if the change helps or not.
