### ISSUE TITLE
Enhancement: hazelcast-jet-sql, suppress duplicate definition when unchanged

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2694]
If I run
```
CREATE EXTERNAL MAPPING something (...) TYPE Kafka ...
```
twice, I get
```
Caused by: com.hazelcast.sql.impl.QueryException: Mapping already exists: something
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:67)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:51)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:47)
	at com.hazelcast.jet.sql.impl.schema.MappingCatalog.createMapping(MappingCatalog.java:74)
	at com.hazelcast.jet.sql.impl.JetPlanExecutor.execute(JetPlanExecutor.java:54)
	at com.hazelcast.jet.sql.impl.JetPlan$CreateMappingPlan.execute(JetPlan.java:57)
	at com.hazelcast.jet.sql.impl.JetSqlCoreBackendImpl.execute(JetSqlCoreBackendImpl.java:91)
	at com.hazelcast.sql.impl.SqlServiceImpl.executeJet(SqlServiceImpl.java:287)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:276)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:247)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:205)
	... 3 more
```

However, this is reasonably likely if Kafka is not restarted and Jet is.

It would be helpful if the exception was thrown if the definition attempted was different. If the definition is unchanged from what is stored, there is no harm to apply.

**Comment by neilstevenson** [comment]
Steps to recreate

```
        String myDefinition = "CREATE EXTERNAL MAPPING something ( "
                + " neil VARCHAR "
                + ") "
                + "TYPE Kafka "
                + "OPTIONS ( "
                + " valueFormat 'json',"
                + " \"auto.offset.reset\" 'earliest',"
                + " \"bootstrap.servers\" '127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094'"
                + ")";
        jetInstance.getSql().execute(myDefinition);
        jetInstance.getSql().execute(myDefinition);
```

As nodes join the cluster, the ability to idempotently ensure definitions are present will be helpful

**Comment by gierlachg** [comment]
You can use `CREATE OR REPLACE MAPPING something...` or `CREATE MAPPING IF NOT EXISTS something...`

**Comment by viliam-durina** [comment]
I think the response addresses the issue and am closing. @neilstevenson, feel free to reopen if you still have issues.
