### ISSUE TITLE
Bug in REBALANCE implementation

### ISSUE THREAD

**Issue by jbartok** [hazelcast/hazelcast-jet#2735]
There seems to be a bug in the implementation of the pipeline `rebalance` operation. 

Take following code:
```
        JetInstance jet = Jet.newJetInstance();
        Jet.newJetInstance();
        try {
            Pipeline p = Pipeline.create();
            p.readFrom(TestSources.itemStream(3))
                    .withNativeTimestamps(0)
                    .rebalance(SimpleEvent::sequence)
                    .writeTo(Sinks.logger());

            jet.newJob(p).join();
        } finally {
            Jet.shutdownAll();
        }
```

It will throw:
```
java.lang.ClassCastException: com.hazelcast.jet.impl.JetEvent cannot be cast to com.hazelcast.jet.pipeline.test.SimpleEvent
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47)
	at com.hazelcast.jet.core.Edge$KeyPartitioner.getPartition(Edge.java:726)
	at com.hazelcast.jet.impl.execution.OutboundCollector$Partitioned.offer(OutboundCollector.java:193)
	at com.hazelcast.jet.impl.execution.OutboxImpl.doOffer(OutboxImpl.java:251)
	at com.hazelcast.jet.impl.execution.OutboxImpl.offerInternal(OutboxImpl.java:139)
	at com.hazelcast.jet.impl.execution.OutboxImpl.offer(OutboxImpl.java:94)
	at com.hazelcast.jet.core.AbstractProcessor.tryEmit(AbstractProcessor.java:309)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:408)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:421)
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:128)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:467)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:367)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:242)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293)
```

Observation: only happens when multiple Jet members are involved, that's why I didn't just provide pipeline code.

**Comment by mtopolnik** [comment]
Quick fix in `StreamStageImpl`:

```java
    @Nonnull @Override
    public <K> StreamStage<T> rebalance(@Nonnull FunctionEx<? super T, ? extends K> keyFn) {
        checkSerializable(keyFn, "keyFn");
        @SuppressWarnings("unchecked")
        FunctionEx<? super T, ? extends K> adaptedKeyFn =
                (FunctionEx<? super T, ? extends K>) fnAdapter.adaptKeyFn(keyFn);
        return new StreamStageImpl<>(this, adaptedKeyFn);
    }
```

We miss `keyFn` adapting because in the design so far it was happening at a later point. I haven't thoroughly checked whether this is the best place to add it.

**Comment by jbartok** [comment]
Thank you.
