### ISSUE TITLE
Preserver order breaks pipeline if hashJoin is used

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2744]
If pipeline includes `hashJoin` stage (or `hashJoin2`, `innerHashJoin`, `innerHashJoin2`) and `preservedOrder` is set to `true` and partitioned source is used (tested with `mapJournal`) then job fails with:
```
Exception in ProcessorTasklet{mapJournalSource(sourceMap)#1}
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4164)
	at com.hazelcast.jet.impl.util.CircularListCursor.value(CircularListCursor.java:57)
	at com.hazelcast.jet.impl.execution.OutboundCollector$RoundRobin.offer(OutboundCollector.java:121)
	at com.hazelcast.jet.impl.execution.OutboxImpl.doOffer(OutboxImpl.java:251)
	at com.hazelcast.jet.impl.execution.OutboxImpl.offerInternal(OutboxImpl.java:139)
	at com.hazelcast.jet.impl.execution.OutboxImpl.offer(OutboxImpl.java:94)
	at com.hazelcast.jet.core.AbstractProcessor.tryEmit(AbstractProcessor.java:309)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:408)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:421)
	at com.hazelcast.jet.impl.connector.StreamEventJournalP.emitResultSet(StreamEventJournalP.java:207)
	at com.hazelcast.jet.impl.connector.StreamEventJournalP.complete(StreamEventJournalP.java:192)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:467)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:367)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:242)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Steps to reproduce:
```
Pipeline p = Pipeline.create();
StreamStage<Map.Entry<Integer, Integer>> source
        = p.readFrom(Sources.<Integer, Integer>mapJournal("sourceMap", JournalInitialPosition.START_FROM_OLDEST))
                .withoutTimestamps();
BatchStage<Map.Entry<Integer, String>> enr = p.readFrom(Sources.map("enrichMap"));
StreamStage<Map.Entry<Integer, String>> hashJoin = source.hashJoin(
        enr,
        joinMapEntries(t -> t.getKey()),
        (t, u) -> {
            return entry(t.getKey(), t.getValue() + u);
        }
);
hashJoin.writeTo(Sinks.logger());
p.setPreserveOrder(true);
JetConfig config = new JetConfig();
EventJournalConfig eventJournalConfig = config.getHazelcastConfig().getMapConfig("sourceMap").getEventJournalConfig();
eventJournalConfig.setEnabled(true);
JetInstance jet = Jet.newJetInstance(config);
try {
    IMap<Integer, String> eMap = jet.getMap("enrichMap");
    eMap.put(0, "a");
    eMap.put(1, "b");
    Job job = jet.newJob(p);
    Thread.sleep(5000);
    IMap<Integer, Integer> map = jet.getMap("sourceMap");
    for (int i = 0; i < 100; i++) {
        map.put(0, i);
        map.put(1, i);
    }
    Thread.sleep(5000);
    job.cancel();
    Thread.sleep(1000);
    System.out.println("DONE");
} finally {
    jet.shutdown();
}
```

**Comment by viliam-durina** [comment]
From the stack trace it looks like if the local parallelism of the vertex following the map journal source was 0...
