### ISSUE TITLE
SQL console crashes

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet#2768]
it appears the sql console crashed when there is a null field:
```
sql> select * from lionking;
+--------------------+--------------------+--------------------+
|               __key|animal              |                 age|
+--------------------+--------------------+--------------------+
17:44:22.721 [ INFO] [c.h.c.LifecycleService] hz.client_1 [jet] [4.4-SNAPSHOT] [4.1.1] HazelcastClient 4.1.1 (20201222 - 27af558) is SHUTTING_DOWN
17:44:22.744 [ INFO] [c.h.c.i.c.ClientConnectionManager] hz.client_1 [jet] [4.4-SNAPSHOT] [4.1.1] Removed connection to endpoint: [10.0.0.49]:5701:f70c2a15-7d50-44c5-af21-c3af97e992f4, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:41435->/127.0.0.1:5701}, remoteAddress=[10.0.0.49]:5701, lastReadTime=2021-01-04 17:44:22.720, lastWriteTime=2021-01-04 17:44:22.717, closedTime=2021-01-04 17:44:22.722, connected server version=4.1.1}
17:44:22.745 [ INFO] [c.h.c.LifecycleService] hz.client_1 [jet] [4.4-SNAPSHOT] [4.1.1] HazelcastClient 4.1.1 (20201222 - 27af558) is CLIENT_DISCONNECTED
17:44:22.748 [ INFO] [c.h.c.LifecycleService] hz.client_1 [jet] [4.4-SNAPSHOT] [4.1.1] HazelcastClient 4.1.1 (20201222 - 27af558) is SHUTDOWN
com.hazelcast.jet.picocli.CommandLine$ExecutionException: Error while calling command (public void com.hazelcast.jet.server.JetCommandLine.sql(com.hazelcast.jet.server.JetCommandLine$Verbosity,com.hazelcast.jet.server.JetCommandLine$TargetsMixin)): java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.hazelcast.sql.SqlRow.getObject(int)" is null
	at com.hazelcast.jet.picocli.CommandLine.execute(CommandLine.java:1207)
	at com.hazelcast.jet.picocli.CommandLine.access$800(CommandLine.java:141)
	at com.hazelcast.jet.picocli.CommandLine$RunAll.handle(CommandLine.java:1416)
	at com.hazelcast.jet.picocli.CommandLine$RunAll.handle(CommandLine.java:1376)
	at com.hazelcast.jet.picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
	at com.hazelcast.jet.picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
	at com.hazelcast.jet.server.JetCommandLine.runCommandLine(JetCommandLine.java:202)
	at com.hazelcast.jet.server.JetCommandLine.main(JetCommandLine.java:179)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.hazelcast.sql.SqlRow.getObject(int)" is null
	at com.hazelcast.jet.server.JetCommandLine.printRow(JetCommandLine.java:1131)
	at com.hazelcast.jet.server.JetCommandLine.executeSqlCmd(JetCommandLine.java:991)
	at com.hazelcast.jet.server.JetCommandLine.lambda$sql$b0ae703e$1(JetCommandLine.java:309)
	at com.hazelcast.function.ConsumerEx.accept(ConsumerEx.java:46)
	at com.hazelcast.jet.server.JetCommandLine.runWithJet(JetCommandLine.java:617)
	at com.hazelcast.jet.server.JetCommandLine.sql(JetCommandLine.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.hazelcast.jet.picocli.CommandLine.execute(CommandLine.java:1189)
	... 7 more
```

**Comment by viliam-durina** [comment]
A childhood disease :-)
