### ISSUE TITLE
com.hazelcast.jet.kinesis.KinesisIntegrationTest.com.hazelcast.jet.kinesis.KinesisIntegrationTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2838]
_master_ (commit afbeccd072bae869696cd8a576e437876ef8b64c)

Failed on Zulu JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-zulu-jdk8/324/testReport/junit/com.hazelcast.jet.kinesis/KinesisIntegrationTest/com_hazelcast_jet_kinesis_KinesisIntegrationTest/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 900 seconds
	at org.testcontainers.shaded.okio.Buffer.getByte(Buffer.java:312)
	at org.testcontainers.shaded.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:310)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:492)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
	at org.testcontainers.shaded.okhttp3.internal.Util.skipAll(Util.java:204)
	at org.testcontainers.shaded.okhttp3.internal.Util.discard(Util.java:186)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.close(Http1ExchangeCodec.java:511)
	at org.testcontainers.shaded.okio.ForwardingSource.close(ForwardingSource.java:43)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.java:313)
	at org.testcontainers.shaded.okio.RealBufferedSource.close(RealBufferedSource.java:476)
	at org.testcontainers.shaded.okhttp3.internal.Util.closeQuietly(Util.java:139)
	at org.testcontainers.shaded.okhttp3.ResponseBody.close(ResponseBody.java:192)
	at org.testcontainers.shaded.okhttp3.Response.close(Response.java:290)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient$OkResponse.close(OkDockerHttpClient.java:285)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$null$0(DefaultInvocationBuilder.java:272)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$87/43725871.close(Unknown Source)
	at com.github.dockerjava.api.async.ResultCallbackTemplate.close(ResultCallbackTemplate.java:77)
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:202)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:205)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1029)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
2021-01-22 02:09:16,459 [ INFO] [main] [o.t.d.DockerClientProviderStrategy]: Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
2021-01-22 02:09:17,091 [ INFO] [main] [o.t.d.DockerClientProviderStrategy]: Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
2021-01-22 02:09:17,126 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: Docker host IP address is 172.17.0.1
2021-01-22 02:09:17,163 [ INFO] [Time-limited test] [o.t.DockerClientFactory]: Connected to docker: 
  Server Version: 18.06.1-ce
  API Version: 1.38
  Operating System: Red Hat Enterprise Linux
  Total Memory: 386667 MB
2021-01-22 02:09:17,168 [ INFO] [Time-limited test] [o.t.u.ImageNameSubstitutor]: Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2021-01-22 02:09:17,197 [ INFO] [Time-limited test] [o.t.u.RegistryAuthLocator]: Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.3.0, configFile: /home/jenkins/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /home/jenkins/.docker/config.json (No such file or directory)
```

**Comment by olukas** [comment]
Failed again on Zulu JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-zulu-jdk8/325/testReport/com.hazelcast.jet.kinesis/KinesisIntegrationTest/com_hazelcast_jet_kinesis_KinesisIntegrationTest/

**Comment by jbartok** [comment]
No idea what's wrong here, I have no clues in the output. Looks like the docker containers didn't start at all, but I'm just guessing here.... Any chance that we could upgrade to using the latest Docker version? Seems to be at least 2 major versions behind.

**Comment by olukas** [comment]
Failed also on `4.4-maintenance` branch: http://jenkins.hazelcast.com/job/jet-oss-maintenance-zulu-jdk8/271/testReport/junit/com.hazelcast.jet.kinesis/KinesisIntegrationTest/com_hazelcast_jet_kinesis_KinesisIntegrationTest/
