### ISSUE TITLE
Failure in JetSqlResultImplTest.when_closed_then_iteratorFails

### ISSUE THREAD

**Issue by jbartok** [hazelcast/hazelcast-jet#2874]
_cdc-commit-offset_ (commit 8faf221455fb9db448961105d79d8fec0d34fa02)

Failed on http://jenkins.hazelcast.com/job/jet-oss-pr-builder/4138/testReport/junit/com.hazelcast.jet.sql.impl/JetSqlResultImplTest/when_closed_then_iteratorFails/

Stacktrace:
```
Expecting code to raise a throwable.
	at com.hazelcast.jet.sql.impl.JetSqlResultImplTest.when_closed_then_iteratorFails(JetSqlResultImplTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
2021-02-05 09:12:45,996 [ INFO] [Time-limited test] [c.h.i.m.i.MetricsConfigHelper]: [LOCAL] [jet] [4.5-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
2021-02-05 09:12:45,997 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Hazelcast Jet 4.5-SNAPSHOT (20210205 - d09f308) starting at [127.0.0.1]:5701
2021-02-05 09:12:45,997 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Based on Hazelcast IMDG version: 4.1.1 (20201222 - 27af558)
2021-02-05 09:12:45,997 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Cluster name: jet
2021-02-05 09:12:45,997 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] 
	o   o   o   o---o o---o o     o---o   o   o---o o-o-o        o o---o o-o-o
	|   |  / \     /  |     |     |      / \  |       |          | |       |
	o---o o---o   o   o-o   |     o     o---o o---o   |          | o-o     |
	|   | |   |  /    |     |     |     |   |     |   |      \   | |       |
	o   o o   o o---o o---o o---o o---o o   o o---o   o       o--o o---o   o
2021-02-05 09:12:45,997 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Copyright (c) 2008-2020, Hazelcast, Inc. All Rights Reserved.
2021-02-05 09:12:46,000 [ INFO] [Time-limited test] [c.h.i.m.i.MetricsConfigHelper]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
2021-02-05 09:12:46,006 [ WARN] [Time-limited test] [c.h.c.CPSubsystem]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2021-02-05 09:12:46,044 [ INFO] [Time-limited test] [c.h.j.i.JetService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Setting number of cooperative threads and default parallelism to 72
2021-02-05 09:12:46,201 [ INFO] [Time-limited test] [c.h.i.d.Diagnostics]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2021-02-05 09:12:46,202 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] [127.0.0.1]:5701 is STARTING
2021-02-05 09:12:46,202 [ INFO] [Time-limited test] [c.h.i.c.ClusterService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - e0fe43d2-59a1-4a32-bb02-272a6b7b3275 this
]

2021-02-05 09:12:46,206 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] [127.0.0.1]:5701 is STARTED
2021-02-05 09:12:46,206 [DEBUG] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-05 09:12:46,211 [ INFO] [Time-limited test] [c.h.i.p.i.PartitionStateManager]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Initializing cluster partition table arrangement...
2021-02-05 09:12:46,216 [ INFO] [hz.stupefied_hofstadter.HealthMonitor] [c.h.i.d.HealthMonitor]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] processors=72, physical.memory.total=377.6G, physical.memory.free=53.9G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=236.5M, heap.memory.free=727.5M, heap.memory.total=964.0M, heap.memory.max=964.0M, heap.memory.used/total=24.53%, heap.memory.used/max=24.53%, minor.gc.count=17, minor.gc.time=932ms, major.gc.count=3, major.gc.time=364ms, load.process=0.00%, load.system=87.50%, load.systemAverage=143.18, thread.count=351, thread.peakCount=929, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=7, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
2021-02-05 09:12:46,229 [DEBUG] [Time-limited test] [c.h.j.s.i.JetSqlBackend]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Before logical opt:
LogicalProject(v=[$0])
  LogicalTableScan(table=[[hazelcast, public, m[projects=[0]]]])

2021-02-05 09:12:46,235 [DEBUG] [Time-limited test] [c.h.j.s.i.JetSqlBackend]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] After logical opt:
FullScanLogicalRel(table=[[hazelcast, public, m[projects=[0]]]])

2021-02-05 09:12:46,236 [DEBUG] [Time-limited test] [c.h.j.s.i.JetSqlBackend]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] After physical opt:
FullScanPhysicalRel(table=[[hazelcast, public, m[projects=[0]]]])

2021-02-05 09:12:46,260 [ INFO] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Starting job 05b0-9ca1-e740-0001 based on submit request
2021-02-05 09:12:46,262 [ INFO] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Didn't find any snapshot to restore for job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001
2021-02-05 09:12:46,262 [ INFO] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Start executing job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001, execution graph in DOT format:
digraph DAG {
	"TestBatch[public.m]" [localParallelism=1];
	"ClientSink" [localParallelism=1];
	"TestBatch[public.m]" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
2021-02-05 09:12:46,262 [DEBUG] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Building execution plan for job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001
2021-02-05 09:12:46,263 [DEBUG] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Built execution plans for job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001
2021-02-05 09:12:46,263 [DEBUG] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.o.InitExecutionOperation]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Initializing execution plan for job 05b0-9ca1-e740-0001, execution 05b0-9ca1-e741-0001 from [127.0.0.1]:5701
2021-02-05 09:12:46,290 [ INFO] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution plan for jobId=05b0-9ca1-e740-0001, jobName='05b0-9ca1-e740-0001', executionId=05b0-9ca1-e741-0001 initialized
2021-02-05 09:12:46,291 [DEBUG] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Init of job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001 was successful
2021-02-05 09:12:46,291 [DEBUG] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Executing job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001
2021-02-05 09:12:46,291 [ INFO] [hz.stupefied_hofstadter.cached.thread-1] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Start execution of job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001 from coordinator [127.0.0.1]:5701
2021-02-05 09:12:46,293 [DEBUG] [hz.stupefied_hofstadter.jet.cooperative.thread-1] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution of job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001 completed
2021-02-05 09:12:46,293 [DEBUG] [ForkJoinPool.commonPool-worker-119] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution of job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001 was successful
2021-02-05 09:12:46,294 [DEBUG] [hz.stupefied_hofstadter.cached.thread-5] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Sending CompleteExecutionOperation for job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001
2021-02-05 09:12:46,294 [DEBUG] [hz.stupefied_hofstadter.cached.thread-5] [c.h.j.i.o.CompleteExecutionOperation]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Completing execution 05b0-9ca1-e741-0001 from caller [127.0.0.1]:5701, error=null
2021-02-05 09:12:46,294 [DEBUG] [hz.stupefied_hofstadter.cached.thread-5] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Completed execution of job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001
2021-02-05 09:12:46,294 [ INFO] [hz.stupefied_hofstadter.cached.thread-5] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution of job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001 completed successfully
	Start time: 2021-02-05T09:12:46.260
	Duration: 00:00:00.034
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
2021-02-05 09:12:46,294 [DEBUG] [hz.stupefied_hofstadter.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] job '05b0-9ca1-e740-0001', execution 05b0-9ca1-e741-0001 is completed
2021-02-05 09:12:46,316 [DEBUG] [hz.stupefied_hofstadter.cached.thread-5] [c.h.j.i.JobRepository]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Job cleanup took 8ms
2021-02-05 09:12:46,324 [ INFO] [Time-limited test] [c.h.j.c.JetTestSupport]: Terminating instanceFactory in JetTestSupport.@After
2021-02-05 09:12:46,328 [ INFO] [Thread-22] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
2021-02-05 09:12:46,328 [ WARN] [Thread-22] [c.h.i.i.Node]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Terminating forcefully...
2021-02-05 09:12:46,329 [ INFO] [Thread-22] [c.h.i.i.Node]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Shutting down connection manager...
2021-02-05 09:12:46,330 [ INFO] [Thread-22] [c.h.i.i.Node]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Shutting down node engine...
2021-02-05 09:12:46,402 [ INFO] [Thread-22] [c.h.i.i.NodeExtension]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Destroying node NodeExtension.
2021-02-05 09:12:46,403 [ INFO] [Thread-22] [c.h.i.i.Node]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Hazelcast Shutdown is completed in 75 ms.
2021-02-05 09:12:46,403 [ INFO] [Thread-22] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after when_closed_then_iteratorFails(com.hazelcast.jet.sql.impl.JetSqlResultImplTest): BuildInfo{version='4.1.1', build='20201222', buildNumber=20201222, revision=27af558, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='4.5-SNAPSHOT', build='20210205', revision='d09f308'}}
Hiccups measured while running test 'when_closed_then_iteratorFails(com.hazelcast.jet.sql.impl.JetSqlResultImplTest):'
09:12:45, accumulated pauses: 186 ms, max pause: 32 ms, pauses over 1000 ms: 0
```

**Comment by viliam-durina** [comment]
Will be fixed in sql-4.2
