### ISSUE TITLE
SQL 4.4 exception when closing query

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2940]
On Jet 4.4, if I query an infinite source and run

```
sqlResult.close();
```

I get lots of these in the server logs

```
Caused by: com.hazelcast.sql.impl.QueryException: Query was cancelled by the user
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:55)
	at com.hazelcast.sql.impl.QueryException.cancelledByUser(QueryException.java:91)
	at com.hazelcast.jet.sql.impl.JetSqlResultImpl.close(JetSqlResultImpl.java:78)
	at com.hazelcast.sql.impl.AbstractSqlResult.close(AbstractSqlResult.java:41)
	at com.hazelcast.sql.impl.state.QueryClientStateRegistry.close(QueryClientStateRegistry.java:178)
	at com.hazelcast.sql.impl.client.SqlCloseMessageTask.call(SqlCloseMessageTask.java:40)
	at com.hazelcast.client.impl.protocol.task.AbstractCallableMessageTask.processMessage(AbstractCallableMessageTask.java:35)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

It should be possible to cleanly end such a query. Cleanly end might simply mean suppressing these exceptions.

**Comment by viliam-durina** [comment]
Did you run multiple queries? In our tests we see one such exception per cancelled query.

**Comment by neilstevenson** [comment]
Yes, I have multiple queries.

But I think the miscount was due to the exception being logged as
```
11:06:09.609 WARN  hz.sad_hodgkin.jet.cooperative.thread-7 c.h.j.i.e.TaskletExecutionService - Exception in ProcessorTasklet{05dc-7c27-1984-0001/ClientSink#0} 
java.lang.RuntimeException: com.hazelcast.sql.impl.QueryException: Query was cancelled by the user
```
and
```
11:06:09.868 ERROR hz.sad_hodgkin.cached.thread-3 com.hazelcast.jet.impl.MasterJobContext - Execution of job '05dc-7c27-1984-0001', execution 05dc-7c27-1985-0001 failed
	Start time: 2021-03-11T11:06:09.353
	Duration: 00:00:00.512
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion 
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{05dc-7c27-1984-0001/ClientSink#0}: java.lang.RuntimeException: com.hazelcast.sql.impl.QueryException: Query was cancelled by the user
```

So I found it twice using string search. None of which will matter if the exception is suppressed.

**Comment by neilstevenson** [comment]
Also, if the query is cancelled, the job shows as failed. It hasn't compleeted but it's not faulty.
