### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: "mapFn" must be serializable

### ISSUE THREAD

**Issue by deepak9764** [hazelcast/hazelcast-jet#3117]
Code:

public class TestDBReader implements CommandLineRunner {

   

  @Autowired
    RebalancingQcDataDBReader rebalancingQcDataDBReader;

    @Autowired
    Parser parser;

    @Autowired
    NormalizerQcResultDBWriter normalizerQcResultDBWriter;

    @Autowired
    JetInstance instance;

    public static void main(String[] args) {
        SpringApplication.run(TestDBReader.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        LocalDate dataDate = LocalDate.of(2021, 5, 28);
        LocalDate asOfDate = LocalDate.of(2021, 5, 28);

        Pipeline p = Pipeline.create();
        //List<IndexRebalancingResult> rebalQcData = rebalancingQcDataDBReader.getRebalQcData(dataDate, asOfDate, 38);

        p.readFrom(TestSources.items(rebalancingQcDataDBReader.getRebalQcData(dataDate, asOfDate, 38)))
                    **.map(indexRebalancingResult -> parser.parse(indexRebalancingResult))**
                    .writeTo(Sinks.logger());

        JobConfig jobConfig = new JobConfig()
                .addClass(TestDBReader.class);

        instance.newJob(p, jobConfig).join();

    }

I am getting below error:
Caused by: java.lang.IllegalArgumentException: "mapFn" must be serializable
	at com.hazelcast.jet.impl.util.Util.checkSerializable(Util.java:188) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.pipeline.ComputeStageImplBase.attachMap(ComputeStageImplBase.java:146) ~[hazelcast-jet-4.3.jar:4.3]
	at com.hazelcast.jet.impl.pipeline.BatchStageImpl.map(BatchStageImpl.java:100) ~[hazelcast-jet-4.3.jar:4.3]
	at com.msci.eqb.qcnormalizerservice.TestDBReader.run(TestDBReader.java:65) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	... 5 common frames omitted
Caused by: java.io.NotSerializableException: com.msci.eqb.qcnormalizerservice.TestDBReader$$EnhancerBySpringCGLIB$$6aa2b97d
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1379) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175) ~[na:na]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[na:na]
	at com.hazelcast.jet.impl.util.Util.checkSerializable(Util.java:186) ~[hazelcast-jet-4.3.jar:4.3]
	... 9 common frames omitted

**Comment by deepak9764** [comment]
what extra step i need to do in **map(indexRebalancingResult -> parser.parse(indexRebalancingResult))** so that i can avoid error 

Caused by: java.io.NotSerializableException: com.msci.eqb.qcnormalizerservice.TestDBReader$$EnhancerBySpringCGLIB$$6aa2b97d

**Comment by deepak9764** [comment]
resolved
