### ISSUE TITLE
No DataSerializerFactory registered for namespace: -10002

### ISSUE THREAD

**Issue by anderschbe** [hazelcast/hazelcast-jet#332]
Trying to get started with hazelcast and hazelcast jet, I tried this fairly simple example: http://jet.hazelcast.org/getting-started/.

Everything works fine till job 0 is to be executed. And then:

```
C:\Users\Abernard\Desktop>java -jar JavaHazelTest-1.0-SNAPSHOT-jar-with-dependencies.jar
Mõr 02, 2017 2:04:31 PM com.hazelcast.jet.impl.config.XmlJetConfigLocator
INFORMATION: Loading hazelcast-jet-default.xml from classpath.
Mõr 02, 2017 2:04:31 PM com.hazelcast.jet.impl.config.XmlJetConfigLocator
INFORMATION: Loading hazelcast-jet-member-default.xml from classpath.
Mõr 02, 2017 2:04:32 PM com.hazelcast.instance.DefaultAddressPicker
INFORMATION: [LOCAL] [jet] [0.3] [3.8] Prefer IPv4 stack is true.
Mõr 02, 2017 2:04:32 PM com.hazelcast.instance.DefaultAddressPicker
INFORMATION: [LOCAL] [jet] [0.3] [3.8] Picked [10.13.52.102]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,local
port=5701], bind any local is true
Mõr 02, 2017 2:04:32 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Hazelcast 3.8 (20170217 - d7998b4) starting at [10.13.52.102]:5701
Mõr 02, 2017 2:04:32 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.
Mõr 02, 2017 2:04:32 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Configured Hazelcast Serialization version : 1
Mõr 02, 2017 2:04:32 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Backpressure is disabled
Mõr 02, 2017 2:04:33 PM com.hazelcast.instance.Node
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Creating MulticastJoiner
Mõr 02, 2017 2:04:33 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Starting Jet 0.3 (20170206 - 5c8738d)
Mõr 02, 2017 2:04:33 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Setting number of cooperative threads and default parallelism to 2
Mõr 02, 2017 2:04:33 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8]
        o   o   o   o---o o---o o     o---o   o   o---o o-o-o        o o---o o-o-o
        |   |  / \     /  |     |     |      / \  |       |          | |       |
        o---o o---o   o   o-o   |     o     o---o o---o   |          | o-o     |
        |   | |   |  /    |     |     |     |   |     |   |      \   | |       |
        o   o o   o o---o o---o o---o o---o o   o o---o   o       o--o o---o   o
Mõr 02, 2017 2:04:33 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.
Mõr 02, 2017 2:04:33 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Starting 2 partition threads
Mõr 02, 2017 2:04:33 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Starting 3 generic threads (1 dedicated for priority tasks)
Mõr 02, 2017 2:04:33 PM com.hazelcast.core.LifecycleService
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] [10.13.52.102]:5701 is STARTING
Mõr 02, 2017 2:04:35 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Cluster version set to 3.8
Mõr 02, 2017 2:04:35 PM com.hazelcast.internal.cluster.impl.MulticastJoiner
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8]


Members [1] {
        Member [10.13.52.102]:5701 - a6188fc1-4b3f-4f3e-b55b-e35959ff0b63 this
}

Mõr 02, 2017 2:04:35 PM com.hazelcast.core.LifecycleService
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] [10.13.52.102]:5701 is STARTED
Mõr 02, 2017 2:04:35 PM com.hazelcast.jet.impl.config.XmlJetConfigLocator
INFORMATION: Loading hazelcast-jet-default.xml from classpath.
Mõr 02, 2017 2:04:35 PM com.hazelcast.jet.impl.config.XmlJetConfigLocator
INFORMATION: Loading hazelcast-jet-member-default.xml from classpath.
Mõr 02, 2017 2:04:36 PM com.hazelcast.instance.DefaultAddressPicker
INFORMATION: [LOCAL] [jet] [0.3] [3.8] Prefer IPv4 stack is true.
Mõr 02, 2017 2:04:36 PM com.hazelcast.instance.DefaultAddressPicker
INFORMATION: [LOCAL] [jet] [0.3] [3.8] Picked [10.13.52.102]:5702, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,local
port=5702], bind any local is true
Mõr 02, 2017 2:04:36 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Hazelcast 3.8 (20170217 - d7998b4) starting at [10.13.52.102]:5702
Mõr 02, 2017 2:04:36 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.
Mõr 02, 2017 2:04:36 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Configured Hazelcast Serialization version : 1
Mõr 02, 2017 2:04:36 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Backpressure is disabled
Mõr 02, 2017 2:04:36 PM com.hazelcast.instance.Node
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Creating MulticastJoiner
Mõr 02, 2017 2:04:36 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Starting Jet 0.3 (20170206 - 5c8738d)
Mõr 02, 2017 2:04:36 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Setting number of cooperative threads and default parallelism to 2
Mõr 02, 2017 2:04:36 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8]
        o   o   o   o---o o---o o     o---o   o   o---o o-o-o        o o---o o-o-o
        |   |  / \     /  |     |     |      / \  |       |          | |       |
        o---o o---o   o   o-o   |     o     o---o o---o   |          | o-o     |
        |   | |   |  /    |     |     |     |   |     |   |      \   | |       |
        o   o o   o o---o o---o o---o o---o o   o o---o   o       o--o o---o   o
Mõr 02, 2017 2:04:36 PM com.hazelcast.jet.impl.JetService
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Copyright (c) 2008-2017, Hazelcast, Inc. All Rights Reserved.
Mõr 02, 2017 2:04:36 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Starting 2 partition threads
Mõr 02, 2017 2:04:36 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Starting 3 generic threads (1 dedicated for priority tasks)
Mõr 02, 2017 2:04:36 PM com.hazelcast.core.LifecycleService
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] [10.13.52.102]:5702 is STARTING
Mõr 02, 2017 2:04:36 PM com.hazelcast.internal.cluster.impl.MulticastJoiner
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Trying to join to discovered node: [10.13.52.102]:5701
Mõr 02, 2017 2:04:36 PM com.hazelcast.nio.tcp.InitConnectionTask
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Connecting to /10.13.52.102:5701, timeout: 0, bind-any: true
Mõr 02, 2017 2:04:36 PM com.hazelcast.nio.tcp.SocketAcceptorThread
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Accepting socket connection from /10.13.52.102:58605
Mõr 02, 2017 2:04:36 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Established socket connection between /10.13.52.102:5701 and /10.13.5
2.102:58605
Mõr 02, 2017 2:04:36 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Established socket connection between /10.13.52.102:58605 and /10.13.
52.102:5701
Mõr 02, 2017 2:04:43 PM com.hazelcast.internal.cluster.ClusterService
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8]

Members [2] {
        Member [10.13.52.102]:5701 - a6188fc1-4b3f-4f3e-b55b-e35959ff0b63 this
        Member [10.13.52.102]:5702 - 10a41f14-19e8-4577-b496-c722148a7351
}

Mõr 02, 2017 2:04:52 PM com.hazelcast.system
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Cluster version set to 3.8
Mõr 02, 2017 2:04:52 PM com.hazelcast.internal.cluster.ClusterService
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8]

Members [2] {
        Member [10.13.52.102]:5701 - a6188fc1-4b3f-4f3e-b55b-e35959ff0b63
        Member [10.13.52.102]:5702 - 10a41f14-19e8-4577-b496-c722148a7351 this
}

Mõr 02, 2017 2:04:53 PM com.hazelcast.core.LifecycleService
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] [10.13.52.102]:5702 is STARTED
Mõr 02, 2017 2:04:53 PM com.hazelcast.internal.partition.impl.PartitionStateManager
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Initializing cluster partition table arrangement...
Mõr 02, 2017 2:04:53 PM com.hazelcast.jet.impl.operation.ExecuteJobOperation
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Start executing job 0.
Mõr 02, 2017 2:04:53 PM com.hazelcast.jet.impl.operation.InitOperation
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Initializing execution plan for job 0 from [10.13.52.102]:5701.
Mõr 02, 2017 2:04:53 PM com.hazelcast.jet.impl.operation.InitOperation
INFORMATION: [10.13.52.102]:5702 [jet] [0.3] [3.8] Initializing execution plan for job 0 from [10.13.52.102]:5701.
Mõr 02, 2017 2:04:53 PM com.hazelcast.jet.impl.operation.InitOperation
SCHWERWIEGEND: [10.13.52.102]:5702 [jet] [0.3] [3.8] No DataSerializerFactory registered for namespace: -10002
com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -100
02
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.
java:134)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103
)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)

        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.
java:184)
        at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoa
dedObject.java:61)
        at com.hazelcast.jet.impl.operation.InitOperation.lambda$readInternal$1(InitOperation.java:71)
        at com.hazelcast.jet.impl.operation.InitOperation.run(InitOperation.java:49)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)

Mõr 02, 2017 2:04:54 PM com.hazelcast.jet.impl.operation.ExecuteJobOperation
INFORMATION: [10.13.52.102]:5701 [jet] [0.3] [3.8] Execution of job 0 completed in 482ms.
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory reg
istered for namespace: -10002
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.
java:134)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103
)
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)

        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.
java:184)
        at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoa
dedObject.java:61)
        at com.hazelcast.jet.impl.operation.InitOperation.lambda$readInternal$1(InitOperation.java:71)
        at com.hazelcast.jet.impl.operation.InitOperation.run(InitOperation.java:49)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
        at ------ submitted from ------.(Unknown Source)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.jav
a:75)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
        at com.hazelcast.jet.stream.impl.StreamUtil.executeJob(StreamUtil.java:68)
        at com.hazelcast.jet.stream.impl.collectors.HazelcastMergingMapCollector.collect(HazelcastMergingMapCollector.ja
va:75)
        at com.hazelcast.jet.stream.impl.collectors.HazelcastMergingMapCollector.collect(HazelcastMergingMapCollector.ja
va:38)
        at com.hazelcast.jet.stream.impl.pipeline.AbstractPipeline.collect(AbstractPipeline.java:221)
        at be.andersch.javahazeltest.WordCount.main(WordCount.java:48)
```
I checked all sources I could find for similar errors, but couldn't find any explanation for the failing serialization. Jar is attached.
[JavaHazelTest-1.0-SNAPSHOT-jar-with-dependencies.zip](https://github.com/hazelcast/hazelcast-jet/files/813885/JavaHazelTest-1.0-SNAPSHOT-jar-with-dependencies.zip)

**Comment by cangencer** [comment]
This seems to be due to shading, the resource files in the hazelcast-jet.jar need to be appended with the ones in hazelcast.jar. Can you try without shading? Or use this in your shade configuration:
http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

**Comment by anderschbe** [comment]
The plugin didn't work, looking into that shading issue.

**Comment by anderschbe** [comment]
OK got it solved (though not completely sorted out. It seems there was some weird issue with the shading as you suggested.

**Comment by cangencer** [comment]
@anderschbe have you resolved this issue now? If so, I will close it.

**Comment by anderschbe** [comment]
Thought I had resolved it. BUT: fter removing all shading I get this:

INFO: [192.168.3.48]:5701 [jet] [0.3] [3.8-RC1] Execution of job 0 completed in 1503ms.
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -10
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:136)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:104)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:106)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.collection.impl.collection.AbstractCollectionProxyImpl.invoke(AbstractCollectionProxyImpl.java:229)
	at com.hazelcast.collection.impl.list.ListProxyImpl.get(ListProxyImpl.java:67)
	at com.hazelcast.jet.stream.impl.ListDecorator.get(ListDecorator.java:146)
	at com.hazelcast.jet.stream.impl.terminal.Reducer.execute(Reducer.java:113)
	at com.hazelcast.jet.stream.impl.terminal.Reducer.reduce(Reducer.java:88)
	at com.hazelcast.jet.stream.impl.pipeline.AbstractPipeline.reduce(AbstractPipeline.java:200)
	at com.hazelcast.jet.stream.DistributedStream.reduce(DistributedStream.java:337)
	at com.hazelcast.jet.stream.impl.pipeline.AbstractPipeline.min(AbstractPipeline.java:227)
	at be.andersch.javadao.HazelProc.processLogs(HazelProc.java:42)
	at be.andersch.javadao.LogCreator.main(LogCreator.java:69)

Seems it's not connected to shading, but rather some problem in 3.8-RC1, as the test-job should be solved in <10ms.

**Comment by anderschbe** [comment]
Little update: I double checked for everything I could come up with that could cause it.

- java version conflicts can be ruled out
- lacking hazelcast dependency ruled out as well
- replacing the Comparator with a Distributed.Comparator didn't work either

The app works out of netbeans, but not as standalone. So it looks like some lacking dependency, but I can't figure out what isn't added in.

**Comment by anderschbe** [comment]
OK, found a workaround. The problems seems to be in the 3.8-RC1 Hazelcast interacting with maven in netbeans.

I originally had only a call to Hazelcast Jet in my pom, which led to 3.8-RC1 being used. As soon as I changed my POM to:

        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>3.8</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.hazelcast.jet</groupId>
            <artifactId>hazelcast-jet</artifactId>
            <version>0.3</version>
        </dependency>

it worked flawlessly. I have no clue WHAT is causing the trouble, but at least i can continue testing.

**Comment by anderschbe** [comment]
And as soon as I started my Instanziators... No DataSerializerFactory registered for namespace: -10002 again
Will look into it somemore first thing tomorrow morning.

Q: do I need to define a Hazelcast config if all I intend to do is using the distributed stream api (no DAG or anything yet)?

Q2: do the secondary instances need to import the Object that is to be transfered via the maps? Or does Jet handle that by itself?

**Comment by cangencer** [comment]
@anderschbe you don't need to define a Hazelcast config, it will use a default configuration.

Could you clarify the second question?

**Comment by anderschbe** [comment]
I'll try. Keep in mind though that I'm just a rookie and still trying to grasp everything.

To test the way Hazelcast Jet works I attempted to run the class you can find under https://github.com/anderschbe/clusterbench/blob/master/src/main/java/be/andersch/javadao/Instantiator.java as a standalone. Basically the equivalent of the Spark master/slave setup. 

Originally the Instantiator class was in it's own separate package, I just moved it to the main package to a) make it easily available here and b) in the hopes of solving the problems in this issue. Couldn't test it yet though (first thing tomorrow morning).

As said, I'm still learning the ropes of Hazelcast,  thus I have to poke around in the dark to find the reasons for the error. My guess was, that the Instantiator instances have no representation of the LogPojo class, which could explain the trouble with the DataSerializerFactory.

So my question is basically: assuming I have two JVMs, each with embedded Jet instances (that do connect just fine). And I get a Map<LogPojo> from jet in JVM1 (where you run an app that does define LogPojo). Do I need to have a representation of LogPojo in the app in JVM2 as well (using an import or such), or is Jet able to transfer that representation (and thus a mechanism of deserialization) together with the distributed map?

Again, might sound like a dumb question for you, but as said, I've barely started dipping my toes into the whole distributed processing thingy yet.

**Comment by anderschbe** [comment]
OK tested it.

I started my clusterbench on one node as well as the Instantiator on a separate node. The Instantiator is now in the same project and package as the clusterbench, thus should have access to the LogPojo class. And still:

		Members [2] {
			Member [192.168.3.58]:5701 - b115e6e8-9b9c-4a70-9ee9-cd6422511b1b this
			Member [192.168.3.48]:5701 - a9afcd4a-0d8a-4ed6-8e96-4100c9499adf
		}

		Mar 16, 2017 8:17:15 AM com.hazelcast.internal.partition.impl.PartitionStateManager
		INFO: [192.168.3.58]:5701 [jet] [0.3] [3.8] Initializing cluster partition table arrangement...
		Mar 16, 2017 8:18:53 AM com.hazelcast.jet.impl.operation.InitOperation
		INFO: [192.168.3.58]:5701 [jet] [0.3] [3.8] Initializing execution plan for job 0 from [192.168.3.48]:5701.
		Mar 16, 2017 8:18:53 AM com.hazelcast.jet.impl.operation.InitOperation
		SEVERE: [192.168.3.58]:5701 [jet] [0.3] [3.8] No DataSerializerFactory registered for namespace: -10002
		com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: -10002
			at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:134)
			at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103)
			at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49)
			at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
			at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
			at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:61)
			at com.hazelcast.jet.impl.operation.InitOperation.lambda$readInternal$1(InitOperation.java:71)
			at com.hazelcast.jet.impl.operation.InitOperation.run(InitOperation.java:49)
			at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186)
			at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
			at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
			at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)

**Comment by cangencer** [comment]
This exception: `No DataSerializerFactory registered for namespace: -10002` is probably caused by some shading issue. When you shade your JARs, you need to make sure that the resource files are appended. The error you are getting isn't related to LogPojo, but it's happening because one of the resources file from Hazelcast is overriding the one from Jet.

**Comment by anderschbe** [comment]
The weird part is: I do not have shading activated in the POM.

**Comment by anderschbe** [comment]
OK, problem definitely comes from "fat-jar shading" of the internal dependencies of Jet to Hazelcast. Lets go at it scientifically, and taking both Jet as well as Hazelcast as black boxes (as they are for me atm):

- if I run both the Instantiator and the Main App in Netbeans (no fat jar) everything works fine, independently on which and how the Hazelcast dependency is used

Now there are 4 options for a fat-jar:

1. one built with a POM including Jet0.3 only, thus integrating Hazelcast 3.8-RC1
2. one built with a POM with Hazelcast 3.8 dependency called BEFORE Jet0.3
3. one built with a POM with Hazelcast 3.8 dependency called AFTER Jet0.3
4. one built with a POM including Jet0.3 only, but including maven-shade-plugin

The following errors occur:

1. No DataSerializerFactory registered for namespace: -10
2. No DataSerializerFactory registered for namespace: -10002
3. No DataSerializerFactory registered for namespace: -10
4. Works, but DIDN'T work when Apache Flink was part of the dependencies

Would it be possible to circumvent this issue in Jet 0.4? So that rookies like me do not run into such troubles right of the start? Would probably help with making HCJ popular. ;)

**Comment by anderschbe** [comment]
Problem solved, thank you.
