### ISSUE TITLE
ClassNotFoundException from client side IStreamMap with filter

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#333]
If this code is run from a client
```
		this.jetInstance.getMap("emptyMap")
			.stream()
			.filter(entry -> (entry.getKey() != null))
			.collect(DistributedCollectors.toIMap());
```
an exception is thrown, ClassNotFoundException for the client's main class.

Run from the client without the filter, or run from the server, all is ok

**Comment by neilstevenson** [comment]
Example stacktrace from client,
```
11:10:43.301 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
 java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:779) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:747) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	at issue333.Issue333.main(Issue333.java:27) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [client-submit-dag.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [client-submit-dag.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [client-submit-dag.jar:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [client-submit-dag.jar:0.0.1-SNAPSHOT]
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: issue333.Issue333
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:106) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:85) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.read(CustomClassLoadedObject.java:54) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.Vertex.readData(Vertex.java:171) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.jet.DAG.readData(DAG.java:386) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:61) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.client.JetExecuteJobMessageTask.prepareOperation(JetExecuteJobMessageTask.java:43) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.client.JetExecuteJobMessageTask.processMessage(JetExecuteJobMessageTask.java:49) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103) ~[hazelcast-3.8.jar!/:3.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-3.8.jar!/:3.8]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74) ~[hazelcast-client-3.8.jar!/:3.8]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31) ~[hazelcast-client-3.8.jar!/:3.8]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.jet.impl.JetClientInstanceImpl$ExecutionFuture.get(JetClientInstanceImpl.java:177) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.JetClientInstanceImpl$ExecutionFuture.get(JetClientInstanceImpl.java:132) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.stream.impl.StreamUtil.executeJob(StreamUtil.java:62) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.stream.impl.reducers.AbstractSinkReducer.reduce(AbstractSinkReducer.java:44) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.stream.impl.pipeline.AbstractPipeline.collect(AbstractPipeline.java:239) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at issue333.Issue333.run(Issue333.java:46) ~[classes!/:0.0.1-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:776) ~[spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
	... 14 more
Caused by: java.lang.ClassNotFoundException: issue333.Issue333
	at com.hazelcast.jet.impl.deployment.JetClassLoader.loadClass(JetClassLoader.java:62) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.deployment.JetClassLoader.loadClass(JetClassLoader.java:40) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:146) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:120) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:522) ~[hazelcast-3.8.jar!/:3.8]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readClass(ObjectInputStream.java:1678) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1518) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1919) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1919) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1919) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1919) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1919) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535) ~[?:1.8.0_121]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422) ~[?:1.8.0_121]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:104) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:85) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.read(CustomClassLoadedObject.java:54) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.Vertex.readData(Vertex.java:171) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.jet.DAG.readData(DAG.java:386) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:61) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.client.JetExecuteJobMessageTask.prepareOperation(JetExecuteJobMessageTask.java:43) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.jet.impl.client.JetExecuteJobMessageTask.processMessage(JetExecuteJobMessageTask.java:49) ~[hazelcast-jet-0.3.1-SNAPSHOT.jar!/:0.3.1-SNAPSHOT]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103) ~[hazelcast-3.8.jar!/:3.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-3.8.jar!/:3.8]
```

**Comment by cangencer** [comment]
This is because the server doesn't have access the code for the filter, which is a lambda. We currently do not support shipping bytecode as part of java.util.stream jobs.

**Comment by neilstevenson** [comment]
What's confusing to the user is the `ClassNotFoundException` appears on the client, but it's a client-side class which is cited.

**Comment by cangencer** [comment]
It's possible to add config to j.u.s since #359 , so closing this issue.
