### ISSUE TITLE
jet requires JCache - 0.3.2-SNASHOT

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast-jet#366]
last updated snapshot requires jcache `20170328042018`

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/cache/Cache$Entry
	at com.hazelcast.jet.impl.execution.init.JetSerializerHook$CacheEntry.getSerializationType(JetSerializerHook.java:148)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.load(SerializerHookLoader.java:63)
	at com.hazelcast.internal.serialization.impl.SerializerHookLoader.<init>(SerializerHookLoader.java:55)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.registerSerializerHooks(DefaultSerializationServiceBuilder.java:282)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:223)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:49)
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:151)
	at com.hazelcast.instance.Node.<init>(Node.java:201)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:163)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:130)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:176)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:126)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
	at com.hazelcast.jet.Jet.newJetInstance(Jet.java:49)
	at com.hazelcast.jet.Jet.newJetInstance(Jet.java:58)
	at com.hazelcast.techops.jet.training.essentials.MyJetInstance.main(MyJetInstance.java:19)
Caused by: java.lang.ClassNotFoundException: javax.cache.Cache$Entry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
```

**Comment by gurbuzali** [comment]
fix is on the way https://github.com/hazelcast/hazelcast-jet/pull/365
