### ISSUE TITLE
Startup fails in a Spring boot application.

### ISSUE THREAD

**Issue by manishonline** [hazelcast/hazelcast-jet#483]
I am trying to start Jet as a simple spring boot application with no other dependencies.

Added a Bean that creates a Jet instance with default configuration.

>  @Bean
    public JetInstance getJetInstance(){
        return Jet.newJetInstance();
    }

Jet version is 0.4

Below is the error:
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.hazelcast.jet.impl.JetInstanceImpl] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:656) ~[spring-core-5.0.0.RC2.jar:5.0.0.RC2]

Caused by: java.lang.ClassNotFoundException: javax.cache.Cache
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_74]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
	... 47 common frames omitted

**Comment by viliam-durina** [comment]
The `javax.cache:cache-api` dependency is declared with `<scope>provided</scope>` in Jet. Implementation is written in a way that it's presence is not required by the JVM, unless the cache functionality is actually used.

However Spring creates proxy objects around classes, which force you to have the dependency on the classpath. Add a dependency like this and it should resolve your issue:

    <dependency>
        <groupId>javax.cache</groupId>
        <artifactId>cache-api</artifactId>
        <version>1.0.0</version>
    </dependency>

**Comment by cangencer** [comment]
We should have the same approach as IMDG here: to add an extra level of indirection via the `getCacheManager()`

**Comment by manishonline** [comment]
Adding javax dependency fixed the issue. But somehow this issue doesn't come when just Hazelcast is instantiated in the exactly same way.
