### ISSUE TITLE
Issue while running DAG job

### ISSUE THREAD

**Issue by manishonline** [hazelcast/hazelcast-jet#491]
Hazelcast Jet Version : 0.4
Below is the exception stacktrace
```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.impl.AggregateOperationImpl.accumulateItemF of type com.hazelcast.jet.function.DistributedBiConsumer in instance of com.hazelcast.jet.impl.AggregateOperationImpl
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:61) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:272) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.read(CustomClassLoadedObject.java:54) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.execution.init.VertexDef.readData(VertexDef.java:115) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:599) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.util.Util.readList(Util.java:137) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.readData(ExecutionPlan.java:181) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:155) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:103) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:49) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:63) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.operation.InitOperation.lambda$readInternal$1(InitOperation.java:71) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.operation.InitOperation.run(InitOperation.java:49) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:186) [hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401) [hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115) [hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) [hazelcast-jet-0.4.jar:0.4]
Caused by: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field com.hazelcast.jet.impl.AggregateOperationImpl.accumulateItemF of type com.hazelcast.jet.function.DistributedBiConsumer in instance of com.hazelcast.jet.impl.AggregateOperationImpl
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133) ~[na:1.8.0_74]
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2006) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1707) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1707) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1707) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1345) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351) ~[na:1.8.0_74]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371) ~[na:1.8.0_74]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:106) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject$Serializer.read(CustomClassLoadedObject.java:87) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-jet-0.4.jar:0.4]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:266) ~[hazelcast-jet-0.4.jar:0.4]
	... 23 common frames omitted

```

DAG Code:
`    private static DAG buildDagForSumPVByBook(){
        DAG dag = new DAG();
        Vertex readCache = dag.newVertex("readCache", peekOutput(Sources.readMap(ResultFileReader.RESULT_CACHE)));
        Vertex transform = dag.newVertex("transform", peekInput(Processors.accumulateByKey((Map.Entry<String,FlatResult> e) ->e.getValue().getBook(), summingDouble((Map.Entry<String,FlatResult> e) ->e.getValue().getUnitResultPV()))));
        Vertex combine = dag.newVertex("combine", Processors.combineByKey(AggregateOperations.summingDouble(value -> (Double)value)));
        Vertex writeResult = dag.newVertex("writeResult",Sinks.writeMap("pvByBook"));
        dag.edge(Edge.from(readCache).to(transform).partitioned(DistributedFunctions.entryKey(),Partitioner.HASH_CODE))
                .edge(Edge.from(transform).to(combine).distributed().partitioned(DistributedFunctions.entryKey(),Partitioner.HASH_CODE))
                .edge(Edge.from(combine).to(writeResult));
        return dag;
    }`

Client Code:

`public class JetClient2 implements Serializable{

    public static void main(String[] args) {

        JetConfig jetConfig = new JetConfig();
        jetConfig.getHazelcastConfig().getGroupConfig().setName("hz-oneview-results").setPassword("s3c3rt");
        //jetConfig.getHazelcastConfig().getSerializationConfig().addDataSerializableFactoryClass(ResultsDataSerializableFactory.ID,ResultsDataSerializableFactory.class);
        jetConfig.getHazelcastConfig().getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        jetConfig.getHazelcastConfig().getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true).addMember("127.0.0.1");
        JetInstance jetInstance = Jet.newJetInstance(jetConfig);

        ClientConfig clientConfig = new ClientConfig();
        clientConfig.getGroupConfig().setName("hz-oneview-results").setPassword("s3c3rt");
        //clientConfig.getSerializationConfig().addDataSerializableFactoryClass(ResultsDataSerializableFactory.ID,ResultsDataSerializableFactory.class);
        clientConfig.getNetworkConfig().addAddress("localhost:5701");

        // JetInstance jetInstance = Jet.newJetClient(clientConfig);
        //HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);

        log.info("Cache {} size {}", ResultFileReader.RESULT_CACHE, jetInstance.getMap(ResultFileReader.RESULT_CACHE).size());
        log.info("First Entry{}",jetInstance.getMap(ResultFileReader.RESULT_CACHE).entrySet().iterator().next());
             try {
                 JobConfig conf = new JobConfig();
                 conf.addClass(JetClient2.class);
                // conf.addClass(SumPVByBookDAG.class);
                 //Job job = jetInstance.newJob(new SumPVByBookDAG(ResultFileReader.RESULT_CACHE,"pvByBook",clientConfig));
                 Job job = jetInstance.newJob(buildDagForSumPVByBook());
                 //log.info("JobId {}",job);
                 Future<Void> future = job.execute();
                 Void voidF = future.get();
                 jetInstance.getMap("pvByBook").forEach((k,v) -> System.out.println(k +" "+ v));
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        } finally {
            jetInstance.shutdown();
            //client.shutdown();
        }

    }

    private static DAG buildDagForCountByProdType(ClientConfig clientConfig){
        DAG dag = new DAG();
        Vertex readCache = dag.newVertex("readCache", Sources.readMap(ResultFileReader.RESULT_CACHE));
        Vertex transform = dag.newVertex("transform", Processors.accumulateByKey((Map.Entry<String,FlatResult> e) ->e.getValue().getResultProductType(), counting()));
        Vertex combine = dag.newVertex("combine", Processors.combineByKey(counting()));
        Vertex writeResult = dag.newVertex("writeResult",Sinks.writeMap("countByProdType",clientConfig));
        dag.edge(Edge.from(readCache).to(transform).partitioned(DistributedFunctions.entryKey(),Partitioner.HASH_CODE).distributed())
                .edge(Edge.from(transform).to(combine).distributed().partitioned(DistributedFunctions.entryKey(),Partitioner.HASH_CODE))
                .edge(Edge.from(combine).to(writeResult));
        return dag;
    }

    private static DAG buildDagForSumPVByBook(){
        DAG dag = new DAG();
        Vertex readCache = dag.newVertex("readCache", peekOutput(Sources.readMap(ResultFileReader.RESULT_CACHE)));
        Vertex transform = dag.newVertex("transform", peekInput(Processors.accumulateByKey((Map.Entry<String,FlatResult> e) ->e.getValue().getBook(), summingDouble((Map.Entry<String,FlatResult> e) ->e.getValue().getUnitResultPV()))));
        Vertex combine = dag.newVertex("combine", Processors.combineByKey(AggregateOperations.summingDouble(value -> (Double)value)));
        Vertex writeResult = dag.newVertex("writeResult",Sinks.writeMap("pvByBook"));
        dag.edge(Edge.from(readCache).to(transform).partitioned(DistributedFunctions.entryKey(),Partitioner.HASH_CODE))
                .edge(Edge.from(transform).to(combine).distributed().partitioned(DistributedFunctions.entryKey(),Partitioner.HASH_CODE))
                .edge(Edge.from(combine).to(writeResult));
        return dag;
    }

    private static DAG buildMapDumpDag(ClientConfig clientConfig){
        DAG dag = new DAG();
        Vertex readCache = dag.newVertex("readCache", Sources.readMap(ResultFileReader.RESULT_CACHE,clientConfig));
        Vertex sink = dag.newVertex("sink",  peekInput(Sinks.writeFile("C:\\work")));
        dag.edge(Edge.between(readCache,sink));
        return dag;
    }
}`

**Comment by manishonline** [comment]
Is there anything wrong with either the configuration or the way Job is run?

**Comment by cangencer** [comment]
First of all `JetClient2` shouldn't be marked as serializable. You also seem to have a lambda which can't be deserialized on the server. It could be that some types are missing on the server classpath?

**Comment by manishonline** [comment]
Thanks for pointing out the error. I'll make amends as per your suggestion and try again. Strange thing is same job used to run fine until a day ago when I moved DAG building from the local method to a class.

Could it be because JetClient2 was a cluster member and as Job ran on itself, it used to work?

**Comment by cangencer** [comment]
One thing to try is building a JAR with your project, and submitting the whole JAR as part of running the job using the jet-submit.sh script. See the documentation at http://docs.hazelcast.org/docs/jet/0.4/manual/Best_Practices.html#page_Packaging+the+Job

This will make sure all your dependencies get deployed without doing any specific configuration.

**Comment by viliam-durina** [comment]
Here is good description of the issue: https://stackoverflow.com/a/28367602/952135
The `JetClient2` class is probably missing on classpath.

**Comment by manishonline** [comment]
Thanks for all the hints. My issue is fine now. Regarding classpath, my understanding was of distributed executors and I assumed jet would be working in the same way.
