### ISSUE TITLE
KafkaReader doesn't close cleanly when cancelling job

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#589]
When reading from Kafka and cancelling the job, this exception is sometimes thrown:

```55:26,612 [10.0.1.3]:5702 [jet] [0.5-SNAPSHOT] job ff48-7219-d4ca-c9a5, execution c12a-9c40-7ed7-86b2 encountered an exception in ProcessorSupplier.complete(), ignoring it
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1673)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1571)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1549)
	at com.hazelcast.jet.impl.connector.kafka.StreamKafkaP.close(StreamKafkaP.java:186)
	at com.hazelcast.jet.core.CloseableProcessorSupplier.complete(CloseableProcessorSupplier.java:83)
	at com.hazelcast.jet.impl.execution.ExecutionContext.lambda$complete$2(ExecutionContext.java:151)```

**Comment by viliam-durina** [comment]
The culprit is in `JobExecutionService.cancelAndComplete`:
```
            exeCtx.cancel().whenComplete(withTryCatch(logger, (r, e) -> {
                long executionId = exeCtx.getExecutionId();
                logger.fine(message);
                completeExecution(executionId, t);
            }));
```
Immediately after the future is canceled, we go on to call `completeExecution`, which calls `ProcessorSupplier.complete()`. We should wait until the tasklets really complete and call PS.complete after that.

**Comment by gurbuzali** [comment]
We have a `completionLatch` field in `JobFuture`. We can wait(sleep) for that to count down to 0 before returning the `cancel` method.
```
        @Override
        public boolean cancel(boolean mayInterruptIfRunning) {
            boolean cancelled = super.cancel(mayInterruptIfRunning);
            if (cancelled) {
                blockingFutures.forEach(f -> f.cancel(true)); // CompletableFuture.cancel ignores the flag
                //wait for tasklets to complete
                while (completionLatch.get() != 0) {
                    parkNanos(10);
                }
            }
            return cancelled;
        }
```

**Comment by cangencer** [comment]
Calling .cancel() should not block. My idea was to have a separate future which is only completed when the tasklets are completed, similar to the `doneFuture` we introduced for the invocation system.
