### ISSUE TITLE
Serialization Exception with partionkey.

### ISSUE THREAD

**Issue by parthdwe** [hazelcast/hazelcast-jet#643]
![img_01122017_113904_0](https://user-images.githubusercontent.com/34028771/33614678-12d32f06-d9fe-11e7-98a9-beeb5dce0bb0.png)

I create a simple dag design with partion key(DistributedFunctions.entryKey()) and when i run the jet instance i am facing this exception.
How can i fix this exception?
Thanks!

**Comment by cangencer** [comment]
It seems like Jet doesn't access to your custom classes. You need to make sure all the classes and lambdas used in the job are accessible to Jet cluster, either by adding them to your Jet classpath or adding them to JobConfig.

**Comment by parthdwe** [comment]
I tried with Adding class in job config() but still i am getting the error with "-Error: Failed to serialize 'com.hazelcast.jet.core.DAG'".
Same code is working with hazelcast jet 0.4 version but not in hazelcast jet 0.5 version.
i am trying to run my code with uber jar and is not working but same time i am trying to run in eclipse java application it's working absolutely fine.
can you please help me out?

**Comment by viliam-durina** [comment]
Adding your code with all your lambdas would help us lot, we won't have to guess. Also, add exceptions as text and not as an image, with full stack trace. I don't see the stack trace for the IOException in the image. 

Also make sure you have recent JDK as there was [bug](https://bugs.openjdk.java.net/browse/JDK-8161257) related to lambda deserialization with similar stack trace.

**Comment by parthdwe** [comment]
-Error: Failed to serialize 'com.hazelcast.jet.core.DAG'
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.core.DAG'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:155)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:122)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:110)
	at com.hazelcast.jet.impl.JetInstanceImpl$SubmittedJobImpl.sendJoinRequest(JetInstanceImpl.java:133)
	at com.hazelcast.jet.impl.AbstractJobImpl.init(AbstractJobImpl.java:68)
	at com.hazelcast.jet.impl.AbstractSubmittedJobImpl.init(AbstractSubmittedJobImpl.java:77)
	at com.hazelcast.jet.impl.JetInstanceImpl.newJob(JetInstanceImpl.java:77)
	at picocli.CommandLine.call(CommandLine.java:533)
	at picocli.CommandLine.call(CommandLine.java:497)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.core.Vertex'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:252)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:370)
	at com.hazelcast.jet.core.DAG.writeData(DAG.java:307)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:201)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:152)
	... 12 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:252)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:370)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.write(CustomClassLoadedObject.java:50)
	at com.hazelcast.jet.core.Vertex.writeData(Vertex.java:186)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:201)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:50)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:250)
	... 18 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:485)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:248)

This is my full stack trace.
i am using java 8 but as early it's working fine i just upgrade the hazelcast jet to 0.5.
when i am trying to run with uber jar it's show my above error in console.

**Comment by viliam-durina** [comment]
This is different error.

Anyway, I still would like to see the code where you create the DAG or pipeline.

**Comment by parthdwe** [comment]
[generator.zip](https://github.com/hazelcast/hazelcast-jet/files/1546787/generator.zip)

Please download the Zip file and follow the below steps for reproduce the issue.
Steps:
1.Extract file and import it in Eclipse.
2.Run the setup file.
3.Perform maven clean install from eclipse.
4.Run the generator-0.1-jar-with-dependencies.jar with command line which is available in build/server directory.

Note: 
We can run the project from the eclipse it's working fine but when we trying to run the uber jar it's showing the exception.

**Comment by viliam-durina** [comment]
Now I see the problem: You used the `maven-assembly-plugin`, which cannot merge files. The file `META-INF/services/com.hazelcast.SerializerHook` from multiple jars got overwritten. This setup is not supported. You should start the Jet cluster separately (using the scripts in `bin` directory) and then submit your jar to execution, as [described here](http://docs.hazelcast.org/docs/jet/0.5.1/manual/Work_with_Jet/Practical_Considerations.html#page_Submit+a+Job+from+the+Command+Line).

**Comment by parthdwe** [comment]
Thanks for quick reply Viliam, Much appreciated. 

I am wondering when you said "this setup is not supported", do you mean we can not run Hazelcast-jet project as uber jar? Or It is not recommended?

**Comment by viliam-durina** [comment]
It's not recommended, you certainly can do it, but you'll need to use `maven-shade-plugin`, which is able to merge the services files.

What's your use case actually? Jet is designed to run in cluster, that is on multiple machines. With the approach you tried you won't be able to start multiple Jet members - each jar will start jet member and also start the job.

For development just start the job from your IDE or start few Jet members using the provided scripts and then submit your job in a much smaller jar.

**Comment by parthdwe** [comment]
Thanks,

I have multiple data stream of various frequency between 1 to 400hz. I want to regularize these data at fixed frequency (lets say at 100hz) for now. I want run these in multiple jet instances to distribute processing load. At the same time, I also want to prove that when I run the process in multiple instance it generate the same result as compare to single jet instance more effectively. 

Based on your explanation what I understood is, 
We need to start jet instance in multiple nodes using submit-jet script and then submit the job in any of the node from the cluster, is that correct? 
But if we use UBER jar to start jet instances on multiple nodes then it will not be possible?

**Comment by viliam-durina** [comment]
You understand it correctly (except that the script is `start-jet`).

**Comment by parthdwe** [comment]
Thanks Viliam for your support!
