### ISSUE TITLE
Element supports custom serialization but array is not serializable

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#679]
`Tuple2` doesn't implement `java.io.Serializable`, but has serialization hook. The same is true for `java.util.Map.Entry`, but `Entry[]` is serializable.

            IList<Tuple2[]> tmp = inst[0].getList("test");
            tmp.add(new Tuple2[]{tuple2(1, 2)});

Eception:

    Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.datamodel.Tuple2'
        at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:155)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:122)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:110)
        at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:334)
        at com.hazelcast.collection.impl.collection.AbstractCollectionProxyImpl.add(AbstractCollectionProxyImpl.java:101)
        at com.hazelcast.jet.stream.impl.ListDecorator.add(ListDecorator.java:106)
        at BatchMapping.main(BatchMapping.java:72)
    Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize '[Lcom.hazelcast.jet.datamodel.Tuple2;'
        at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:252)
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:370)
        at com.hazelcast.jet.datamodel.DataModelSerializerHooks$Tuple2Hook$1.write(DataModelSerializerHooks.java:139)
        at com.hazelcast.jet.datamodel.DataModelSerializerHooks$Tuple2Hook$1.write(DataModelSerializerHooks.java:135)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:152)
        ... 6 more
    Caused by: java.io.NotSerializableException: com.hazelcast.jet.datamodel.Tuple2
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:242)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:250)
        ... 11 more

**Comment by viliam-durina** [comment]
Related issue: hazelcast/hazelcast#634.
Workaround is to use `Object[]{tuple2(...)}`
