### ISSUE TITLE
com.hazelcast.jet.impl.connector.HazelcastConnectorTest.test_defaultFilter_mapJournal

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#735]
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/Jet/lastCompletedBuild/com.hazelcast.jet$hazelcast-jet-core/testReport/com.hazelcast.jet.impl.connector/HazelcastConnectorTest/test_defaultFilter_mapJournal/

```
Error Message
expected:<2> but was:<1>
Stacktrace
java.lang.AssertionError: expected:<2> but was:<1>
	at com.hazelcast.jet.impl.connector.HazelcastConnectorTest.lambda$test_defaultFilter_mapJournal$12(HazelcastConnectorTest.java:344)
	at com.hazelcast.jet.impl.connector.HazelcastConnectorTest.test_defaultFilter_mapJournal(HazelcastConnectorTest.java:343)
```

**Comment by viliam-durina** [comment]
http://jenkins.hazelcast.com/job/jet-oss-pr-builder/216/testReport/junit/com.hazelcast.jet.impl.connector/HazelcastConnectorTest/test_defaultFilter_mapJournal/

```
java.lang.AssertionError: expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.jet.impl.connector.HazelcastConnectorTest.lambda$test_defaultFilter_mapJournal$12(HazelcastConnectorTest.java:343)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:196)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1307)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1324)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:161)
	at com.hazelcast.jet.impl.connector.HazelcastConnectorTest.test_defaultFilter_mapJournal(HazelcastConnectorTest.java:342)
```

**Comment by viliam-durina** [comment]
From logs:

    Finished Running Test: test_defaultFilter_mapJournal in 51.707 seconds.

Looks like a tooo slow PR builder again.
