### ISSUE TITLE
Kafka exception not suppressed on Job cancel

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#824]
I saw this once or twice, Jet 0.6, closing a job with a Kafka source

```
12:19:52.854 WARN  hz._hzInstance_1_amsjug.jet.blocking.thread-3 c.h.j.i.e.TaskletExecutionService - [127.0.0.1]:5701 [xxx] [0.6] Exception in ProcessorTasklet{Kafka Source#3} 
org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:447)
    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:254)
    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:214)
    at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:190)
    at org.apache.kafka.clients.consumer.internals.Fetcher.getTopicMetadata(Fetcher.java:314)
    at org.apache.kafka.clients.consumer.KafkaConsumer.partitionsFor(KafkaConsumer.java:1481)
    at com.hazelcast.jet.kafka.impl.StreamKafkaP.assignPartitions(StreamKafkaP.java:116)
    at com.hazelcast.jet.kafka.impl.StreamKafkaP.complete(StreamKafkaP.java:165)
    at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:253)
    at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:143)
    at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:136)
    at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:187)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
    ... 17 common frames omitted
```

@viliam-durina  Thinks it should be suppressed, not a real issue but will cause confusion

**Comment by viliam-durina** [comment]
It happens when job is cancelled when we interrupt threads.

**Comment by cangencer** [comment]
Kafka can still fail on `close()` method. Not critical exception, but we should just ignore it.

```
52:06,815 [Consumer clientId=consumer-4, groupId=] Failed to close coordinator
org.apache.kafka.common.errors.InterruptException: java.lang.InterruptedException
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.maybeThrowInterruptException(ConsumerNetworkClient.java:447)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:254)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:275)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.disconnect(ConsumerNetworkClient.java:393)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.coordinatorDead(AbstractCoordinator.java:653)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onFailure(AbstractCoordinator.java:797)
	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onFailure(RequestFuture.java:209)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireFailure(RequestFuture.java:177)
	at org.apache.kafka.clients.consumer.internals.RequestFuture.raise(RequestFuture.java:147)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:502)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:353)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.failUnsentRequests(ConsumerNetworkClient.java:416)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.disconnect(ConsumerNetworkClient.java:388)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.coordinatorDead(AbstractCoordinator.java:653)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.coordinator(AbstractCoordinator.java:638)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.coordinatorUnknown(AbstractCoordinator.java:629)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.maybeLeaveGroup(AbstractCoordinator.java:717)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:698)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:498)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1729)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1697)
	at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1672)
	at com.hazelcast.jet.kafka.impl.StreamKafkaP.close(StreamKafkaP.java:205)
```
