### ISSUE TITLE
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorCooperativeCompleteThrows_then_failJob

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#845]
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet-sonar/com.hazelcast.jet$hazelcast-jet-core/1192/testReport/junit/com.hazelcast.jet.core/ExecutionLifecycleTest/when_processorCooperativeCompleteThrows_then_failJob/

```
Error Message
expected:<8> but was:<4>
Stacktrace
java.lang.AssertionError: expected:<8> but was:<4>
	at com.hazelcast.jet.core.ExecutionLifecycleTest.assertPClosedWithError(ExecutionLifecycleTest.java:525)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorCooperativeCompleteThrows_then_failJob(ExecutionLifecycleTest.java:293)
```

**Comment by cangencer** [comment]
Looks like this failure is caused because job is failed on one node before the other has had chance to init.
