### ISSUE TITLE
com.hazelcast.jet.core.JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot_singleStage

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#846]
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet-sonar/com.hazelcast.jet$hazelcast-jet-core/1193/testReport/junit/com.hazelcast.jet.core/JobRestartWithSnapshotTest/when_nodeDown_then_jobRestartsFromSnapshot_singleStage/

**Comment by cangencer** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/jet-sonar/com.hazelcast.jet$hazelcast-jet-core/1570/testReport/junit/com.hazelcast.jet.core/JobRestartWithSnapshotTest/when_nodeDown_then_jobRestartsFromSnapshot_singleStage/

```
Stacktrace
java.lang.NullPointerException
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.waitForNextSnapshot(JobRestartWithSnapshotTest.java:311)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot(JobRestartWithSnapshotTest.java:216)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.when_nodeDown_then_jobRestartsFromSnapshot_singleStage(JobRestartWithSnapshotTest.java:105)
```
