### ISSUE TITLE
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorProcessThrows_then_failJob

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-jet#860]
https://hazelcast-l337.ci.cloudbees.com/job/jet-pr-builder/com.hazelcast.jet$hazelcast-jet-core/2703/testReport/junit/com.hazelcast.jet.core/ExecutionLifecycleTest/when_processorProcessThrows_then_failJob/

```
Error Message

expected:<8> but was:<4>

Stacktrace

java.lang.AssertionError: expected:<8> but was:<4>
	at com.hazelcast.jet.core.ExecutionLifecycleTest.assertPClosedWithError(ExecutionLifecycleTest.java:525)
	at com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorProcessThrows_then_failJob(ExecutionLifecycleTest.java:275)

```

**Comment by viliam-durina** [comment]
Fixed in #861
