### ISSUE TITLE
com.hazelcast.jet.core.SplitBrainTest.when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#918]
https://hazelcast-l337.ci.cloudbees.com/job/jet-pr-builder/com.hazelcast.jet$hazelcast-jet-core/2834/testReport/junit/com.hazelcast.jet.core/SplitBrainTest/when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed/

```
Error Message
expected:<RESTARTING> but was:<FAILED>
Stacktrace
java.lang.AssertionError: expected:<RESTARTING> but was:<FAILED>
	at com.hazelcast.jet.core.SplitBrainTest.lambda$when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed$26(SplitBrainTest.java:304)
	at com.hazelcast.jet.core.SplitBrainTest.when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed(SplitBrainTest.java:304)
```

**Comment by viliam-durina** [comment]
By looking at the test output it seems to me that we've lost the JobRecord. There are 5 members in the test, we terminate 4 of them forcefully. This is only a hypothesis, i couldn't reproduce it locally. I tried to terminate instances at once in parallel to increase the chance of losing a partition, because one `terminate` call takes about 50ms, which might be enough for the backup to pick up and replicate.
```
12:50:01,500 ERROR || - [StartExecutionOperation] hz._hzInstance_69_jet.generic-operation.thread-3 - [127.0.0.1]:5067 [jet] [0.7-SNAPSHOT] Job with id d454-ac6b-9a41-212f not found
com.hazelcast.jet.core.JobNotFoundException: Job with id d454-ac6b-9a41-212f not found
	at com.hazelcast.jet.impl.JobCoordinationService.getJobConfig(JobCoordinationService.java:415)
	at com.hazelcast.jet.impl.JobCoordinationService.getClassLoader(JobCoordinationService.java:107)
	at com.hazelcast.jet.impl.JetService.getClassLoader(JetService.java:159)
	at com.hazelcast.jet.impl.execution.ExecutionContext.beginExecution(ExecutionContext.java:124)
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:50)
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:44)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```

**Comment by cangencer** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/999/testReport/junit/com.hazelcast.jet.core/SplitBrainTest/when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed/

```
Error Message
test timed out after 300000 milliseconds
Stacktrace
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
	at com.hazelcast.jet.impl.JetService.shutDownJobs(JetService.java:146)
	at com.hazelcast.jet.impl.JetInstanceImpl.shutdown(JetInstanceImpl.java:112)
	at com.hazelcast.jet.core.SplitBrainTest.when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed(SplitBrainTest.java:307)
```

**Comment by viliam-durina** [comment]
This is a real problem: one of 5 members in the test did not terminate the job execution and the shutdown got stuck [on this line](https://github.com/hazelcast/hazelcast-jet/blob/f3b739b39f3c8ff19fa230c388728c969a37f70e/hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/SplitBrainTest.java#L307).
I failed to reproduce the issue locally and I reviewed many code paths, but couldn't figure out the root cause.

**Comment by cangencer** [comment]
New failure

http://jenkins.hazelcast.com/job/Jet-pr-builder/10/testReport/junit/com.hazelcast.jet.core/SplitBrainTest/when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed/

**Comment by cangencer** [comment]
http://jenkins.hazelcast.com/job/jet-oss-master-zulu-jdk11/4/testReport/junit/com.hazelcast.jet.core/SplitBrainTest/when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed/

```
Error Message
test timed out after 300000 milliseconds
Stacktrace
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.1/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@11.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.
```

**Comment by viliam-durina** [comment]
Again: http://jenkins.hazelcast.com/job/jet-oss-pr-builder/156/testReport/junit/com.hazelcast.jet.core/SplitBrainTest/when_newMemberIsAddedAfterClusterSizeFallsBelowQuorumSize_then_jobRestartDoesNotSucceed/
