### ISSUE TITLE
com.hazelcast.jet.impl.connector.HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-jet#948]
https://hazelcast-l337.ci.cloudbees.com/job/jet-pr-builder/2918/

```
Error Message

output continues after shutdown expected:<41> but was:<42>

Stacktrace

java.lang.AssertionError: output continues after shutdown expected:<41> but was:<42>
	at com.hazelcast.jet.impl.connector.HazelcastConnector_RestartTest.lambda$when_iListWrittenAndMemberShutdown_then_jobRestarts$2(HazelcastConnector_RestartTest.java:100)
	at com.hazelcast.jet.impl.connector.HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts(HazelcastConnector_RestartTest.java:100)

```

**Comment by viliam-durina** [comment]
[Full test output from S3 archive](https://github.com/hazelcast/hazelcast-jet/files/2339272/test_output.txt)

**Comment by cangencer** [comment]
Not able to reproduce and hasn't failed again in two months. Suspect it might be related to an upstream change in Hazelcast.
