### ISSUE TITLE
SerializableClientConfig ignores all configs other than group name/password

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-jet#949]
```
 Pipeline.create()
  .drawFrom(Sources.<Integer, Val>remoteMap("test", clientConfig))
  .drainTo(Sinks.remoteMapWithEntryProcessor("test", clientConfig, entryKey(), o -> new EP(5)));       
```

Problem is, data in `test` IMAP & `EP` class is `IdentifiedDataSerializable`. I have Serialization config in my client config but I see that it ignored since client config wrapped into `SerializableClientConfig` which only contains group name/password & list of addresses.

That causes below exception:

```
WARNING: [192.168.5.73]:5702 [jet] [0.6.1] Execution of job bd10-2644-260a-50cc, execution 2fe1-65a9-d2f3-9ee6 failed after 590 ms
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{remoteMapWithEntryProcessorSink(test)#0}: java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: No DataSerializerFactory registered for namespace: 1
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

**Comment by cangencer** [comment]
Fixed by #1147
