### ISSUE TITLE
com.hazelcast.jet.impl.execution.WatermarkCoalescer_IntegrationTest.when_i1_aheadAndIdle_i2_activeNoWm_then_wmForwardedAfterADelay[TWO_QUEUES]

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast-jet#955]
https://hazelcast-l337.ci.cloudbees.com/job/jet-pr-builder/2927/
```
Error Message

expected:<1> but was:<0>

Stacktrace

java.lang.AssertionError: expected:<1> but was:<0>
	at com.hazelcast.jet.impl.execution.WatermarkCoalescer_IntegrationTest.lambda$when_i1_aheadAndIdle_i2_activeNoWm_then_wmForwardedAfterADelay$11(WatermarkCoalescer_IntegrationTest.java:220)
	at com.hazelcast.jet.impl.execution.WatermarkCoalescer_IntegrationTest.when_i1_aheadAndIdle_i2_activeNoWm_then_wmForwardedAfterADelay(WatermarkCoalescer_IntegrationTest.java:220)
```

**Comment by cangencer** [comment]
Same error here: https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/816/testReport/junit/com.hazelcast.jet.impl.execution/WatermarkCoalescer_IntegrationTest/when_i1_active_i2_activeNoWm_then_wmForwardedAfterDelay_TWO_EDGES_/
