### ISSUE TITLE
remoteMap with DistributedFunction fails with ClassNotFoundException

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-jet#957]
https://github.com/hazelcast/hazelcast-jet/blob/26c7ae304c91416eea8ae5b61e7b473ac9cc3f0f/hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/SourcesTest.java#L125

Above test fails with below exception if remote cluster started using Hazelcast library only (No Jet related classes)

```
WARNING: [192.168.5.73]:6701 [jet] [0.6.1] Exception in ProcessorTasklet{remoteMapSource(test)#0}
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: com.hazelcast.jet.core.processor.SourceProcessors$1
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:86)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:75)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.client.impl.protocol.task.map.MapFetchWithQueryMessageTask.prepareOperation(MapFetchWithQueryMessageTask.java:56)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:62)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:155)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:162)
	at com.hazelcast.client.map.impl.ClientMapQueryPartitionIterator.fetch(ClientMapQueryPartitionIterator.java:67)
	at com.hazelcast.map.impl.iterator.AbstractMapQueryPartitionIterator.advance(AbstractMapQueryPartitionIterator.java:106)
	at com.hazelcast.map.impl.iterator.AbstractMapQueryPartitionIterator.hasNext(AbstractMapQueryPartitionIterator.java:83)
	at com.hazelcast.jet.impl.connector.ReadWithPartitionIteratorP.lambda$new$0(ReadWithPartitionIteratorP.java:78)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:414)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:430)
	at com.hazelcast.jet.impl.connector.ReadWithPartitionIteratorP.complete(ReadWithPartitionIteratorP.java:142)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:253)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:143)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:136)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.hazelcast.jet.core.processor.SourceProcessors$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:173)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:147)
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:615)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1863)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1746)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2037)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1568)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:82)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:75)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:187)
	at com.hazelcast.client.impl.protocol.task.map.MapFetchWithQueryMessageTask.prepareOperation(MapFetchWithQueryMessageTask.java:56)
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:62)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.doRun(AbstractMessageTask.java:111)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:101)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:155)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)

```

**Comment by gokhanoner** [comment]
Test:

Hazelcast Member, dependency: hazelcast:hazelcast-all:3.10.2

```
        HazelcastInstance hz = Hazelcast.newHazelcastInstance();
        IntStream.range(0, 10).forEach(i -> hz.getMap("test").put(i, i));
```


Jet member

```
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.getNetworkConfig().addAddress("127.0.0.1:5701");

        JetInstance jet = Jet.newJetInstance();

        Pipeline p = Pipeline.create();

        p
                .drawFrom(Sources.<Integer, Integer, Integer>remoteMap("test", clientConfig, Predicates.alwaysTrue(), Map.Entry::getValue))
                .drainTo(Sinks.logger());

        jet.newJob(p).join();
```

**Comment by cangencer** [comment]
Projections and predicates are run on the remote node, so the node would have need to have these in the classpath.  Please read the javadoc

```
     * <h4>Predicate/projection class requirements</h4>
     *
     * The classes implementing {@code predicateFn} and {@code projectionFn}
     * need to be available on the cluster's classpath, or loaded using
     * <em>Hazelcast User Code Deployment</em>. It's not enough to add them to
     * job classpath in {@link JobConfig}. Same is
     * true for the class of the objects stored in the cache itself. If you
     * cannot fulfill these conditions, use {@link #remoteCacheJournal(String,
     * ClientConfig, JournalInitialPosition)} and add a subsequent {@link
     * GeneralStage#map map} or {@link GeneralStage#filter filter} stage.
```

**Comment by gokhanoner** [comment]
Thanks @cangencer
