### ISSUE TITLE
com.hazelcast.jet.core.JobRestartWithSnapshotTest.stressTest

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#963]
```
Error Message
java.lang.AssertionError: No more snapshots produced after restart
Stacktrace
java.util.concurrent.ExecutionException: java.lang.AssertionError: No more snapshots produced after restart
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.stressTest(JobRestartWithSnapshotTest.java:426)
Caused by: java.lang.AssertionError: No more snapshots produced after restart
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$waitForNextSnapshot$8(JobRestartWithSnapshotTest.java:365)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.waitForNextSnapshot(JobRestartWithSnapshotTest.java:362)
	at com.hazelcast.jet.core.JobRestartWithSnapshotTest.lambda$stressTest$9(JobRestartWithSnapshotTest.java:422)
```

https://hazelcast-l337.ci.cloudbees.com/view/Jet/job/jet/com.hazelcast.jet$hazelcast-jet-core/815/testReport/junit/com.hazelcast.jet.core/JobRestartWithSnapshotTest/stressTest/

**Comment by viliam-durina** [comment]
Fixed by #946
