### ISSUE TITLE
Don't use stateful flush function in mapWithMerging

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#968]
See #967 where a quick workaround was merged.

**Comment by viliam-durina** [comment]
The error was
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataCollectionWithNonNullKeyValidation(MapProxySupport.java:1214)
	at com.hazelcast.map.impl.proxy.MapProxySupport.executeOnKeysInternal(MapProxySupport.java:1094)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnKeysInternal(MapProxyImpl.java:105)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.executeOnKeys(MapProxyImpl.java:665)
	at com.hazelcast.jet.impl.connector.HazelcastWriters.lambda$null$bff5069d$1(HazelcastWriters.java:137)
	at com.hazelcast.jet.function.DistributedConsumer.accept(DistributedConsumer.java:41)
	at com.hazelcast.jet.impl.connector.WriteBufferedP.process(WriteBufferedP.java:63)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.process(ProcessorWrapper.java:54)
	at com.hazelcast.jet.impl.pipeline.FunctionAdapter$AdaptingProcessor.process(FunctionAdapter.java:161)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:269)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:212)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:205)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:235)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
